version: 1.0.{build}
build:
  project: src/SessionSeven.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - SessionSeven.Functional.Test.dll
  categories:
    except:
    - GPU
    - FileSystem