version: 1.0.{build}
install:
  - cmd: git submodule update --init --recursive
build:
  project: src/SessionSeven.sln
  verbosity: minimal
test:
  assemblies:
    only:
      -
  categories:
    except:
    - GPU
    - FileSystem