version: 1.0.{build}
install:
  - cmd: git submodule update --init --recursive
build:
  project: SessionSeven.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - SessionSeven.Functional.Test
  categories:
    except:
    - GPU
    - FileSystem