version: 1.0.{build}
image: Visual Studio 2019
install:
  - cmd: git submodule update --init --recursive
build:
  project: SessionSeven.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - SessionSeven.Functional.Test
  categories:
    except:
    - GPU
    - FileSystem
skip_commits:
  files:
    - '**/*.png'
    - '**/*.gif'
    - '**/*.md'