//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool on 03.07.2018 18:33:39.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Entities
{
    /// <summary>
    /// Autogenerated game object graph for easy access.
    /// </summary>
    public static partial class Tree
    {
        public static STACK.World World;

        public static partial class Actors
        {
            public static string MouseID = "SessionSeven.Actors.Mouse";
            public static global::SessionSeven.Actors.Mouse Mouse
            {
                get
                {
                    return (global::SessionSeven.Actors.Mouse)World.GetGameObject(MouseID);
                }
            }

            public static string RyanID = "SessionSeven.Actors.Ryan";
            public static global::SessionSeven.Actors.Ryan Ryan
            {
                get
                {
                    return (global::SessionSeven.Actors.Ryan)World.GetGameObject(RyanID);
                }
            }

            public static string RyanBlooddropID = "SessionSeven.Actors.RyanBlooddrop";
            public static global::SessionSeven.Actors.RyanBlooddrop RyanBlooddrop
            {
                get
                {
                    return (global::SessionSeven.Actors.RyanBlooddrop)World.GetGameObject(RyanBlooddropID);
                }
            }

            public static string RyanVoiceID = "SessionSeven.Actors.RyanVoice";
            public static global::SessionSeven.Actors.RyanVoice RyanVoice
            {
                get
                {
                    return (global::SessionSeven.Actors.RyanVoice)World.GetGameObject(RyanVoiceID);
                }
            }

            public static string SceneID = "SessionSeven.Actors.Scene";
            public static global::SessionSeven.Actors.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.Actors.Scene)World.GetScene(SceneID);
                }
            }
        }

        public static partial class GUI
        {
            public static partial class Dialog
            {
                public static string MenuID = "SessionSeven.GUI.Dialog.Menu";
                public static global::SessionSeven.GUI.Dialog.Menu Menu
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Dialog.Menu)World.GetGameObject(MenuID);
                    }
                }

                public static string SceneID = "SessionSeven.GUI.Dialog.Scene";
                public static global::SessionSeven.GUI.Dialog.Scene Scene
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Dialog.Scene)World.GetScene(SceneID);
                    }
                }
            }
        }

        public static partial class GUI
        {
            public static string FaderID = "SessionSeven.GUI.Fader";
            public static global::SessionSeven.GUI.Fader Fader
            {
                get
                {
                    return (global::SessionSeven.GUI.Fader)World.GetGameObject(FaderID);
                }
            }

            public static string MouseID = "SessionSeven.GUI.Mouse";
            public static global::SessionSeven.GUI.Mouse Mouse
            {
                get
                {
                    return (global::SessionSeven.GUI.Mouse)World.GetGameObject(MouseID);
                }
            }

            public static string SceneID = "SessionSeven.GUI.Scene";
            public static global::SessionSeven.GUI.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.GUI.Scene)World.GetScene(SceneID);
                }
            }

            public static string ScreenTextID = "SessionSeven.GUI.ScreenText";
            public static global::SessionSeven.GUI.ScreenText ScreenText
            {
                get
                {
                    return (global::SessionSeven.GUI.ScreenText)World.GetGameObject(ScreenTextID);
                }
            }
        }

        public static partial class GUI
        {
            public static partial class Interaction
            {
                public static string ActionTextLabelID = "SessionSeven.GUI.Interaction.ActionTextLabel";
                public static global::SessionSeven.GUI.Interaction.ActionTextLabel ActionTextLabel
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.ActionTextLabel)World.GetGameObject(ActionTextLabelID);
                    }
                }

                public static string InteractionBarID = "SessionSeven.GUI.Interaction.InteractionBar";
                public static global::SessionSeven.GUI.Interaction.InteractionBar InteractionBar
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.InteractionBar)World.GetGameObject(InteractionBarID);
                    }
                }

                public static string SceneID = "SessionSeven.GUI.Interaction.Scene";
                public static global::SessionSeven.GUI.Interaction.Scene Scene
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.Scene)World.GetScene(SceneID);
                    }
                }

                public static string ScrollDownButtonID = "SessionSeven.GUI.Interaction.ScrollDownButton";
                public static global::SessionSeven.GUI.Interaction.ScrollDownButton ScrollDownButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.ScrollDownButton)World.GetGameObject(ScrollDownButtonID);
                    }
                }

                public static string ScrollUpButtonID = "SessionSeven.GUI.Interaction.ScrollUpButton";
                public static global::SessionSeven.GUI.Interaction.ScrollUpButton ScrollUpButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.ScrollUpButton)World.GetGameObject(ScrollUpButtonID);
                    }
                }

                public static string VerbsID = "SessionSeven.GUI.Interaction.Verbs";
                public static global::SessionSeven.GUI.Interaction.Verbs Verbs
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.Verbs)World.GetGameObject(VerbsID);
                    }
                }

                public static string GiveButtonID = "SessionSeven.GUI.Interaction.GiveButton";
                public static global::SessionSeven.GUI.Interaction.GiveButton GiveButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.GiveButton)World.GetGameObject(GiveButtonID);
                    }
                }

                public static string OpenButtonID = "SessionSeven.GUI.Interaction.OpenButton";
                public static global::SessionSeven.GUI.Interaction.OpenButton OpenButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.OpenButton)World.GetGameObject(OpenButtonID);
                    }
                }

                public static string CloseButtonID = "SessionSeven.GUI.Interaction.CloseButton";
                public static global::SessionSeven.GUI.Interaction.CloseButton CloseButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.CloseButton)World.GetGameObject(CloseButtonID);
                    }
                }

                public static string PickButtonID = "SessionSeven.GUI.Interaction.PickButton";
                public static global::SessionSeven.GUI.Interaction.PickButton PickButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.PickButton)World.GetGameObject(PickButtonID);
                    }
                }

                public static string LookButtonID = "SessionSeven.GUI.Interaction.LookButton";
                public static global::SessionSeven.GUI.Interaction.LookButton LookButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.LookButton)World.GetGameObject(LookButtonID);
                    }
                }

                public static string TalkButtonID = "SessionSeven.GUI.Interaction.TalkButton";
                public static global::SessionSeven.GUI.Interaction.TalkButton TalkButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.TalkButton)World.GetGameObject(TalkButtonID);
                    }
                }

                public static string UseButtonID = "SessionSeven.GUI.Interaction.UseButton";
                public static global::SessionSeven.GUI.Interaction.UseButton UseButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.UseButton)World.GetGameObject(UseButtonID);
                    }
                }

                public static string PushButtonID = "SessionSeven.GUI.Interaction.PushButton";
                public static global::SessionSeven.GUI.Interaction.PushButton PushButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.PushButton)World.GetGameObject(PushButtonID);
                    }
                }

                public static string PullButtonID = "SessionSeven.GUI.Interaction.PullButton";
                public static global::SessionSeven.GUI.Interaction.PullButton PullButton
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.PullButton)World.GetGameObject(PullButtonID);
                    }
                }

                public static string VerbsHighlightID = "SessionSeven.GUI.Interaction.VerbsHighlight";
                public static global::SessionSeven.GUI.Interaction.VerbsHighlight VerbsHighlight
                {
                    get
                    {
                        return (global::SessionSeven.GUI.Interaction.VerbsHighlight)World.GetGameObject(VerbsHighlightID);
                    }
                }
            }
        }

        public static partial class GUI
        {
            public static partial class PositionSelection
            {
                public static string LabelID = "SessionSeven.GUI.PositionSelection.Label";
                public static global::SessionSeven.GUI.PositionSelection.Label Label
                {
                    get
                    {
                        return (global::SessionSeven.GUI.PositionSelection.Label)World.GetGameObject(LabelID);
                    }
                }

                public static string SceneID = "SessionSeven.GUI.PositionSelection.Scene";
                public static global::SessionSeven.GUI.PositionSelection.Scene Scene
                {
                    get
                    {
                        return (global::SessionSeven.GUI.PositionSelection.Scene)World.GetScene(SceneID);
                    }
                }
            }
        }

        public static partial class InventoryItems
        {
            public static string AnimalSkeletonID = "SessionSeven.InventoryItems.AnimalSkeleton";
            public static global::SessionSeven.InventoryItems.AnimalSkeleton AnimalSkeleton
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.AnimalSkeleton)World.GetGameObject(AnimalSkeletonID);
                }
            }

            public static string BandagesID = "SessionSeven.InventoryItems.Bandages";
            public static global::SessionSeven.InventoryItems.Bandages Bandages
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Bandages)World.GetGameObject(BandagesID);
                }
            }

            public static string BandagesCutID = "SessionSeven.InventoryItems.BandagesCut";
            public static global::SessionSeven.InventoryItems.BandagesCut BandagesCut
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.BandagesCut)World.GetGameObject(BandagesCutID);
                }
            }

            public static string BandageStripID = "SessionSeven.InventoryItems.BandageStrip";
            public static global::SessionSeven.InventoryItems.BandageStrip BandageStrip
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.BandageStrip)World.GetGameObject(BandageStripID);
                }
            }

            public static string BatonID = "SessionSeven.InventoryItems.Baton";
            public static global::SessionSeven.InventoryItems.Baton Baton
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Baton)World.GetGameObject(BatonID);
                }
            }

            public static string BatonWithStringID = "SessionSeven.InventoryItems.BatonWithString";
            public static global::SessionSeven.InventoryItems.BatonWithString BatonWithString
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.BatonWithString)World.GetGameObject(BatonWithStringID);
                }
            }

            public static string BatteryAID = "SessionSeven.InventoryItems.BatteryA";
            public static global::SessionSeven.InventoryItems.BatteryA BatteryA
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.BatteryA)World.GetGameObject(BatteryAID);
                }
            }

            public static string BatteryBID = "SessionSeven.InventoryItems.BatteryB";
            public static global::SessionSeven.InventoryItems.BatteryB BatteryB
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.BatteryB)World.GetGameObject(BatteryBID);
                }
            }

            public static string BlanketID = "SessionSeven.InventoryItems.Blanket";
            public static global::SessionSeven.InventoryItems.Blanket Blanket
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Blanket)World.GetGameObject(BlanketID);
                }
            }

            public static string CrowbarID = "SessionSeven.InventoryItems.Crowbar";
            public static global::SessionSeven.InventoryItems.Crowbar Crowbar
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Crowbar)World.GetGameObject(CrowbarID);
                }
            }

            public static string CrowbarBrokenID = "SessionSeven.InventoryItems.CrowbarBroken";
            public static global::SessionSeven.InventoryItems.CrowbarBroken CrowbarBroken
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.CrowbarBroken)World.GetGameObject(CrowbarBrokenID);
                }
            }

            public static string DrawerKeyID = "SessionSeven.InventoryItems.DrawerKey";
            public static global::SessionSeven.InventoryItems.DrawerKey DrawerKey
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.DrawerKey)World.GetGameObject(DrawerKeyID);
                }
            }

            public static string DroneID = "SessionSeven.InventoryItems.Drone";
            public static global::SessionSeven.InventoryItems.Drone Drone
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Drone)World.GetGameObject(DroneID);
                }
            }

            public static string DronePackageID = "SessionSeven.InventoryItems.DronePackage";
            public static global::SessionSeven.InventoryItems.DronePackage DronePackage
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.DronePackage)World.GetGameObject(DronePackageID);
                }
            }

            public static string DrugPrescriptionRyanID = "SessionSeven.InventoryItems.DrugPrescriptionRyan";
            public static global::SessionSeven.InventoryItems.DrugPrescriptionRyan DrugPrescriptionRyan
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.DrugPrescriptionRyan)World.GetGameObject(DrugPrescriptionRyanID);
                }
            }

            public static string EnvelopeID = "SessionSeven.InventoryItems.Envelope";
            public static global::SessionSeven.InventoryItems.Envelope Envelope
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Envelope)World.GetGameObject(EnvelopeID);
                }
            }

            public static string FlashlightID = "SessionSeven.InventoryItems.Flashlight";
            public static global::SessionSeven.InventoryItems.Flashlight Flashlight
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Flashlight)World.GetGameObject(FlashlightID);
                }
            }

            public static string GuitarStringsID = "SessionSeven.InventoryItems.GuitarStrings";
            public static global::SessionSeven.InventoryItems.GuitarStrings GuitarStrings
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.GuitarStrings)World.GetGameObject(GuitarStringsID);
                }
            }

            public static string HammerID = "SessionSeven.InventoryItems.Hammer";
            public static global::SessionSeven.InventoryItems.Hammer Hammer
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Hammer)World.GetGameObject(HammerID);
                }
            }

            public static string HazelnutsID = "SessionSeven.InventoryItems.Hazelnuts";
            public static global::SessionSeven.InventoryItems.Hazelnuts Hazelnuts
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Hazelnuts)World.GetGameObject(HazelnutsID);
                }
            }

            public static string PaperclipID = "SessionSeven.InventoryItems.Paperclip";
            public static global::SessionSeven.InventoryItems.Paperclip Paperclip
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Paperclip)World.GetGameObject(PaperclipID);
                }
            }

            public static string PaperclipsID = "SessionSeven.InventoryItems.Paperclips";
            public static global::SessionSeven.InventoryItems.Paperclips Paperclips
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Paperclips)World.GetGameObject(PaperclipsID);
                }
            }

            public static string PillsID = "SessionSeven.InventoryItems.Pills";
            public static global::SessionSeven.InventoryItems.Pills Pills
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Pills)World.GetGameObject(PillsID);
                }
            }

            public static string PortraitID = "SessionSeven.InventoryItems.Portrait";
            public static global::SessionSeven.InventoryItems.Portrait Portrait
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Portrait)World.GetGameObject(PortraitID);
                }
            }

            public static string RemoteControlID = "SessionSeven.InventoryItems.RemoteControl";
            public static global::SessionSeven.InventoryItems.RemoteControl RemoteControl
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.RemoteControl)World.GetGameObject(RemoteControlID);
                }
            }

            public static string RFIDAntennaCabinetID = "SessionSeven.InventoryItems.RFIDAntennaCabinet";
            public static global::SessionSeven.InventoryItems.RFIDAntennaCabinet RFIDAntennaCabinet
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.RFIDAntennaCabinet)World.GetGameObject(RFIDAntennaCabinetID);
                }
            }

            public static string RFIDAntennaShelfID = "SessionSeven.InventoryItems.RFIDAntennaShelf";
            public static global::SessionSeven.InventoryItems.RFIDAntennaShelf RFIDAntennaShelf
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.RFIDAntennaShelf)World.GetGameObject(RFIDAntennaShelfID);
                }
            }

            public static string RFIDAntennaBoxCabinetID = "SessionSeven.InventoryItems.RFIDAntennaBoxCabinet";
            public static global::SessionSeven.InventoryItems.RFIDAntennaBoxCabinet RFIDAntennaBoxCabinet
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.RFIDAntennaBoxCabinet)World.GetGameObject(RFIDAntennaBoxCabinetID);
                }
            }

            public static string RFIDAntennaBoxShelfID = "SessionSeven.InventoryItems.RFIDAntennaBoxShelf";
            public static global::SessionSeven.InventoryItems.RFIDAntennaBoxShelf RFIDAntennaBoxShelf
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.RFIDAntennaBoxShelf)World.GetGameObject(RFIDAntennaBoxShelfID);
                }
            }

            public static string RFIDBookID = "SessionSeven.InventoryItems.RFIDBook";
            public static global::SessionSeven.InventoryItems.RFIDBook RFIDBook
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.RFIDBook)World.GetGameObject(RFIDBookID);
                }
            }

            public static string SawKitID = "SessionSeven.InventoryItems.SawKit";
            public static global::SessionSeven.InventoryItems.SawKit SawKit
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.SawKit)World.GetGameObject(SawKitID);
                }
            }

            public static string ScissorsID = "SessionSeven.InventoryItems.Scissors";
            public static global::SessionSeven.InventoryItems.Scissors Scissors
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Scissors)World.GetGameObject(ScissorsID);
                }
            }

            public static string ScrewdriverID = "SessionSeven.InventoryItems.Screwdriver";
            public static global::SessionSeven.InventoryItems.Screwdriver Screwdriver
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.Screwdriver)World.GetGameObject(ScrewdriverID);
                }
            }

            public static string TherapyLogID = "SessionSeven.InventoryItems.TherapyLog";
            public static global::SessionSeven.InventoryItems.TherapyLog TherapyLog
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.TherapyLog)World.GetGameObject(TherapyLogID);
                }
            }

            public static string WoodenBoxID = "SessionSeven.InventoryItems.WoodenBox";
            public static global::SessionSeven.InventoryItems.WoodenBox WoodenBox
            {
                get
                {
                    return (global::SessionSeven.InventoryItems.WoodenBox)World.GetGameObject(WoodenBoxID);
                }
            }
        }

        public static partial class Basement
        {
            public static string BloodOnFloorID = "SessionSeven.Basement.BloodOnFloor";
            public static global::SessionSeven.Basement.BloodOnFloor BloodOnFloor
            {
                get
                {
                    return (global::SessionSeven.Basement.BloodOnFloor)World.GetGameObject(BloodOnFloorID);
                }
            }

            public static string BoilerID = "SessionSeven.Basement.Boiler";
            public static global::SessionSeven.Basement.Boiler Boiler
            {
                get
                {
                    return (global::SessionSeven.Basement.Boiler)World.GetGameObject(BoilerID);
                }
            }

            public static string BoxScrewsID = "SessionSeven.Basement.BoxScrews";
            public static global::SessionSeven.Basement.BoxScrews BoxScrews
            {
                get
                {
                    return (global::SessionSeven.Basement.BoxScrews)World.GetGameObject(BoxScrewsID);
                }
            }

            public static string BoxWritingMaterialsID = "SessionSeven.Basement.BoxWritingMaterials";
            public static global::SessionSeven.Basement.BoxWritingMaterials BoxWritingMaterials
            {
                get
                {
                    return (global::SessionSeven.Basement.BoxWritingMaterials)World.GetGameObject(BoxWritingMaterialsID);
                }
            }

            public static string CabinetLeftDoorID = "SessionSeven.Basement.CabinetLeftDoor";
            public static global::SessionSeven.Basement.CabinetLeftDoor CabinetLeftDoor
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetLeftDoor)World.GetGameObject(CabinetLeftDoorID);
                }
            }

            public static string CabinetLockID = "SessionSeven.Basement.CabinetLock";
            public static global::SessionSeven.Basement.CabinetLock CabinetLock
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetLock)World.GetGameObject(CabinetLockID);
                }
            }

            public static string CabinetRightDoorID = "SessionSeven.Basement.CabinetRightDoor";
            public static global::SessionSeven.Basement.CabinetRightDoor CabinetRightDoor
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetRightDoor)World.GetGameObject(CabinetRightDoorID);
                }
            }

            public static string CabinetSawKitID = "SessionSeven.Basement.CabinetSawKit";
            public static global::SessionSeven.Basement.CabinetSawKit CabinetSawKit
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetSawKit)World.GetGameObject(CabinetSawKitID);
                }
            }

            public static string CabinetScrapbooksLeftID = "SessionSeven.Basement.CabinetScrapbooksLeft";
            public static global::SessionSeven.Basement.CabinetScrapbooksLeft CabinetScrapbooksLeft
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetScrapbooksLeft)World.GetGameObject(CabinetScrapbooksLeftID);
                }
            }

            public static string CabinetScrapbooksRightID = "SessionSeven.Basement.CabinetScrapbooksRight";
            public static global::SessionSeven.Basement.CabinetScrapbooksRight CabinetScrapbooksRight
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetScrapbooksRight)World.GetGameObject(CabinetScrapbooksRightID);
                }
            }

            public static string CabinetSuppliesID = "SessionSeven.Basement.CabinetSupplies";
            public static global::SessionSeven.Basement.CabinetSupplies CabinetSupplies
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetSupplies)World.GetGameObject(CabinetSuppliesID);
                }
            }

            public static string CabinetToolboxID = "SessionSeven.Basement.CabinetToolbox";
            public static global::SessionSeven.Basement.CabinetToolbox CabinetToolbox
            {
                get
                {
                    return (global::SessionSeven.Basement.CabinetToolbox)World.GetGameObject(CabinetToolboxID);
                }
            }

            public static string CactusID = "SessionSeven.Basement.Cactus";
            public static global::SessionSeven.Basement.Cactus Cactus
            {
                get
                {
                    return (global::SessionSeven.Basement.Cactus)World.GetGameObject(CactusID);
                }
            }

            public static string CarpetID = "SessionSeven.Basement.Carpet";
            public static global::SessionSeven.Basement.Carpet Carpet
            {
                get
                {
                    return (global::SessionSeven.Basement.Carpet)World.GetGameObject(CarpetID);
                }
            }

            public static string CarpetWallID = "SessionSeven.Basement.CarpetWall";
            public static global::SessionSeven.Basement.CarpetWall CarpetWall
            {
                get
                {
                    return (global::SessionSeven.Basement.CarpetWall)World.GetGameObject(CarpetWallID);
                }
            }

            public static string CratesID = "SessionSeven.Basement.Crates";
            public static global::SessionSeven.Basement.Crates Crates
            {
                get
                {
                    return (global::SessionSeven.Basement.Crates)World.GetGameObject(CratesID);
                }
            }

            public static string CrowbarID = "SessionSeven.Basement.Crowbar";
            public static global::SessionSeven.Basement.Crowbar Crowbar
            {
                get
                {
                    return (global::SessionSeven.Basement.Crowbar)World.GetGameObject(CrowbarID);
                }
            }

            public static string CrumbsLeftID = "SessionSeven.Basement.CrumbsLeft";
            public static global::SessionSeven.Basement.CrumbsLeft CrumbsLeft
            {
                get
                {
                    return (global::SessionSeven.Basement.CrumbsLeft)World.GetGameObject(CrumbsLeftID);
                }
            }

            public static string CrumbsRightID = "SessionSeven.Basement.CrumbsRight";
            public static global::SessionSeven.Basement.CrumbsRight CrumbsRight
            {
                get
                {
                    return (global::SessionSeven.Basement.CrumbsRight)World.GetGameObject(CrumbsRightID);
                }
            }

            public static string DeskID = "SessionSeven.Basement.Desk";
            public static global::SessionSeven.Basement.Desk Desk
            {
                get
                {
                    return (global::SessionSeven.Basement.Desk)World.GetGameObject(DeskID);
                }
            }

            public static string DoorID = "SessionSeven.Basement.Door";
            public static global::SessionSeven.Basement.Door Door
            {
                get
                {
                    return (global::SessionSeven.Basement.Door)World.GetGameObject(DoorID);
                }
            }

            public static string DrawerLeftID = "SessionSeven.Basement.DrawerLeft";
            public static global::SessionSeven.Basement.DrawerLeft DrawerLeft
            {
                get
                {
                    return (global::SessionSeven.Basement.DrawerLeft)World.GetGameObject(DrawerLeftID);
                }
            }

            public static string DrawerRightID = "SessionSeven.Basement.DrawerRight";
            public static global::SessionSeven.Basement.DrawerRight DrawerRight
            {
                get
                {
                    return (global::SessionSeven.Basement.DrawerRight)World.GetGameObject(DrawerRightID);
                }
            }

            public static string DrillingMachineID = "SessionSeven.Basement.DrillingMachine";
            public static global::SessionSeven.Basement.DrillingMachine DrillingMachine
            {
                get
                {
                    return (global::SessionSeven.Basement.DrillingMachine)World.GetGameObject(DrillingMachineID);
                }
            }

            public static string DrillingMachineCableID = "SessionSeven.Basement.DrillingMachineCable";
            public static global::SessionSeven.Basement.DrillingMachineCable DrillingMachineCable
            {
                get
                {
                    return (global::SessionSeven.Basement.DrillingMachineCable)World.GetGameObject(DrillingMachineCableID);
                }
            }

            public static string DrillingMachineCableTopID = "SessionSeven.Basement.DrillingMachineCableTop";
            public static global::SessionSeven.Basement.DrillingMachineCableTop DrillingMachineCableTop
            {
                get
                {
                    return (global::SessionSeven.Basement.DrillingMachineCableTop)World.GetGameObject(DrillingMachineCableTopID);
                }
            }

            public static string DrillingMachineUsedID = "SessionSeven.Basement.DrillingMachineUsed";
            public static global::SessionSeven.Basement.DrillingMachineUsed DrillingMachineUsed
            {
                get
                {
                    return (global::SessionSeven.Basement.DrillingMachineUsed)World.GetGameObject(DrillingMachineUsedID);
                }
            }

            public static string DroneID = "SessionSeven.Basement.Drone";
            public static global::SessionSeven.Basement.Drone Drone
            {
                get
                {
                    return (global::SessionSeven.Basement.Drone)World.GetGameObject(DroneID);
                }
            }

            public static string DronePackageID = "SessionSeven.Basement.DronePackage";
            public static global::SessionSeven.Basement.DronePackage DronePackage
            {
                get
                {
                    return (global::SessionSeven.Basement.DronePackage)World.GetGameObject(DronePackageID);
                }
            }

            public static string FamiliyPortraitID = "SessionSeven.Basement.FamiliyPortrait";
            public static global::SessionSeven.Basement.FamiliyPortrait FamiliyPortrait
            {
                get
                {
                    return (global::SessionSeven.Basement.FamiliyPortrait)World.GetGameObject(FamiliyPortraitID);
                }
            }

            public static string FoldersID = "SessionSeven.Basement.Folders";
            public static global::SessionSeven.Basement.Folders Folders
            {
                get
                {
                    return (global::SessionSeven.Basement.Folders)World.GetGameObject(FoldersID);
                }
            }

            public static string ForegroundID = "SessionSeven.Basement.Foreground";
            public static global::SessionSeven.Basement.Foreground Foreground
            {
                get
                {
                    return (global::SessionSeven.Basement.Foreground)World.GetGameObject(ForegroundID);
                }
            }

            public static string GuitarID = "SessionSeven.Basement.Guitar";
            public static global::SessionSeven.Basement.Guitar Guitar
            {
                get
                {
                    return (global::SessionSeven.Basement.Guitar)World.GetGameObject(GuitarID);
                }
            }

            public static string GuitarCaseID = "SessionSeven.Basement.GuitarCase";
            public static global::SessionSeven.Basement.GuitarCase GuitarCase
            {
                get
                {
                    return (global::SessionSeven.Basement.GuitarCase)World.GetGameObject(GuitarCaseID);
                }
            }

            public static string GuitarStringsID = "SessionSeven.Basement.GuitarStrings";
            public static global::SessionSeven.Basement.GuitarStrings GuitarStrings
            {
                get
                {
                    return (global::SessionSeven.Basement.GuitarStrings)World.GetGameObject(GuitarStringsID);
                }
            }

            public static string HammerID = "SessionSeven.Basement.Hammer";
            public static global::SessionSeven.Basement.Hammer Hammer
            {
                get
                {
                    return (global::SessionSeven.Basement.Hammer)World.GetGameObject(HammerID);
                }
            }

            public static string HazelnutsID = "SessionSeven.Basement.Hazelnuts";
            public static global::SessionSeven.Basement.Hazelnuts Hazelnuts
            {
                get
                {
                    return (global::SessionSeven.Basement.Hazelnuts)World.GetGameObject(HazelnutsID);
                }
            }

            public static string HazelnutsOnFloorID = "SessionSeven.Basement.HazelnutsOnFloor";
            public static global::SessionSeven.Basement.HazelnutsOnFloor HazelnutsOnFloor
            {
                get
                {
                    return (global::SessionSeven.Basement.HazelnutsOnFloor)World.GetGameObject(HazelnutsOnFloorID);
                }
            }

            public static string LightsID = "SessionSeven.Basement.Lights";
            public static global::SessionSeven.Basement.Lights Lights
            {
                get
                {
                    return (global::SessionSeven.Basement.Lights)World.GetGameObject(LightsID);
                }
            }

            public static string LightSwitchID = "SessionSeven.Basement.LightSwitch";
            public static global::SessionSeven.Basement.LightSwitch LightSwitch
            {
                get
                {
                    return (global::SessionSeven.Basement.LightSwitch)World.GetGameObject(LightSwitchID);
                }
            }

            public static string MedicalCabinetID = "SessionSeven.Basement.MedicalCabinet";
            public static global::SessionSeven.Basement.MedicalCabinet MedicalCabinet
            {
                get
                {
                    return (global::SessionSeven.Basement.MedicalCabinet)World.GetGameObject(MedicalCabinetID);
                }
            }

            public static string MissingToolID = "SessionSeven.Basement.MissingTool";
            public static global::SessionSeven.Basement.MissingTool MissingTool
            {
                get
                {
                    return (global::SessionSeven.Basement.MissingTool)World.GetGameObject(MissingToolID);
                }
            }

            public static string ModemLightID = "SessionSeven.Basement.ModemLight";
            public static global::SessionSeven.Basement.ModemLight ModemLight
            {
                get
                {
                    return (global::SessionSeven.Basement.ModemLight)World.GetGameObject(ModemLightID);
                }
            }

            public static string MouseHoleID = "SessionSeven.Basement.MouseHole";
            public static global::SessionSeven.Basement.MouseHole MouseHole
            {
                get
                {
                    return (global::SessionSeven.Basement.MouseHole)World.GetGameObject(MouseHoleID);
                }
            }

            public static string NutsOnFloorID = "SessionSeven.Basement.NutsOnFloor";
            public static global::SessionSeven.Basement.NutsOnFloor NutsOnFloor
            {
                get
                {
                    return (global::SessionSeven.Basement.NutsOnFloor)World.GetGameObject(NutsOnFloorID);
                }
            }

            public static string LandonPortraitID = "SessionSeven.Basement.LandonPortrait";
            public static global::SessionSeven.Basement.LandonPortrait LandonPortrait
            {
                get
                {
                    return (global::SessionSeven.Basement.LandonPortrait)World.GetGameObject(LandonPortraitID);
                }
            }

            public static string ReceiptID = "SessionSeven.Basement.Receipt";
            public static global::SessionSeven.Basement.Receipt Receipt
            {
                get
                {
                    return (global::SessionSeven.Basement.Receipt)World.GetGameObject(ReceiptID);
                }
            }

            public static string RFIDAntennaCabinetID = "SessionSeven.Basement.RFIDAntennaCabinet";
            public static global::SessionSeven.Basement.RFIDAntennaCabinet RFIDAntennaCabinet
            {
                get
                {
                    return (global::SessionSeven.Basement.RFIDAntennaCabinet)World.GetGameObject(RFIDAntennaCabinetID);
                }
            }

            public static string RFIDAntennaFloorShelfID = "SessionSeven.Basement.RFIDAntennaFloorShelf";
            public static global::SessionSeven.Basement.RFIDAntennaFloorShelf RFIDAntennaFloorShelf
            {
                get
                {
                    return (global::SessionSeven.Basement.RFIDAntennaFloorShelf)World.GetGameObject(RFIDAntennaFloorShelfID);
                }
            }

            public static string RFIDAntennaFloorCabinetID = "SessionSeven.Basement.RFIDAntennaFloorCabinet";
            public static global::SessionSeven.Basement.RFIDAntennaFloorCabinet RFIDAntennaFloorCabinet
            {
                get
                {
                    return (global::SessionSeven.Basement.RFIDAntennaFloorCabinet)World.GetGameObject(RFIDAntennaFloorCabinetID);
                }
            }

            public static string RFIDAntennaShelfID = "SessionSeven.Basement.RFIDAntennaShelf";
            public static global::SessionSeven.Basement.RFIDAntennaShelf RFIDAntennaShelf
            {
                get
                {
                    return (global::SessionSeven.Basement.RFIDAntennaShelf)World.GetGameObject(RFIDAntennaShelfID);
                }
            }

            public static string RyanLyingID = "SessionSeven.Basement.RyanLying";
            public static global::SessionSeven.Basement.RyanLying RyanLying
            {
                get
                {
                    return (global::SessionSeven.Basement.RyanLying)World.GetGameObject(RyanLyingID);
                }
            }

            public static string SceneID = "SessionSeven.Basement.Scene";
            public static global::SessionSeven.Basement.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.Basement.Scene)World.GetScene(SceneID);
                }
            }

            public static string SceneTransparentFloorID = "SessionSeven.Basement.SceneTransparentFloor";
            public static global::SessionSeven.Basement.SceneTransparentFloor SceneTransparentFloor
            {
                get
                {
                    return (global::SessionSeven.Basement.SceneTransparentFloor)World.GetGameObject(SceneTransparentFloorID);
                }
            }

            public static string ScrewdriverID = "SessionSeven.Basement.Screwdriver";
            public static global::SessionSeven.Basement.Screwdriver Screwdriver
            {
                get
                {
                    return (global::SessionSeven.Basement.Screwdriver)World.GetGameObject(ScrewdriverID);
                }
            }

            public static string ShelfID = "SessionSeven.Basement.Shelf";
            public static global::SessionSeven.Basement.Shelf Shelf
            {
                get
                {
                    return (global::SessionSeven.Basement.Shelf)World.GetGameObject(ShelfID);
                }
            }

            public static string ShelfBlanketFlashlightID = "SessionSeven.Basement.ShelfBlanketFlashlight";
            public static global::SessionSeven.Basement.ShelfBlanketFlashlight ShelfBlanketFlashlight
            {
                get
                {
                    return (global::SessionSeven.Basement.ShelfBlanketFlashlight)World.GetGameObject(ShelfBlanketFlashlightID);
                }
            }

            public static string ShelfBoxID = "SessionSeven.Basement.ShelfBox";
            public static global::SessionSeven.Basement.ShelfBox ShelfBox
            {
                get
                {
                    return (global::SessionSeven.Basement.ShelfBox)World.GetGameObject(ShelfBoxID);
                }
            }

            public static string ShelfComicBoxID = "SessionSeven.Basement.ShelfComicBox";
            public static global::SessionSeven.Basement.ShelfComicBox ShelfComicBox
            {
                get
                {
                    return (global::SessionSeven.Basement.ShelfComicBox)World.GetGameObject(ShelfComicBoxID);
                }
            }

            public static string ShelfEngineeringBooksID = "SessionSeven.Basement.ShelfEngineeringBooks";
            public static global::SessionSeven.Basement.ShelfEngineeringBooks ShelfEngineeringBooks
            {
                get
                {
                    return (global::SessionSeven.Basement.ShelfEngineeringBooks)World.GetGameObject(ShelfEngineeringBooksID);
                }
            }

            public static string ShelfRFIDBookID = "SessionSeven.Basement.ShelfRFIDBook";
            public static global::SessionSeven.Basement.ShelfRFIDBook ShelfRFIDBook
            {
                get
                {
                    return (global::SessionSeven.Basement.ShelfRFIDBook)World.GetGameObject(ShelfRFIDBookID);
                }
            }

            public static string ShelfSingleBookID = "SessionSeven.Basement.ShelfSingleBook";
            public static global::SessionSeven.Basement.ShelfSingleBook ShelfSingleBook
            {
                get
                {
                    return (global::SessionSeven.Basement.ShelfSingleBook)World.GetGameObject(ShelfSingleBookID);
                }
            }

            public static string SocketsCenterID = "SessionSeven.Basement.SocketsCenter";
            public static global::SessionSeven.Basement.SocketsCenter SocketsCenter
            {
                get
                {
                    return (global::SessionSeven.Basement.SocketsCenter)World.GetGameObject(SocketsCenterID);
                }
            }

            public static string SocketsLeftID = "SessionSeven.Basement.SocketsLeft";
            public static global::SessionSeven.Basement.SocketsLeft SocketsLeft
            {
                get
                {
                    return (global::SessionSeven.Basement.SocketsLeft)World.GetGameObject(SocketsLeftID);
                }
            }

            public static string ToDoBoardID = "SessionSeven.Basement.ToDoBoard";
            public static global::SessionSeven.Basement.ToDoBoard ToDoBoard
            {
                get
                {
                    return (global::SessionSeven.Basement.ToDoBoard)World.GetGameObject(ToDoBoardID);
                }
            }

            public static string ToolBarID = "SessionSeven.Basement.ToolBar";
            public static global::SessionSeven.Basement.ToolBar ToolBar
            {
                get
                {
                    return (global::SessionSeven.Basement.ToolBar)World.GetGameObject(ToolBarID);
                }
            }

            public static string VentilationShaftID = "SessionSeven.Basement.VentilationShaft";
            public static global::SessionSeven.Basement.VentilationShaft VentilationShaft
            {
                get
                {
                    return (global::SessionSeven.Basement.VentilationShaft)World.GetGameObject(VentilationShaftID);
                }
            }

            public static string WindowLeftID = "SessionSeven.Basement.WindowLeft";
            public static global::SessionSeven.Basement.WindowLeft WindowLeft
            {
                get
                {
                    return (global::SessionSeven.Basement.WindowLeft)World.GetGameObject(WindowLeftID);
                }
            }

            public static string WindowRightID = "SessionSeven.Basement.WindowRight";
            public static global::SessionSeven.Basement.WindowRight WindowRight
            {
                get
                {
                    return (global::SessionSeven.Basement.WindowRight)World.GetGameObject(WindowRightID);
                }
            }

            public static string WoodenBoxID = "SessionSeven.Basement.WoodenBox";
            public static global::SessionSeven.Basement.WoodenBox WoodenBox
            {
                get
                {
                    return (global::SessionSeven.Basement.WoodenBox)World.GetGameObject(WoodenBoxID);
                }
            }

            public static string WoodenPanelID = "SessionSeven.Basement.WoodenPanel";
            public static global::SessionSeven.Basement.WoodenPanel WoodenPanel
            {
                get
                {
                    return (global::SessionSeven.Basement.WoodenPanel)World.GetGameObject(WoodenPanelID);
                }
            }

            public static string WorkbenchID = "SessionSeven.Basement.Workbench";
            public static global::SessionSeven.Basement.Workbench Workbench
            {
                get
                {
                    return (global::SessionSeven.Basement.Workbench)World.GetGameObject(WorkbenchID);
                }
            }
        }

        public static partial class JailCell
        {
            public static string ForegroundID = "SessionSeven.JailCell.Foreground";
            public static global::SessionSeven.JailCell.Foreground Foreground
            {
                get
                {
                    return (global::SessionSeven.JailCell.Foreground)World.GetGameObject(ForegroundID);
                }
            }

            public static string SceneID = "SessionSeven.JailCell.Scene";
            public static global::SessionSeven.JailCell.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.JailCell.Scene)World.GetScene(SceneID);
                }
            }
        }

        public static partial class Letter
        {
            public static string SceneID = "SessionSeven.Letter.Scene";
            public static global::SessionSeven.Letter.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.Letter.Scene)World.GetScene(SceneID);
                }
            }
        }

        public static partial class Office
        {
            public static string RyanID = "SessionSeven.Office.Ryan";
            public static global::SessionSeven.Office.Ryan Ryan
            {
                get
                {
                    return (global::SessionSeven.Office.Ryan)World.GetGameObject(RyanID);
                }
            }

            public static string RyanEyesClosedID = "SessionSeven.Office.RyanEyesClosed";
            public static global::SessionSeven.Office.RyanEyesClosed RyanEyesClosed
            {
                get
                {
                    return (global::SessionSeven.Office.RyanEyesClosed)World.GetGameObject(RyanEyesClosedID);
                }
            }

            public static string SceneID = "SessionSeven.Office.Scene";
            public static global::SessionSeven.Office.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.Office.Scene)World.GetScene(SceneID);
                }
            }

            public static string TableID = "SessionSeven.Office.Table";
            public static global::SessionSeven.Office.Table Table
            {
                get
                {
                    return (global::SessionSeven.Office.Table)World.GetGameObject(TableID);
                }
            }

            public static string TherapistID = "SessionSeven.Office.Therapist";
            public static global::SessionSeven.Office.Therapist Therapist
            {
                get
                {
                    return (global::SessionSeven.Office.Therapist)World.GetGameObject(TherapistID);
                }
            }

            public static string WaterDayID = "SessionSeven.Office.WaterDay";
            public static global::SessionSeven.Office.WaterDay WaterDay
            {
                get
                {
                    return (global::SessionSeven.Office.WaterDay)World.GetGameObject(WaterDayID);
                }
            }

            public static string WaterNightID = "SessionSeven.Office.WaterNight";
            public static global::SessionSeven.Office.WaterNight WaterNight
            {
                get
                {
                    return (global::SessionSeven.Office.WaterNight)World.GetGameObject(WaterNightID);
                }
            }
        }

        public static partial class PaddedCell
        {
            public static string SceneID = "SessionSeven.PaddedCell.Scene";
            public static global::SessionSeven.PaddedCell.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.PaddedCell.Scene)World.GetScene(SceneID);
                }
            }
        }

        public static partial class SunSet
        {
            public static string SceneID = "SessionSeven.SunSet.Scene";
            public static global::SessionSeven.SunSet.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.SunSet.Scene)World.GetScene(SceneID);
                }
            }
        }

        public static partial class Title
        {
            public static string SceneID = "SessionSeven.Title.Scene";
            public static global::SessionSeven.Title.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.Title.Scene)World.GetScene(SceneID);
                }
            }
        }

        public static partial class Cutscenes
        {
            public static string SceneID = "SessionSeven.Cutscenes.Scene";
            public static global::SessionSeven.Cutscenes.Scene Scene
            {
                get
                {
                    return (global::SessionSeven.Cutscenes.Scene)World.GetScene(SceneID);
                }
            }

            public static string DirectorID = "SessionSeven.Cutscenes.Director";
            public static global::SessionSeven.Cutscenes.Director Director
            {
                get
                {
                    return (global::SessionSeven.Cutscenes.Director)World.GetGameObject(DirectorID);
                }
            }
        }

        public static void Reset(STACK.World world)
        {
            World = world;
        }
    }
}

