  
REM ------------------------------------------------------------------------------
REM  <auto-generated>
REM      This code was generated by a tool on 05.07.2018 22:35:55.
REM 
REM      Changes to this file may cause incorrect behavior and will be lost if
REM      the code is regenerated.
REM  </auto-generated>
REM ------------------------------------------------------------------------------

copy "audio\basement.ogg" "bin\audio\basement.ogg"
copy "audio\intro.ogg" "bin\audio\intro.ogg"
copy "audio\session2.ogg" "bin\audio\session2.ogg"
copy "audio\session3.ogg" "bin\audio\session3.ogg"
copy "audio\session4.ogg" "bin\audio\session4.ogg"
copy "audio\session5.ogg" "bin\audio\session5.ogg"
copy "audio\session6.ogg" "bin\audio\session6.ogg"
copy "audio\spectres.ogg" "bin\audio\spectres.ogg"
ContentCompiler.exe audio\battery_insert.wav bin\audio\battery_insert WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\battery_remove.wav bin\audio\battery_remove WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\birds.wav bin\audio\birds WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\box_open.wav bin\audio\box_open WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\cabinet_close.wav bin\audio\cabinet_close WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\cabinet_open.wav bin\audio\cabinet_open WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\cardboard_open.wav bin\audio\cardboard_open WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\crowbar_break.wav bin\audio\crowbar_break WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\door_knob.wav bin\audio\door_knob WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\door_knock.wav bin\audio\door_knock WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\door_open.wav bin\audio\door_open WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drawer_close.wav bin\audio\drawer_close WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drawer_open.wav bin\audio\drawer_open WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drawer_unlock.wav bin\audio\drawer_unlock WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drill.wav bin\audio\drill WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drill_click.wav bin\audio\drill_click WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drone_failure.wav bin\audio\drone_failure WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drone_flying.wav bin\audio\drone_flying WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drone_landing.wav bin\audio\drone_landing WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\drone_shutdown.wav bin\audio\drone_shutdown WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\glass_shatter.wav bin\audio\glass_shatter WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\guitar_case_close.wav bin\audio\guitar_case_close WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\guitar_case_open.wav bin\audio\guitar_case_open WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\guitar_play1.wav bin\audio\guitar_play1 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\guitar_play2.wav bin\audio\guitar_play2 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\guitar_play3.wav bin\audio\guitar_play3 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\hammer_metal.wav bin\audio\hammer_metal WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\hammer_once.wav bin\audio\hammer_once WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\hammer_wood.wav bin\audio\hammer_wood WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\light_off.wav bin\audio\light_off WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\light_on.wav bin\audio\light_on WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\lock_pick.wav bin\audio\lock_pick WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\menu_click-backup1.wav bin\audio\menu_click-backup1 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\menu_click.wav bin\audio\menu_click WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\menu_focus-backup1.wav bin\audio\menu_focus-backup1 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\menu_focus.wav bin\audio\menu_focus WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\mouse_eat.wav bin\audio\mouse_eat WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\open_panel.wav bin\audio\open_panel WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\rustling1.wav bin\audio\rustling1 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\rustling2.wav bin\audio\rustling2 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\rustling3.wav bin\audio\rustling3 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\scissors_cut.wav bin\audio\scissors_cut WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\screwdriver_wood.wav bin\audio\screwdriver_wood WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\scribble_long.wav bin\audio\scribble_long WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\scribble_short.wav bin\audio\scribble_short WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_1.wav bin\audio\step_1 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_10.wav bin\audio\step_10 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_11.wav bin\audio\step_11 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_12.wav bin\audio\step_12 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_13.wav bin\audio\step_13 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_14.wav bin\audio\step_14 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_15.wav bin\audio\step_15 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_16.wav bin\audio\step_16 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_2.wav bin\audio\step_2 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_3.wav bin\audio\step_3 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_4.wav bin\audio\step_4 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_5.wav bin\audio\step_5 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_6.wav bin\audio\step_6 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_7.wav bin\audio\step_7 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_8.wav bin\audio\step_8 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\step_9.wav bin\audio\step_9 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\strings_drop.wav bin\audio\strings_drop WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\title.wav bin\audio\title WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\transition_1.wav bin\audio\transition_1 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\transition_2.wav bin\audio\transition_2 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\transition_3.wav bin\audio\transition_3 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\transition_4.wav bin\audio\transition_4 WavImporter SoundEffectProcessor true
ContentCompiler.exe audio\whining.wav bin\audio\whining WavImporter SoundEffectProcessor true
copy "rooms\basement\path.stp" "bin\rooms\basement\path.stp"
copy "rooms\jailcell\path.stp" "bin\rooms\jailcell\path.stp"
copy "rooms\paddedcell\path.stp" "bin\rooms\paddedcell\path.stp"
copy "rooms\sunset\path.stp" "bin\rooms\sunset\path.stp"
ContentCompiler.exe characters\mouse\sprite.png bin\characters\mouse\sprite TextureImporter TextureProcessor true
ContentCompiler.exe characters\ryan\sprite.png bin\characters\ryan\sprite TextureImporter TextureProcessor true
ContentCompiler.exe characters\ryan\sprite_blood.png bin\characters\ryan\sprite_blood TextureImporter TextureProcessor true
ContentCompiler.exe inventory\animalskeleton.png bin\inventory\animalskeleton TextureImporter TextureProcessor true
ContentCompiler.exe inventory\bandages.png bin\inventory\bandages TextureImporter TextureProcessor true
ContentCompiler.exe inventory\bandages_cut.png bin\inventory\bandages_cut TextureImporter TextureProcessor true
ContentCompiler.exe inventory\bandages_strip.png bin\inventory\bandages_strip TextureImporter TextureProcessor true
ContentCompiler.exe inventory\baton.png bin\inventory\baton TextureImporter TextureProcessor true
ContentCompiler.exe inventory\baton_expanded.png bin\inventory\baton_expanded TextureImporter TextureProcessor true
ContentCompiler.exe inventory\baton_string.png bin\inventory\baton_string TextureImporter TextureProcessor true
ContentCompiler.exe inventory\battery_a.png bin\inventory\battery_a TextureImporter TextureProcessor true
ContentCompiler.exe inventory\battery_b.png bin\inventory\battery_b TextureImporter TextureProcessor true
ContentCompiler.exe inventory\blanket.png bin\inventory\blanket TextureImporter TextureProcessor true
ContentCompiler.exe inventory\cardboard.png bin\inventory\cardboard TextureImporter TextureProcessor true
ContentCompiler.exe inventory\crowbar.png bin\inventory\crowbar TextureImporter TextureProcessor true
ContentCompiler.exe inventory\crowbar_broken.png bin\inventory\crowbar_broken TextureImporter TextureProcessor true
ContentCompiler.exe inventory\drawerkey.png bin\inventory\drawerkey TextureImporter TextureProcessor true
ContentCompiler.exe inventory\drone.png bin\inventory\drone TextureImporter TextureProcessor true
ContentCompiler.exe inventory\dronepackage.png bin\inventory\dronepackage TextureImporter TextureProcessor true
ContentCompiler.exe inventory\drugprescriptionryan.png bin\inventory\drugprescriptionryan TextureImporter TextureProcessor true
ContentCompiler.exe inventory\envelope.png bin\inventory\envelope TextureImporter TextureProcessor true
ContentCompiler.exe inventory\flashlight.png bin\inventory\flashlight TextureImporter TextureProcessor true
ContentCompiler.exe inventory\hammer.png bin\inventory\hammer TextureImporter TextureProcessor true
ContentCompiler.exe inventory\hazelnuts.png bin\inventory\hazelnuts TextureImporter TextureProcessor true
ContentCompiler.exe inventory\letter_big.png bin\inventory\letter_big TextureImporter TextureProcessor true
ContentCompiler.exe inventory\paperclip.png bin\inventory\paperclip TextureImporter TextureProcessor true
ContentCompiler.exe inventory\paperclips.png bin\inventory\paperclips TextureImporter TextureProcessor true
ContentCompiler.exe inventory\pills.png bin\inventory\pills TextureImporter TextureProcessor true
ContentCompiler.exe inventory\portrait.png bin\inventory\portrait TextureImporter TextureProcessor true
ContentCompiler.exe inventory\remotecontrol.png bin\inventory\remotecontrol TextureImporter TextureProcessor true
ContentCompiler.exe inventory\rfidantenna.png bin\inventory\rfidantenna TextureImporter TextureProcessor true
ContentCompiler.exe inventory\rfidbook.png bin\inventory\rfidbook TextureImporter TextureProcessor true
ContentCompiler.exe inventory\sawkit.png bin\inventory\sawkit TextureImporter TextureProcessor true
ContentCompiler.exe inventory\scissors.png bin\inventory\scissors TextureImporter TextureProcessor true
ContentCompiler.exe inventory\screwdriver.png bin\inventory\screwdriver TextureImporter TextureProcessor true
ContentCompiler.exe inventory\strings.png bin\inventory\strings TextureImporter TextureProcessor true
ContentCompiler.exe inventory\therapylog.png bin\inventory\therapylog TextureImporter TextureProcessor true
ContentCompiler.exe inventory\woodenbox.png bin\inventory\woodenbox TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\bench.png bin\rooms\basement\bench TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\blanketflashlight.png bin\rooms\basement\blanketflashlight TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\blooddrops.png bin\rooms\basement\blooddrops TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\cabinetleft.png bin\rooms\basement\cabinetleft TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\cabinetlock.png bin\rooms\basement\cabinetlock TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\cabinetright.png bin\rooms\basement\cabinetright TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\cable.png bin\rooms\basement\cable TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\cabletop.png bin\rooms\basement\cabletop TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\crowbar.png bin\rooms\basement\crowbar TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\desk.png bin\rooms\basement\desk TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\door.png bin\rooms\basement\door TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\drawerleft.png bin\rooms\basement\drawerleft TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\drawerright.png bin\rooms\basement\drawerright TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\drillholesaw.png bin\rooms\basement\drillholesaw TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\drillused.png bin\rooms\basement\drillused TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\drone.png bin\rooms\basement\drone TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\eyes.png bin\rooms\basement\eyes TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\familyportraitshattered.png bin\rooms\basement\familyportraitshattered TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\foreground.png bin\rooms\basement\foreground TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\guitar.png bin\rooms\basement\guitar TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\guitarcaseopen.png bin\rooms\basement\guitarcaseopen TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\guitarstringsfloor.png bin\rooms\basement\guitarstringsfloor TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\hammer.png bin\rooms\basement\hammer TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\hazelnuts.png bin\rooms\basement\hazelnuts TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\image.png bin\rooms\basement\image TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\lightsoff.png bin\rooms\basement\lightsoff TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\medicalcabinet.png bin\rooms\basement\medicalcabinet TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\modemlight.png bin\rooms\basement\modemlight TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\nut.png bin\rooms\basement\nut TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\receipt_anim.png bin\rooms\basement\receipt_anim TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\rfidantenna.png bin\rooms\basement\rfidantenna TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\rfidantennacabinet.png bin\rooms\basement\rfidantennacabinet TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\rfidantennashelf.png bin\rooms\basement\rfidantennashelf TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\rfidbook.png bin\rooms\basement\rfidbook TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\ryanlying.png bin\rooms\basement\ryanlying TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\sawkit.png bin\rooms\basement\sawkit TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\scene.png bin\rooms\basement\scene TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\scene_transparent_floor.png bin\rooms\basement\scene_transparent_floor TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\screwdriver.png bin\rooms\basement\screwdriver TextureImporter TextureProcessor true
ContentCompiler.exe rooms\basement\woodenpanel.png bin\rooms\basement\woodenpanel TextureImporter TextureProcessor true
ContentCompiler.exe rooms\jailcell\foreground.png bin\rooms\jailcell\foreground TextureImporter TextureProcessor true
ContentCompiler.exe rooms\jailcell\scene.png bin\rooms\jailcell\scene TextureImporter TextureProcessor true
ContentCompiler.exe rooms\letter\scene.png bin\rooms\letter\scene TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\ryan.png bin\rooms\office\ryan TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\ryaneyes.png bin\rooms\office\ryaneyes TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\scene.png bin\rooms\office\scene TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\scenenight.png bin\rooms\office\scenenight TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\table.png bin\rooms\office\table TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\therapist.png bin\rooms\office\therapist TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\0.png bin\rooms\office\anim\day\0 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\1.png bin\rooms\office\anim\day\1 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\10.png bin\rooms\office\anim\day\10 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\11.png bin\rooms\office\anim\day\11 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\12.png bin\rooms\office\anim\day\12 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\13.png bin\rooms\office\anim\day\13 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\14.png bin\rooms\office\anim\day\14 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\15.png bin\rooms\office\anim\day\15 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\16.png bin\rooms\office\anim\day\16 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\17.png bin\rooms\office\anim\day\17 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\18.png bin\rooms\office\anim\day\18 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\19.png bin\rooms\office\anim\day\19 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\2.png bin\rooms\office\anim\day\2 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\3.png bin\rooms\office\anim\day\3 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\4.png bin\rooms\office\anim\day\4 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\5.png bin\rooms\office\anim\day\5 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\6.png bin\rooms\office\anim\day\6 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\7.png bin\rooms\office\anim\day\7 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\8.png bin\rooms\office\anim\day\8 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\day\9.png bin\rooms\office\anim\day\9 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\0.png bin\rooms\office\anim\night\0 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\1.png bin\rooms\office\anim\night\1 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\10.png bin\rooms\office\anim\night\10 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\11.png bin\rooms\office\anim\night\11 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\12.png bin\rooms\office\anim\night\12 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\13.png bin\rooms\office\anim\night\13 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\14.png bin\rooms\office\anim\night\14 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\15.png bin\rooms\office\anim\night\15 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\16.png bin\rooms\office\anim\night\16 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\17.png bin\rooms\office\anim\night\17 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\18.png bin\rooms\office\anim\night\18 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\19.png bin\rooms\office\anim\night\19 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\2.png bin\rooms\office\anim\night\2 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\3.png bin\rooms\office\anim\night\3 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\4.png bin\rooms\office\anim\night\4 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\5.png bin\rooms\office\anim\night\5 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\6.png bin\rooms\office\anim\night\6 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\7.png bin\rooms\office\anim\night\7 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\8.png bin\rooms\office\anim\night\8 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\office\anim\night\9.png bin\rooms\office\anim\night\9 TextureImporter TextureProcessor true
ContentCompiler.exe rooms\paddedcell\scene.png bin\rooms\paddedcell\scene TextureImporter TextureProcessor true
ContentCompiler.exe rooms\sunset\scene.png bin\rooms\sunset\scene TextureImporter TextureProcessor true
ContentCompiler.exe rooms\title\scene.png bin\rooms\title\scene TextureImporter TextureProcessor true
ContentCompiler.exe ui\cursor.png bin\ui\cursor TextureImporter TextureProcessor true
ContentCompiler.exe ui\shadow.png bin\ui\shadow TextureImporter TextureProcessor true
ContentCompiler.exe ui\verbs.png bin\ui\verbs TextureImporter TextureProcessor true
ContentCompiler.exe ui\verbshighlight.png bin\ui\verbshighlight TextureImporter TextureProcessor true
ContentCompiler.exe ui\verbshighlight_ger.png bin\ui\verbshighlight_ger TextureImporter TextureProcessor true
ContentCompiler.exe ui\verbs_ger.png bin\ui\verbs_ger TextureImporter TextureProcessor true
ContentCompiler.exe fonts\pixeloperator_BMF.png bin\fonts\pixeloperator_BMF TextureImporter FontTextureProcessor true
ContentCompiler.exe fonts\pixeloperator_outline_BMF.png bin\fonts\pixeloperator_outline_BMF TextureImporter FontTextureProcessor true
