  
// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool on 06.07.2018 23:00:28.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SessionSeven
{
    public static partial class content
    {
        public static partial class audio
        {
            public const string _path_ = "audio\\";
            public const string basement = "audio\\basement";
            public const string intro = "audio\\intro";
            public const string session2 = "audio\\session2";
            public const string session3 = "audio\\session3";
            public const string session4 = "audio\\session4";
            public const string session5 = "audio\\session5";
            public const string session6 = "audio\\session6";
            public const string spectres = "audio\\spectres";
            public const string battery_insert = "audio\\battery_insert";
            public const string battery_remove = "audio\\battery_remove";
            public const string birds = "audio\\birds";
            public const string box_open = "audio\\box_open";
            public const string cabinet_close = "audio\\cabinet_close";
            public const string cabinet_open = "audio\\cabinet_open";
            public const string cardboard_open = "audio\\cardboard_open";
            public const string crowbar_break = "audio\\crowbar_break";
            public const string door_knob = "audio\\door_knob";
            public const string door_knock = "audio\\door_knock";
            public const string door_open = "audio\\door_open";
            public const string drawer_close = "audio\\drawer_close";
            public const string drawer_open = "audio\\drawer_open";
            public const string drawer_unlock = "audio\\drawer_unlock";
            public const string drill = "audio\\drill";
            public const string drill_click = "audio\\drill_click";
            public const string drone_failure = "audio\\drone_failure";
            public const string drone_flying = "audio\\drone_flying";
            public const string drone_landing = "audio\\drone_landing";
            public const string drone_shutdown = "audio\\drone_shutdown";
            public const string glass_shatter = "audio\\glass_shatter";
            public const string guitar_case_close = "audio\\guitar_case_close";
            public const string guitar_case_open = "audio\\guitar_case_open";
            public const string guitar_play1 = "audio\\guitar_play1";
            public const string guitar_play2 = "audio\\guitar_play2";
            public const string guitar_play3 = "audio\\guitar_play3";
            public const string hammer_metal = "audio\\hammer_metal";
            public const string hammer_once = "audio\\hammer_once";
            public const string hammer_wood = "audio\\hammer_wood";
            public const string light_off = "audio\\light_off";
            public const string light_on = "audio\\light_on";
            public const string lock_pick = "audio\\lock_pick";
            public const string menu_click = "audio\\menu_click";
            public const string menu_focus = "audio\\menu_focus";
            public const string mouse_eat = "audio\\mouse_eat";
            public const string open_panel = "audio\\open_panel";
            public const string rustling1 = "audio\\rustling1";
            public const string rustling2 = "audio\\rustling2";
            public const string rustling3 = "audio\\rustling3";
            public const string scissors_cut = "audio\\scissors_cut";
            public const string screwdriver_wood = "audio\\screwdriver_wood";
            public const string scribble_long = "audio\\scribble_long";
            public const string scribble_short = "audio\\scribble_short";
            public const string step_1 = "audio\\step_1";
            public const string step_10 = "audio\\step_10";
            public const string step_11 = "audio\\step_11";
            public const string step_12 = "audio\\step_12";
            public const string step_13 = "audio\\step_13";
            public const string step_14 = "audio\\step_14";
            public const string step_15 = "audio\\step_15";
            public const string step_16 = "audio\\step_16";
            public const string step_2 = "audio\\step_2";
            public const string step_3 = "audio\\step_3";
            public const string step_4 = "audio\\step_4";
            public const string step_5 = "audio\\step_5";
            public const string step_6 = "audio\\step_6";
            public const string step_7 = "audio\\step_7";
            public const string step_8 = "audio\\step_8";
            public const string step_9 = "audio\\step_9";
            public const string step_soft_1 = "audio\\step_soft_1";
            public const string step_soft_2 = "audio\\step_soft_2";
            public const string step_soft_3 = "audio\\step_soft_3";
            public const string step_soft_4 = "audio\\step_soft_4";
            public const string step_soft_5 = "audio\\step_soft_5";
            public const string step_soft_6 = "audio\\step_soft_6";
            public const string step_soft_7 = "audio\\step_soft_7";
            public const string strings_drop = "audio\\strings_drop";
            public const string title = "audio\\title";
            public const string transition_1 = "audio\\transition_1";
            public const string transition_2 = "audio\\transition_2";
            public const string transition_3 = "audio\\transition_3";
            public const string transition_4 = "audio\\transition_4";
            public const string whining = "audio\\whining";
        }

        public static partial class characters
        {
            public const string _path_ = "characters\\";
            public static partial class mouse
            {
                public const string _path_ = "characters\\mouse\\";
                public const string sprite = "characters\\mouse\\sprite";
            }

            public static partial class ryan
            {
                public const string _path_ = "characters\\ryan\\";
                public const string sprite = "characters\\ryan\\sprite";
                public const string sprite_blood = "characters\\ryan\\sprite_blood";
            }
        }

        public static partial class fonts
        {
            public const string _path_ = "fonts\\";
            public const string pixeloperator_BMF = "fonts\\pixeloperator_BMF";
            public const string pixeloperator_outline_BMF = "fonts\\pixeloperator_outline_BMF";
        }

        public static partial class inventory
        {
            public const string _path_ = "inventory\\";
            public const string animalskeleton = "inventory\\animalskeleton";
            public const string bandages = "inventory\\bandages";
            public const string bandages_cut = "inventory\\bandages_cut";
            public const string bandages_strip = "inventory\\bandages_strip";
            public const string baton = "inventory\\baton";
            public const string baton_expanded = "inventory\\baton_expanded";
            public const string baton_string = "inventory\\baton_string";
            public const string battery_a = "inventory\\battery_a";
            public const string battery_b = "inventory\\battery_b";
            public const string blanket = "inventory\\blanket";
            public const string cardboard = "inventory\\cardboard";
            public const string crowbar = "inventory\\crowbar";
            public const string crowbar_broken = "inventory\\crowbar_broken";
            public const string drawerkey = "inventory\\drawerkey";
            public const string drone = "inventory\\drone";
            public const string dronepackage = "inventory\\dronepackage";
            public const string drugprescriptionryan = "inventory\\drugprescriptionryan";
            public const string envelope = "inventory\\envelope";
            public const string flashlight = "inventory\\flashlight";
            public const string hammer = "inventory\\hammer";
            public const string hazelnuts = "inventory\\hazelnuts";
            public const string letter_big = "inventory\\letter_big";
            public const string paperclip = "inventory\\paperclip";
            public const string paperclips = "inventory\\paperclips";
            public const string pills = "inventory\\pills";
            public const string portrait = "inventory\\portrait";
            public const string remotecontrol = "inventory\\remotecontrol";
            public const string rfidantenna = "inventory\\rfidantenna";
            public const string rfidbook = "inventory\\rfidbook";
            public const string sawkit = "inventory\\sawkit";
            public const string scissors = "inventory\\scissors";
            public const string screwdriver = "inventory\\screwdriver";
            public const string strings = "inventory\\strings";
            public const string therapylog = "inventory\\therapylog";
            public const string woodenbox = "inventory\\woodenbox";
        }

        public static partial class rooms
        {
            public const string _path_ = "rooms\\";
            public static partial class basement
            {
                public const string _path_ = "rooms\\basement\\";
                public const string path = "rooms\\basement\\path";
                public const string bench = "rooms\\basement\\bench";
                public const string blanketflashlight = "rooms\\basement\\blanketflashlight";
                public const string blooddrops = "rooms\\basement\\blooddrops";
                public const string cabinetleft = "rooms\\basement\\cabinetleft";
                public const string cabinetlock = "rooms\\basement\\cabinetlock";
                public const string cabinetright = "rooms\\basement\\cabinetright";
                public const string cable = "rooms\\basement\\cable";
                public const string cabletop = "rooms\\basement\\cabletop";
                public const string crowbar = "rooms\\basement\\crowbar";
                public const string desk = "rooms\\basement\\desk";
                public const string door = "rooms\\basement\\door";
                public const string drawerleft = "rooms\\basement\\drawerleft";
                public const string drawerright = "rooms\\basement\\drawerright";
                public const string drillholesaw = "rooms\\basement\\drillholesaw";
                public const string drillused = "rooms\\basement\\drillused";
                public const string drone = "rooms\\basement\\drone";
                public const string eyes = "rooms\\basement\\eyes";
                public const string familyportraitshattered = "rooms\\basement\\familyportraitshattered";
                public const string foreground = "rooms\\basement\\foreground";
                public const string guitar = "rooms\\basement\\guitar";
                public const string guitarcaseopen = "rooms\\basement\\guitarcaseopen";
                public const string guitarstringsfloor = "rooms\\basement\\guitarstringsfloor";
                public const string hammer = "rooms\\basement\\hammer";
                public const string hazelnuts = "rooms\\basement\\hazelnuts";
                public const string image = "rooms\\basement\\image";
                public const string lightsoff = "rooms\\basement\\lightsoff";
                public const string medicalcabinet = "rooms\\basement\\medicalcabinet";
                public const string modemlight = "rooms\\basement\\modemlight";
                public const string nut = "rooms\\basement\\nut";
                public const string receipt_anim = "rooms\\basement\\receipt_anim";
                public const string rfidantenna = "rooms\\basement\\rfidantenna";
                public const string rfidantennacabinet = "rooms\\basement\\rfidantennacabinet";
                public const string rfidantennashelf = "rooms\\basement\\rfidantennashelf";
                public const string rfidbook = "rooms\\basement\\rfidbook";
                public const string ryanlying = "rooms\\basement\\ryanlying";
                public const string sawkit = "rooms\\basement\\sawkit";
                public const string scene = "rooms\\basement\\scene";
                public const string scene_transparent_floor = "rooms\\basement\\scene_transparent_floor";
                public const string screwdriver = "rooms\\basement\\screwdriver";
                public const string woodenpanel = "rooms\\basement\\woodenpanel";
            }

            public static partial class jailcell
            {
                public const string _path_ = "rooms\\jailcell\\";
                public const string path = "rooms\\jailcell\\path";
                public const string foreground = "rooms\\jailcell\\foreground";
                public const string scene = "rooms\\jailcell\\scene";
            }

            public static partial class letter
            {
                public const string _path_ = "rooms\\letter\\";
                public const string scene = "rooms\\letter\\scene";
            }

            public static partial class office
            {
                public const string _path_ = "rooms\\office\\";
                public const string ryan = "rooms\\office\\ryan";
                public const string ryaneyes = "rooms\\office\\ryaneyes";
                public const string scene = "rooms\\office\\scene";
                public const string scenenight = "rooms\\office\\scenenight";
                public const string table = "rooms\\office\\table";
                public const string therapist = "rooms\\office\\therapist";

                public static partial class anim
                {
                    public const string _path_ = "rooms\\office\\anim\\";
                    public static partial class day
                    {
                        public const string _path_ = "rooms\\office\\anim\\day\\";
                        public const string _0 = "rooms\\office\\anim\\day\\0";
                        public const string _1 = "rooms\\office\\anim\\day\\1";
                        public const string _10 = "rooms\\office\\anim\\day\\10";
                        public const string _11 = "rooms\\office\\anim\\day\\11";
                        public const string _12 = "rooms\\office\\anim\\day\\12";
                        public const string _13 = "rooms\\office\\anim\\day\\13";
                        public const string _14 = "rooms\\office\\anim\\day\\14";
                        public const string _15 = "rooms\\office\\anim\\day\\15";
                        public const string _16 = "rooms\\office\\anim\\day\\16";
                        public const string _17 = "rooms\\office\\anim\\day\\17";
                        public const string _18 = "rooms\\office\\anim\\day\\18";
                        public const string _19 = "rooms\\office\\anim\\day\\19";
                        public const string _2 = "rooms\\office\\anim\\day\\2";
                        public const string _3 = "rooms\\office\\anim\\day\\3";
                        public const string _4 = "rooms\\office\\anim\\day\\4";
                        public const string _5 = "rooms\\office\\anim\\day\\5";
                        public const string _6 = "rooms\\office\\anim\\day\\6";
                        public const string _7 = "rooms\\office\\anim\\day\\7";
                        public const string _8 = "rooms\\office\\anim\\day\\8";
                        public const string _9 = "rooms\\office\\anim\\day\\9";
                    }

                    public static partial class night
                    {
                        public const string _path_ = "rooms\\office\\anim\\night\\";
                        public const string _0 = "rooms\\office\\anim\\night\\0";
                        public const string _1 = "rooms\\office\\anim\\night\\1";
                        public const string _10 = "rooms\\office\\anim\\night\\10";
                        public const string _11 = "rooms\\office\\anim\\night\\11";
                        public const string _12 = "rooms\\office\\anim\\night\\12";
                        public const string _13 = "rooms\\office\\anim\\night\\13";
                        public const string _14 = "rooms\\office\\anim\\night\\14";
                        public const string _15 = "rooms\\office\\anim\\night\\15";
                        public const string _16 = "rooms\\office\\anim\\night\\16";
                        public const string _17 = "rooms\\office\\anim\\night\\17";
                        public const string _18 = "rooms\\office\\anim\\night\\18";
                        public const string _19 = "rooms\\office\\anim\\night\\19";
                        public const string _2 = "rooms\\office\\anim\\night\\2";
                        public const string _3 = "rooms\\office\\anim\\night\\3";
                        public const string _4 = "rooms\\office\\anim\\night\\4";
                        public const string _5 = "rooms\\office\\anim\\night\\5";
                        public const string _6 = "rooms\\office\\anim\\night\\6";
                        public const string _7 = "rooms\\office\\anim\\night\\7";
                        public const string _8 = "rooms\\office\\anim\\night\\8";
                        public const string _9 = "rooms\\office\\anim\\night\\9";
                    }
                }
            }

            public static partial class paddedcell
            {
                public const string _path_ = "rooms\\paddedcell\\";
                public const string path = "rooms\\paddedcell\\path";
                public const string scene = "rooms\\paddedcell\\scene";
            }

            public static partial class sunset
            {
                public const string _path_ = "rooms\\sunset\\";
                public const string path = "rooms\\sunset\\path";
                public const string scene = "rooms\\sunset\\scene";
            }

            public static partial class title
            {
                public const string _path_ = "rooms\\title\\";
                public const string scene = "rooms\\title\\scene";
            }
        }

        public static partial class ui
        {
            public const string _path_ = "ui\\";
            public const string cursor = "ui\\cursor";
            public const string shadow = "ui\\shadow";
            public const string verbs = "ui\\verbs";
            public const string verbshighlight = "ui\\verbshighlight";
            public const string verbshighlight_ger = "ui\\verbshighlight_ger";
            public const string verbs_ger = "ui\\verbs_ger";
        }
    }
}
