//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Items.Resources", typeof(Items_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » No line of sight is required between the antenna and the tag. Directional antennas allow for a greater coverage distance. «.
        /// </summary>
        internal static string _No_line_of_sight_is_required_between_the_antenna_and_the_tag_Directional_antennas_allow_for_a_greater_coverage_distance_ {
            get {
                return ResourceManager.GetString("_No_line_of_sight_is_required_between_the_antenna_and_the_tag_Directional_antenna" +
                        "s_allow_for_a_greater_coverage_distance_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Radio Frequency Identification allows to identify objects using data transmitted via radio waves. «.
        /// </summary>
        internal static string _Radio_Frequency_Identification_allows_to_identify_objects_using_data_transmitted_via_radio_waves_ {
            get {
                return ResourceManager.GetString("_Radio_Frequency_Identification_allows_to_identify_objects_using_data_transmitted" +
                        "_via_radio_waves_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » RFID antennas send the RF energy to those objects called RFID tags and receive the tags&apos; reply. «.
        /// </summary>
        internal static string _RFID_antennas_send_the_RF_energy_to_those_objects_called_RFID_tags_and_receive_the_tags_reply_ {
            get {
                return ResourceManager.GetString("_RFID_antennas_send_the_RF_energy_to_those_objects_called_RFID_tags_and_receive_t" +
                        "he_tags_reply_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Using two directional RFID antennas, the actual position of a RFID tag can be triangulated. «.
        /// </summary>
        internal static string _Using_two_directional_RFID_antennas_the_actual_position_of_a_RFID_tag_can_be_triangulated_ {
            get {
                return ResourceManager.GetString("_Using_two_directional_RFID_antennas_the_actual_position_of_a_RFID_tag_can_be_tri" +
                        "angulated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bag of hazelnuts..
        /// </summary>
        internal static string A_bag_of_hazelnuts {
            get {
                return ResourceManager.GetString("A_bag_of_hazelnuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A battery..
        /// </summary>
        internal static string A_battery {
            get {
                return ResourceManager.GetString("A_battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cardboard box without any inscription..
        /// </summary>
        internal static string A_cardboard_without_any_inscription {
            get {
                return ResourceManager.GetString("A_cardboard_without_any_inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cloth bandage. I should use this to dress my wound..
        /// </summary>
        internal static string A_cloth_bandage_I_should_use_this_to_dress_my_wound {
            get {
                return ResourceManager.GetString("A_cloth_bandage_I_should_use_this_to_dress_my_wound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cloth bandage roll. This is exactly what I need right now..
        /// </summary>
        internal static string A_cloth_bandage_roll_This_is_exactly_what_I_need_right_now {
            get {
                return ResourceManager.GetString("A_cloth_bandage_roll_This_is_exactly_what_I_need_right_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cloth strip bandage..
        /// </summary>
        internal static string A_cloth_strip_bandage {
            get {
                return ResourceManager.GetString("A_cloth_strip_bandage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular flashlight..
        /// </summary>
        internal static string A_regular_flashlight {
            get {
                return ResourceManager.GetString("A_regular_flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A RFID tag is glued to the bottom..
        /// </summary>
        internal static string A_RFID_tag_is_glued_to_the_bottom {
            get {
                return ResourceManager.GetString("A_RFID_tag_is_glued_to_the_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh god, it&apos;s some kind of animal skeleton. It&apos;s all rotten!.
        /// </summary>
        internal static string A_rotten_animal_skeleton {
            get {
                return ResourceManager.GetString("A_rotten_animal_skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small box with paper clips..
        /// </summary>
        internal static string A_small_box_with_paper_clips {
            get {
                return ResourceManager.GetString("A_small_box_with_paper_clips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the date this therapy session happened some months ago..
        /// </summary>
        internal static string According_to_the_date_this_therapy_session_happened_some_months_ago {
            get {
                return ResourceManager.GetString("According_to_the_date_this_therapy_session_happened_some_months_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost like a net..
        /// </summary>
        internal static string Almost_like_a_net {
            get {
                return ResourceManager.GetString("Almost_like_a_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expandable baton..
        /// </summary>
        internal static string An_expandable_baton {
            get {
                return ResourceManager.GetString("An_expandable_baton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expanded baton. There is a small ring on the top..
        /// </summary>
        internal static string An_expanded_baton_There_is_a_small_ring_on_the_top {
            get {
                return ResourceManager.GetString("An_expanded_baton_There_is_a_small_ring_on_the_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And an expendable baton?.
        /// </summary>
        internal static string And_an_expendable_baton {
            get {
                return ResourceManager.GetString("And_an_expendable_baton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animal skeleton.
        /// </summary>
        internal static string AnimalSkeleton_AnimalSkeleton_AnimalSkeleton {
            get {
                return ResourceManager.GetString("AnimalSkeleton_AnimalSkeleton_AnimalSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another long-range RFID antenna..
        /// </summary>
        internal static string Another_longrange_RFID_antenna {
            get {
                return ResourceManager.GetString("Another_longrange_RFID_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aw man, we hardly ever used this thing..
        /// </summary>
        internal static string Aw_man_we_hardly_ever_used_this_thing {
            get {
                return ResourceManager.GetString("Aw_man_we_hardly_ever_used_this_thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloth bandage roll.
        /// </summary>
        internal static string Bandages_Bandages_ClothBandageRoll {
            get {
                return ResourceManager.GetString("Bandages_Bandages_ClothBandageRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloth bandage.
        /// </summary>
        internal static string BandageStrip_BandageStrip_ClothBandage {
            get {
                return ResourceManager.GetString("BandageStrip_BandageStrip_ClothBandage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expandable baton.
        /// </summary>
        internal static string Baton_Baton_ExpandableBaton {
            get {
                return ResourceManager.GetString("Baton_Baton_ExpandableBaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baton with string.
        /// </summary>
        internal static string BatonWithString_BatonWithString_BatonWithString {
            get {
                return ResourceManager.GetString("BatonWithString_BatonWithString_BatonWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to battery.
        /// </summary>
        internal static string BatteryA_BatteryA_Battery {
            get {
                return ResourceManager.GetString("BatteryA_BatteryA_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picnic blanket.
        /// </summary>
        internal static string Blanket_Blanket_PicnicBlanket {
            get {
                return ResourceManager.GetString("Blanket_Blanket_PicnicBlanket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t expand it any further.
        /// </summary>
        internal static string Cant_expand_it_any_further {
            get {
                return ResourceManager.GetString("Cant_expand_it_any_further", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reduce it any further.
        /// </summary>
        internal static string Cant_reduce_it_any_further {
            get {
                return ResourceManager.GetString("Cant_reduce_it_any_further", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reduce it with the string tied to it..
        /// </summary>
        internal static string Cant_reduce_it_with_the_string_tied_to_it {
            get {
                return ResourceManager.GetString("Cant_reduce_it_with_the_string_tied_to_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use the key with that..
        /// </summary>
        internal static string Cant_use_the_key_with_that {
            get {
                return ResourceManager.GetString("Cant_use_the_key_with_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use the whole thing..
        /// </summary>
        internal static string Cant_use_the_whole_thing {
            get {
                return ResourceManager.GetString("Cant_use_the_whole_thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crowbar.
        /// </summary>
        internal static string Crowbar_Crowbar_Crowbar {
            get {
                return ResourceManager.GetString("Crowbar_Crowbar_Crowbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broken crowbar.
        /// </summary>
        internal static string CrowbarBroken_CrowbarBroken_BrokenCrowbar {
            get {
                return ResourceManager.GetString("CrowbarBroken_CrowbarBroken_BrokenCrowbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cynthia and me spent much time on that together, especially before Landon was born..
        /// </summary>
        internal static string Cynthia_and_me_spent_much_time_on_that_together_especially_before_Landon_was_born {
            get {
                return ResourceManager.GetString("Cynthia_and_me_spent_much_time_on_that_together_especially_before_Landon_was_born" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cynthia is always eating these when she&apos;s up late crafting or working on the house..
        /// </summary>
        internal static string Cynthia_is_always_eating_these_when_shes_up_late_crafting_or_working_on_the_house {
            get {
                return ResourceManager.GetString("Cynthia_is_always_eating_these_when_shes_up_late_crafting_or_working_on_the_house" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small key.
        /// </summary>
        internal static string DrawerKey_DrawerKey_SmallKey {
            get {
                return ResourceManager.GetString("DrawerKey_DrawerKey_SmallKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drone.
        /// </summary>
        internal static string Drone_Drone_Drone {
            get {
                return ResourceManager.GetString("Drone_Drone_Drone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drone package.
        /// </summary>
        internal static string DronePackage_DronePackage_DronePackage {
            get {
                return ResourceManager.GetString("DronePackage_DronePackage_DronePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drug prescription.
        /// </summary>
        internal static string DrugPrescriptionRyan_DrugPrescriptionRyan_DrugPrescription {
            get {
                return ResourceManager.GetString("DrugPrescriptionRyan_DrugPrescriptionRyan_DrugPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to envelope.
        /// </summary>
        internal static string Envelope_Envelope_Envelope {
            get {
                return ResourceManager.GetString("Envelope_Envelope_Envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eww..
        /// </summary>
        internal static string Eww {
            get {
                return ResourceManager.GetString("Eww", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flashlight.
        /// </summary>
        internal static string Flashlight_Flashlight_Flashlight {
            get {
                return ResourceManager.GetString("Flashlight_Flashlight_Flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward..
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good memories..
        /// </summary>
        internal static string Good_memories {
            get {
                return ResourceManager.GetString("Good_memories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it..
        /// </summary>
        internal static string Got_it {
            get {
                return ResourceManager.GetString("Got_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strings.
        /// </summary>
        internal static string GuitarStrings_GuitarStrings_Strings {
            get {
                return ResourceManager.GetString("GuitarStrings_GuitarStrings_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hammer.
        /// </summary>
        internal static string Hammer_Hammer_Hammer {
            get {
                return ResourceManager.GetString("Hammer_Hammer_Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hazelnuts.
        /// </summary>
        internal static string Hazelnuts_Hazelnuts_Hazelnuts {
            get {
                return ResourceManager.GetString("Hazelnuts_Hazelnuts_Hazelnuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He looks happy..
        /// </summary>
        internal static string He_looks_happy {
            get {
                return ResourceManager.GetString("He_looks_happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELLO! IS SOMEBODY THERE?.
        /// </summary>
        internal static string HELLO_IS_SOMEBODY_THERE {
            get {
                return ResourceManager.GetString("HELLO_IS_SOMEBODY_THERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a summary in the book describing RFID antennas..
        /// </summary>
        internal static string Here_is_a_summary_in_the_book_describing_RFID_antennas {
            get {
                return ResourceManager.GetString("Here_is_a_summary_in_the_book_describing_RFID_antennas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! There&apos;s a small key glued to the back of this!.
        /// </summary>
        internal static string Hey_Theres_a_small_key_glued_to_the_back_of_this {
            get {
                return ResourceManager.GetString("Hey_Theres_a_small_key_glued_to_the_back_of_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t put force on that while it&apos;s in my hands. .
        /// </summary>
        internal static string Holding_that_in_my_hands_I_cant_apply_force_on_that {
            get {
                return ResourceManager.GetString("Holding_that_in_my_hands_I_cant_apply_force_on_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t believe what just happened....
        /// </summary>
        internal static string I_cant_believe_what_just_happened {
            get {
                return ResourceManager.GetString("I_cant_believe_what_just_happened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cut off a part of it already..
        /// </summary>
        internal static string I_cut_off_a_part_of_it_already {
            get {
                return ResourceManager.GetString("I_cut_off_a_part_of_it_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t need to cut any more off of that..
        /// </summary>
        internal static string I_dont_need_to_cut_any_more_off_of_that {
            get {
                return ResourceManager.GetString("I_dont_need_to_cut_any_more_off_of_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t need to cut that off any further..
        /// </summary>
        internal static string I_dont_need_to_cut_that_off_any_further {
            get {
                return ResourceManager.GetString("I_dont_need_to_cut_that_off_any_further", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t see the point in making the drone fly to that..
        /// </summary>
        internal static string I_dont_see_the_point_in_making_the_drone_fly_to_that {
            get {
                return ResourceManager.GetString("I_dont_see_the_point_in_making_the_drone_fly_to_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t want to cut that..
        /// </summary>
        internal static string I_dont_want_to_cut_that {
            get {
                return ResourceManager.GetString("I_dont_want_to_cut_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I dont&apos;t have anything to knot the string to..
        /// </summary>
        internal static string I_dontt_have_anything_to_knot_the_string_to {
            get {
                return ResourceManager.GetString("I_dontt_have_anything_to_knot_the_string_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I dressed my wound already..
        /// </summary>
        internal static string I_dressed_my_wound_already {
            get {
                return ResourceManager.GetString("I_dressed_my_wound_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I knew he was having problems in his old school, but this....
        /// </summary>
        internal static string I_knew_he_was_having_problems_in_his_old_school_but_this {
            get {
                return ResourceManager.GetString("I_knew_he_was_having_problems_in_his_old_school_but_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need another antenna to triangulate the signal and get its position..
        /// </summary>
        internal static string I_need_another_antenna_to_triangulate_the_signal_and_get_its_position {
            get {
                return ResourceManager.GetString("I_need_another_antenna_to_triangulate_the_signal_and_get_its_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to place the other antenna with more distance for the triangulation to work..
        /// </summary>
        internal static string I_need_to_place_the_other_antenna_with_more_distance_for_the_triangulation_to_work {
            get {
                return ResourceManager.GetString("I_need_to_place_the_other_antenna_with_more_distance_for_the_triangulation_to_wor" +
                        "k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to put the drone somewhere first..
        /// </summary>
        internal static string I_need_to_put_the_drone_somewhere_first {
            get {
                return ResourceManager.GetString("I_need_to_put_the_drone_somewhere_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I better cut some part off..
        /// </summary>
        internal static string I_should_better_cut_some_part_off {
            get {
                return ResourceManager.GetString("I_should_better_cut_some_part_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I should use the cut off part..
        /// </summary>
        internal static string I_should_better_use_the_cut_off_part {
            get {
                return ResourceManager.GetString("I_should_better_use_the_cut_off_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I should open the package, first..
        /// </summary>
        internal static string I_should_open_the_package_first {
            get {
                return ResourceManager.GetString("I_should_open_the_package_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought he was taking them regularly..
        /// </summary>
        internal static string I_thought_he_was_taking_them_regularly {
            get {
                return ResourceManager.GetString("I_thought_he_was_taking_them_regularly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought we changed schools because he was getting bullied... Why would Cynthia keep this letter a secret from me?.
        /// </summary>
        internal static string I_thought_we_changed_schools_because_he_was_getting_bullied_Why_would_Cynthia_keep_this_letter_a_secret_from_me {
            get {
                return ResourceManager.GetString("I_thought_we_changed_schools_because_he_was_getting_bullied_Why_would_Cynthia_kee" +
                        "p_this_letter_a_secret_from_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I triangulated the signal already..
        /// </summary>
        internal static string I_triangulated_the_signal_already {
            get {
                return ResourceManager.GetString("I_triangulated_the_signal_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wonder what is inside..
        /// </summary>
        internal static string I_wonder_what_is_inside {
            get {
                return ResourceManager.GetString("I_wonder_what_is_inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wonder what Landon used those antennas for....
        /// </summary>
        internal static string I_wonder_what_Landon_used_those_antennas_for {
            get {
                return ResourceManager.GetString("I_wonder_what_Landon_used_those_antennas_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d love to, but I have more important things to tend to..
        /// </summary>
        internal static string Id_love_to_but_I_have_more_important_things_to_tend_to {
            get {
                return ResourceManager.GetString("Id_love_to_but_I_have_more_important_things_to_tend_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If all you have is a hammer, everything looks like a nail..
        /// </summary>
        internal static string If_all_you_have_is_a_hammer_everything_looks_like_a_nail {
            get {
                return ResourceManager.GetString("If_all_you_have_is_a_hammer_everything_looks_like_a_nail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m knotting a string on the ring at the very top..
        /// </summary>
        internal static string Im_knotting_a_string_on_the_ring_at_the_very_top {
            get {
                return ResourceManager.GetString("Im_knotting_a_string_on_the_ring_at_the_very_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not hungry..
        /// </summary>
        internal static string Im_not_hungry {
            get {
                return ResourceManager.GetString("Im_not_hungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not taking this kind of medicine..
        /// </summary>
        internal static string Im_not_taking_this_kind_of_medicine {
            get {
                return ResourceManager.GetString("Im_not_taking_this_kind_of_medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In there are different attachments for drilling machines..
        /// </summary>
        internal static string In_there_are_different_attachments_for_drilling_machines {
            get {
                return ResourceManager.GetString("In_there_are_different_attachments_for_drilling_machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It broke in two parts..
        /// </summary>
        internal static string It_broke_in_two_parts {
            get {
                return ResourceManager.GetString("It_broke_in_two_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welp, it crashed..
        /// </summary>
        internal static string It_crashed {
            get {
                return ResourceManager.GetString("It_crashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It fell down the hole..
        /// </summary>
        internal static string It_fell_down_the_hole {
            get {
                return ResourceManager.GetString("It_fell_down_the_hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a portrait of my son Landon from when he was six years old..
        /// </summary>
        internal static string It_is_a_portrait_of_my_son_Landon_when_he_was_six_years_old {
            get {
                return ResourceManager.GetString("It_is_a_portrait_of_my_son_Landon_when_he_was_six_years_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is empty..
        /// </summary>
        internal static string It_is_empty {
            get {
                return ResourceManager.GetString("It_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is sufficiently bright..
        /// </summary>
        internal static string It_is_sufficiently_bright {
            get {
                return ResourceManager.GetString("It_is_sufficiently_bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It reads:.
        /// </summary>
        internal static string It_reads {
            get {
                return ResourceManager.GetString("It_reads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It stops here. The other page seems to be missing. Not like I don&apos;t remember it, anyways..
        /// </summary>
        internal static string It_stops_here_The_other_page_seems_to_be_missing {
            get {
                return ResourceManager.GetString("It_stops_here_The_other_page_seems_to_be_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was pretty fun freaking the neighbor&apos;s dog out with it though..
        /// </summary>
        internal static string It_was_pretty_fun_freaking_the_neighbors_dog_out_with_it_though {
            get {
                return ResourceManager.GetString("It_was_pretty_fun_freaking_the_neighbors_dog_out_with_it_though", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a book about RFID technology. I wrote a research paper about it in university..
        /// </summary>
        internal static string Its_a_book_about_RFID_technology_I_wrote_a_research_paper_about_it_in_university {
            get {
                return ResourceManager.GetString("Its_a_book_about_RFID_technology_I_wrote_a_research_paper_about_it_in_university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a hand-held controller for the drone..
        /// </summary>
        internal static string Its_a_handheld_controller_for_the_drone {
            get {
                return ResourceManager.GetString("Its_a_handheld_controller_for_the_drone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a screwdriver..
        /// </summary>
        internal static string Its_a_screwdriver {
            get {
                return ResourceManager.GetString("Its_a_screwdriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a tool with a heavy piece of metal at the end of a handle..
        /// </summary>
        internal static string Its_a_tool_with_a_heavy_piece_of_metal_at_the_end_of_a_handle {
            get {
                return ResourceManager.GetString("Its_a_tool_with_a_heavy_piece_of_metal_at_the_end_of_a_handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve got to find a way out of here..
        /// </summary>
        internal static string Ive_got_to_find_a_way_out_of_here {
            get {
                return ResourceManager.GetString("Ive_got_to_find_a_way_out_of_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landon&apos;s antidepressants. Wait, these haven&apos;t even been opened!.
        /// </summary>
        internal static string Landons_antidepressants_They_have_not_yet_been_opened {
            get {
                return ResourceManager.GetString("Landons_antidepressants_They_have_not_yet_been_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see....
        /// </summary>
        internal static string Lets_see {
            get {
                return ResourceManager.GetString("Lets_see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see what&apos;s in there....
        /// </summary>
        internal static string Lets_see_whats_in_there {
            get {
                return ResourceManager.GetString("Lets_see_whats_in_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at that..
        /// </summary>
        internal static string Look_at_that {
            get {
                return ResourceManager.GetString("Look_at_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks exactly like the other box I got..
        /// </summary>
        internal static string Looks_extactly_like_the_other_cardboard_I_got {
            get {
                return ResourceManager.GetString("Looks_extactly_like_the_other_cardboard_I_got", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks extactly like the other box that had the RFID antenna..
        /// </summary>
        internal static string Looks_extactly_like_the_other_cardboard_which_contained_the_RFID_antenna {
            get {
                return ResourceManager.GetString("Looks_extactly_like_the_other_cardboard_which_contained_the_RFID_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr. Johnson: » When you first realized you were trapped, what did you do? «.
        /// </summary>
        internal static string Mr_Psychiatrist__When_you_first_realized_you_were_trapped_what_did_you_do_ {
            get {
                return ResourceManager.GetString("Mr_Psychiatrist__When_you_first_realized_you_were_trapped_what_did_you_do_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » Before I was there, you know? How did it come to this? And where was my family? «.
        /// </summary>
        internal static string Mr_Schmidt__Before_I_was_there_you_know_How_did_it_come_to_this_And_where_was_my_family_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__Before_I_was_there_you_know_How_did_it_come_to_this_And_where_was_my_" +
                        "family_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » But then, I wasn&apos;t even sure how I&apos;d gotten there. «.
        /// </summary>
        internal static string Mr_Schmidt__But_then_I_wasnt_even_sure_how_Id_gotten_there_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__But_then_I_wasnt_even_sure_how_Id_gotten_there_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » Especially not if my family was in danger somewhere else. «.
        /// </summary>
        internal static string Mr_Schmidt__Especially_not_if_my_family_was_in_danger_somewhere_else_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__Especially_not_if_my_family_was_in_danger_somewhere_else_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » I did my best to figure out what was going on. I wasn&apos;t just going to sit down and take it! «.
        /// </summary>
        internal static string Mr_Schmidt__I_did_my_best_to_figure_out_what_was_going_on_I_wasnt_just_going_to_sit_down_and_take_it_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__I_did_my_best_to_figure_out_what_was_going_on_I_wasnt_just_going_to_s" +
                        "it_down_and_take_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » I got frustrated. I tried to remember what I was doing before it all started. «.
        /// </summary>
        internal static string Mr_Schmidt__I_got_frustrated_I_tried_to_remember_what_I_was_doing_before_it_all_started_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__I_got_frustrated_I_tried_to_remember_what_I_was_doing_before_it_all_s" +
                        "tarted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » I just lost it. I was terrified. «.
        /// </summary>
        internal static string Mr_Schmidt__I_just_lost_it_I_was_terrified_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__I_just_lost_it_I_was_terrified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » I stayed calm. I wasn&apos;t just going to give up. «.
        /// </summary>
        internal static string Mr_Schmidt__I_stayed_calm_I_wasnt_just_going_to_give_up_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__I_stayed_calm_I_wasnt_just_going_to_give_up_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » I was just trying everything I could to get out of there. «.
        /// </summary>
        internal static string Mr_Schmidt__I_was_just_trying_everything_I_could_to_get_out_of_there_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__I_was_just_trying_everything_I_could_to_get_out_of_there_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Schmidt: » I was trying to think back on it, and I just... couldn&apos;t remember. «.
        /// </summary>
        internal static string Mr_Schmidt__I_was_trying_to_think_back_on_it_and_I_just_couldnt_remember_ {
            get {
                return ResourceManager.GetString("Mr_Schmidt__I_was_trying_to_think_back_on_it_and_I_just_couldnt_remember_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be Cynthia&apos;s or Landon&apos;s..
        /// </summary>
        internal static string Must_be_Cynthias_or_Landons {
            get {
                return ResourceManager.GetString("Must_be_Cynthias_or_Landons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be Landon&apos;s..
        /// </summary>
        internal static string Must_be_Landons {
            get {
                return ResourceManager.GetString("Must_be_Landons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picnic for now..
        /// </summary>
        internal static string No_picnic_for_now {
            get {
                return ResourceManager.GetString("No_picnic_for_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No power..
        /// </summary>
        internal static string No_power {
            get {
                return ResourceManager.GetString("No_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signal along that direction..
        /// </summary>
        internal static string No_signal_along_that_direction {
            get {
                return ResourceManager.GetString("No_signal_along_that_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. There are too many good memories attached to it..
        /// </summary>
        internal static string No_There_are_many_good_memories_attached_to_it {
            get {
                return ResourceManager.GetString("No_There_are_many_good_memories_attached_to_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing more in there..
        /// </summary>
        internal static string Nothing_more_in_there {
            get {
                return ResourceManager.GetString("Nothing_more_in_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now the other antenna....
        /// </summary>
        internal static string Now_the_other_antenna {
            get {
                return ResourceManager.GetString("Now_the_other_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One battery is installed..
        /// </summary>
        internal static string One_battery_is_installed {
            get {
                return ResourceManager.GetString("One_battery_is_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One pair of bandage scissors..
        /// </summary>
        internal static string One_pair_of_bandage_scissors {
            get {
                return ResourceManager.GetString("One_pair_of_bandage_scissors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our old picnic blanket... Wow, I didn&apos;t know we kept it..
        /// </summary>
        internal static string Our_old_picnic_blanket_wow_I_didnt_know_we_kept_it {
            get {
                return ResourceManager.GetString("Our_old_picnic_blanket_wow_I_didnt_know_we_kept_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paper clip.
        /// </summary>
        internal static string Paperclip_Paperclip_PaperClip {
            get {
                return ResourceManager.GetString("Paperclip_Paperclip_PaperClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paper clips.
        /// </summary>
        internal static string Paperclips_Paperclips_PaperClips {
            get {
                return ResourceManager.GetString("Paperclips_Paperclips_PaperClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antidepressants.
        /// </summary>
        internal static string Pills_Pills_Antidepressants {
            get {
                return ResourceManager.GetString("Pills_Pills_Antidepressants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portrait.
        /// </summary>
        internal static string Portrait_Portrait_Portrait {
            get {
                return ResourceManager.GetString("Portrait_Portrait_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliable and robust..
        /// </summary>
        internal static string Reliable_and_robust {
            get {
                return ResourceManager.GetString("Reliable_and_robust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote control.
        /// </summary>
        internal static string RemoteControl_RemoteControl_RemoteControl {
            get {
                return ResourceManager.GetString("RemoteControl_RemoteControl_RemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID antenna.
        /// </summary>
        internal static string RFIDAntenna_RFIDAntenna_RFIDAntenna {
            get {
                return ResourceManager.GetString("RFIDAntenna_RFIDAntenna_RFIDAntenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cardboard.
        /// </summary>
        internal static string RFIDAntennaBoxCabinet_RFIDAntennaBoxCabinet_Cardboard {
            get {
                return ResourceManager.GetString("RFIDAntennaBoxCabinet_RFIDAntennaBoxCabinet_Cardboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID book.
        /// </summary>
        internal static string RFIDBook_RFIDBook_RFIDBook {
            get {
                return ResourceManager.GetString("RFIDBook_RFIDBook_RFIDBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bi-metal hole saw kit.
        /// </summary>
        internal static string SawKit_SawKit_BiMetalHoleSawKit {
            get {
                return ResourceManager.GetString("SawKit_SawKit_BiMetalHoleSawKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scissors.
        /// </summary>
        internal static string Scissors_Scissors_Scissors {
            get {
                return ResourceManager.GetString("Scissors_Scissors_Scissors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screwdriver.
        /// </summary>
        internal static string Screwdriver_Screwdriver_Screwdriver {
            get {
                return ResourceManager.GetString("Screwdriver_Screwdriver_Screwdriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like the signal is coming from this wooden panel near the workbench..
        /// </summary>
        internal static string Seems_like_the_signal_is_coming_from_this_wooden_panel_near_the_workbench {
            get {
                return ResourceManager.GetString("Seems_like_the_signal_is_coming_from_this_wooden_panel_near_the_workbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start engine and ascend..
        /// </summary>
        internal static string Start_engine_and_ascend {
            get {
                return ResourceManager.GetString("Start_engine_and_ascend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch off..
        /// </summary>
        internal static string Switch_off {
            get {
                return ResourceManager.GetString("Switch_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That should be enough..
        /// </summary>
        internal static string That_should_be_enough {
            get {
                return ResourceManager.GetString("That_should_be_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The antenna is receiving a signal somewhere along that direction..
        /// </summary>
        internal static string The_antenna_is_receiving_a_signal_somewhere_along_that_direction {
            get {
                return ResourceManager.GetString("The_antenna_is_receiving_a_signal_somewhere_along_that_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battery compartment has place for two batteries..
        /// </summary>
        internal static string The_battery_compartment_has_place_for_two_batteries {
            get {
                return ResourceManager.GetString("The_battery_compartment_has_place_for_two_batteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battery compartment is empty..
        /// </summary>
        internal static string The_battery_compartment_is_empty {
            get {
                return ResourceManager.GetString("The_battery_compartment_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The envelope is from Landon&apos;s old school..
        /// </summary>
        internal static string The_envelope_is_from_Landons_old_school {
            get {
                return ResourceManager.GetString("The_envelope_is_from_Landons_old_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plastic wrapping is missing..
        /// </summary>
        internal static string The_plastic_wrapping_is_missing {
            get {
                return ResourceManager.GetString("The_plastic_wrapping_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plastic wrapping is missing on some of them..
        /// </summary>
        internal static string The_plastic_wrapping_is_missing_on_some_of_them {
            get {
                return ResourceManager.GetString("The_plastic_wrapping_is_missing_on_some_of_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two broken parts are utterly useless..
        /// </summary>
        internal static string The_two_broken_parts_are_utterly_useless {
            get {
                return ResourceManager.GetString("The_two_broken_parts_are_utterly_useless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to therapy log.
        /// </summary>
        internal static string TherapyLog_TherapyLog_TherapyLog {
            get {
                return ResourceManager.GetString("TherapyLog_TherapyLog_TherapyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be a RFID receiver underneath for some reason..
        /// </summary>
        internal static string There_must_be_a_RFID_receiver_underneath_for_some_reason {
            get {
                return ResourceManager.GetString("There_must_be_a_RFID_receiver_underneath_for_some_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are my replacement guitar strings..
        /// </summary>
        internal static string These_are_my_replacement_guitar_strings {
            get {
                return ResourceManager.GetString("These_are_my_replacement_guitar_strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They can even cut through metal..
        /// </summary>
        internal static string They_can_even_cut_through_metal {
            get {
                return ResourceManager.GetString("They_can_even_cut_through_metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not need to be screwed..
        /// </summary>
        internal static string This_does_not_need_to_be_screwed {
            get {
                return ResourceManager.GetString("This_does_not_need_to_be_screwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a long-range RFID antenna..
        /// </summary>
        internal static string This_is_a_longrange_RFID_antenna {
            get {
                return ResourceManager.GetString("This_is_a_longrange_RFID_antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an old xanax prescription which was issued for me some years ago..
        /// </summary>
        internal static string This_is_an_old_xanax_prescription_which_was_issued_for_me_some_years_ago {
            get {
                return ResourceManager.GetString("This_is_an_old_xanax_prescription_which_was_issued_for_me_some_years_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This small key was glued to the back of Landon&apos;s portrait..
        /// </summary>
        internal static string This_small_key_was_glued_to_the_back_of_Landons_portrait {
            get {
                return ResourceManager.GetString("This_small_key_was_glued_to_the_back_of_Landons_portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This small wooden box was hidden underneath a plank..
        /// </summary>
        internal static string This_small_wooden_box_was_hidden_underneath_a_plank {
            get {
                return ResourceManager.GetString("This_small_wooden_box_was_hidden_underneath_a_plank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Those are Landon&apos;s antidepressants. They have not yet been opened..
        /// </summary>
        internal static string Those_are_Landons_antidepressants_They_have_not_yet_been_opened {
            get {
                return ResourceManager.GetString("Those_are_Landons_antidepressants_They_have_not_yet_been_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Left..
        /// </summary>
        internal static string Turn_Left {
            get {
                return ResourceManager.GetString("Turn_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Right..
        /// </summary>
        internal static string Turn_Right {
            get {
                return ResourceManager.GetString("Turn_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two batteries are installed..
        /// </summary>
        internal static string Two_batteries_are_installed {
            get {
                return ResourceManager.GetString("Two_batteries_are_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreliable garbage..
        /// </summary>
        internal static string Unreliable_garbage {
            get {
                return ResourceManager.GetString("Unreliable_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What a beast..
        /// </summary>
        internal static string What_a_beast {
            get {
                return ResourceManager.GetString("What_a_beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What the hell would he do with a baton?.
        /// </summary>
        internal static string What_the_hell_would_he_do_with_a_baton {
            get {
                return ResourceManager.GetString("What_the_hell_would_he_do_with_a_baton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s this about?.
        /// </summary>
        internal static string Whats_this_about {
            get {
                return ResourceManager.GetString("Whats_this_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wooden box.
        /// </summary>
        internal static string WoodenBox_WoodenBox_WoodenBox {
            get {
                return ResourceManager.GetString("WoodenBox_WoodenBox_WoodenBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yet..
        /// </summary>
        internal static string Yet {
            get {
                return ResourceManager.GetString("Yet", resourceCulture);
            }
        }
    }
}
