//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Session_2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Session_2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Resources_Session_2", typeof(Resources_Session_2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And no matter how hard I tried, I just couldn&apos;t wake up..
        /// </summary>
        internal static string And_no_matter_how_hard_I_tried_I_just_couldnt_wake_up {
            get {
                return ResourceManager.GetString("And_no_matter_how_hard_I_tried_I_just_couldnt_wake_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before I was there, you know? How did it come to this? And where was my family?.
        /// </summary>
        internal static string Before_I_was_there_you_know_How_did_it_come_to_this_And_where_was_my_family {
            get {
                return ResourceManager.GetString("Before_I_was_there_you_know_How_did_it_come_to_this_And_where_was_my_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But then, I wasn&apos;t even sure how I&apos;d gotten there..
        /// </summary>
        internal static string But_then_I_wasnt_even_sure_how_Id_gotten_there {
            get {
                return ResourceManager.GetString("But_then_I_wasnt_even_sure_how_Id_gotten_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t you think it&apos;d be less confusing if you started with how you got there in the first place?.
        /// </summary>
        internal static string Dont_you_think_itd_be_less_confusing_if_you_started_with_how_you_got_there_in_the_first_place {
            get {
                return ResourceManager.GetString("Dont_you_think_itd_be_less_confusing_if_you_started_with_how_you_got_there_in_the" +
                        "_first_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especially not if my family was in danger somewhere else..
        /// </summary>
        internal static string Especially_not_if_my_family_was_in_danger_somewhere_else {
            get {
                return ResourceManager.GetString("Especially_not_if_my_family_was_in_danger_somewhere_else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did my best to figure out what was going on. I wasn&apos;t just going to sit down and take it!.
        /// </summary>
        internal static string I_did_my_best_to_figure_out_what_was_going_on_I_wasnt_just_going_to_sit_down_and_take_it {
            get {
                return ResourceManager.GetString("I_did_my_best_to_figure_out_what_was_going_on_I_wasnt_just_going_to_sit_down_and_" +
                        "take_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I got frustrated. I tried to remember what I was doing before it all started..
        /// </summary>
        internal static string I_got_frustrated_I_tried_to_remember_what_I_was_doing_before_it_all_started {
            get {
                return ResourceManager.GetString("I_got_frustrated_I_tried_to_remember_what_I_was_doing_before_it_all_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess that started with figuring out how I&apos;d gotten there in the first place..
        /// </summary>
        internal static string I_guess_that_started_with_figuring_out_how_Id_gotten_there_in_the_first_place {
            get {
                return ResourceManager.GetString("I_guess_that_started_with_figuring_out_how_Id_gotten_there_in_the_first_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just lost it. I was terrified..
        /// </summary>
        internal static string I_just_lost_it_I_was_terrified {
            get {
                return ResourceManager.GetString("I_just_lost_it_I_was_terrified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I looked everywhere for clues, anything I could find that might help me fix the mess I&apos;d gotten myself into..
        /// </summary>
        internal static string I_looked_everywhere_for_clues_anything_I_could_find_that_might_help_me_fix_the_mess_Id_gotten_myself_into {
            get {
                return ResourceManager.GetString("I_looked_everywhere_for_clues_anything_I_could_find_that_might_help_me_fix_the_me" +
                        "ss_Id_gotten_myself_into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I stayed calm. I wasn&apos;t just going to give up..
        /// </summary>
        internal static string I_stayed_calm_I_wasnt_just_going_to_give_up {
            get {
                return ResourceManager.GetString("I_stayed_calm_I_wasnt_just_going_to_give_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I was hoping somebody would hear me, but nobody was there....
        /// </summary>
        internal static string I_think_I_was_hoping_somebody_would_hear_me_but_nobody_was_there {
            get {
                return ResourceManager.GetString("I_think_I_was_hoping_somebody_would_hear_me_but_nobody_was_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was just trying everything I could to get out of there..
        /// </summary>
        internal static string I_was_just_trying_everything_I_could_to_get_out_of_there {
            get {
                return ResourceManager.GetString("I_was_just_trying_everything_I_could_to_get_out_of_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was trying to think back on it, and I just... couldn&apos;t remember..
        /// </summary>
        internal static string I_was_trying_to_think_back_on_it_and_I_just_couldnt_remember {
            get {
                return ResourceManager.GetString("I_was_trying_to_think_back_on_it_and_I_just_couldnt_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If only I knew....
        /// </summary>
        internal static string If_only_I_knew {
            get {
                return ResourceManager.GetString("If_only_I_knew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was like everything leading up to that point was just a dream, and I couldn&apos;t quite piece together where it started or ended..
        /// </summary>
        internal static string It_was_like_everything_leading_up_to_that_point_was_just_a_dream_and_I_couldnt_quite_piece_together_where_it_started_or_ended {
            get {
                return ResourceManager.GetString("It_was_like_everything_leading_up_to_that_point_was_just_a_dream_and_I_couldnt_qu" +
                        "ite_piece_together_where_it_started_or_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither my wife or my son was answering me. I thought maybe they were in danger too. .
        /// </summary>
        internal static string Neither_my_wife_or_my_son_was_answering_me_I_thought_maybe_they_were_in_danger_too_ {
            get {
                return ResourceManager.GetString("Neither_my_wife_or_my_son_was_answering_me_I_thought_maybe_they_were_in_danger_to" +
                        "o_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was making sense to me. It was like a mad blur. I felt like banging on the walls most of the time..
        /// </summary>
        internal static string Nothing_was_making_sense_to_me_It_was_like_a_mad_blur_I_felt_like_banging_on_the_walls_most_of_the_time {
            get {
                return ResourceManager.GetString("Nothing_was_making_sense_to_me_It_was_like_a_mad_blur_I_felt_like_banging_on_the_" +
                        "walls_most_of_the_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s just it... I didn&apos;t know..
        /// </summary>
        internal static string Thats_just_it_I_didnt_know {
            get {
                return ResourceManager.GetString("Thats_just_it_I_didnt_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, I think the beginning is a good place to start... How did you think you got there?.
        /// </summary>
        internal static string Well_I_think_the_beginning_is_a_good_place_to_start_How_did_you_think_you_got_there {
            get {
                return ResourceManager.GetString("Well_I_think_the_beginning_is_a_good_place_to_start_How_did_you_think_you_got_the" +
                        "re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, that implies that I had any idea at all....
        /// </summary>
        internal static string Well_that_implies_that_I_had_any_idea_at_all {
            get {
                return ResourceManager.GetString("Well_that_implies_that_I_had_any_idea_at_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, why don&apos;t we start there?.
        /// </summary>
        internal static string Well_why_dont_we_start_there {
            get {
                return ResourceManager.GetString("Well_why_dont_we_start_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you first realized you were trapped, what did you do?.
        /// </summary>
        internal static string When_you_first_realized_you_were_trapped_what_did_you_do {
            get {
                return ResourceManager.GetString("When_you_first_realized_you_were_trapped_what_did_you_do", resourceCulture);
            }
        }
    }
}
