//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloom.
        /// </summary>
        internal static string Bloom {
            get {
                return ResourceManager.GetString("Bloom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        internal static string Borderless {
            get {
                return ResourceManager.GetString("Borderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Fit.
        /// </summary>
        internal static string Borderless_Fit {
            get {
                return ResourceManager.GetString("Borderless_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Scale.
        /// </summary>
        internal static string Borderless_Scale {
            get {
                return ResourceManager.GetString("Borderless_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t do that..
        /// </summary>
        internal static string Cant_do_that {
            get {
                return ResourceManager.GetString("Cant_do_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t use that..
        /// </summary>
        internal static string Cant_use_that {
            get {
                return ResourceManager.GetString("Cant_use_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load save game. Maybe it was created in an earlier game version..
        /// </summary>
        internal static string Could_not_load_save_game_Maybe_it_was_created_in_an_earlier_game_version {
            get {
                return ResourceManager.GetString("Could_not_load_save_game_Maybe_it_was_created_in_an_earlier_game_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        internal static string Display_Mode {
            get {
                return ResourceManager.GetString("Display_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to quit the game?.
        /// </summary>
        internal static string Do_you_really_want_to_quit_the_game {
            get {
                return ResourceManager.GetString("Do_you_really_want_to_quit_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give.
        /// </summary>
        internal static string Give {
            get {
                return ResourceManager.GetString("Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How?.
        /// </summary>
        internal static string How {
            get {
                return ResourceManager.GetString("How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t close that..
        /// </summary>
        internal static string I_cant_close_that {
            get {
                return ResourceManager.GetString("I_cant_close_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t do that..
        /// </summary>
        internal static string I_cant_do_that {
            get {
                return ResourceManager.GetString("I_cant_do_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t give that to somebody..
        /// </summary>
        internal static string I_cant_give_that_to_somebody {
            get {
                return ResourceManager.GetString("I_cant_give_that_to_somebody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t open that..
        /// </summary>
        internal static string I_cant_open_that {
            get {
                return ResourceManager.GetString("I_cant_open_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t talk to that..
        /// </summary>
        internal static string I_cant_talk_to_that {
            get {
                return ResourceManager.GetString("I_cant_talk_to_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t need that..
        /// </summary>
        internal static string I_dont_need_that {
            get {
                return ResourceManager.GetString("I_dont_need_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t see anything special..
        /// </summary>
        internal static string I_dont_see_anything_special {
            get {
                return ResourceManager.GetString("I_dont_see_anything_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t see the point in taking that..
        /// </summary>
        internal static string I_dont_see_the_point_in_taking_that {
            get {
                return ResourceManager.GetString("I_dont_see_the_point_in_taking_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t want to move that..
        /// </summary>
        internal static string I_dont_want_to_move_that {
            get {
                return ResourceManager.GetString("I_dont_want_to_move_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess there won&apos;t be an answer..
        /// </summary>
        internal static string I_guess_there_wont_be_an_answer {
            get {
                return ResourceManager.GetString("I_guess_there_wont_be_an_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have got this already..
        /// </summary>
        internal static string I_have_got_this_already {
            get {
                return ResourceManager.GetString("I_have_got_this_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have it already..
        /// </summary>
        internal static string I_have_it_already {
            get {
                return ResourceManager.GetString("I_have_it_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m carrying that..
        /// </summary>
        internal static string Im_carrying_that {
            get {
                return ResourceManager.GetString("Im_carrying_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanover School Headmaster’s Office
        ///January the 13th, 2017
        ///
        ///Dear Mr. and Mrs. Schmidt,
        ///
        ///I am writing to inform you of an incident in which Landon was involved today at school. 
        ///Around 10:45 this morning, He was brought into my office by another teacher, who was 
        ///approached about him after class by a very distressed female student. The student claims 
        ///to have been cornered by Landon in the girls’ lavatory before school this morning. He 
        ///told me that he was just trying to ask her to formal, which the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Letter_Text {
            get {
                return ResourceManager.GetString("Letter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Savegame.
        /// </summary>
        internal static string Load_Savegame {
            get {
                return ResourceManager.GetString("Load_Savegame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at.
        /// </summary>
        internal static string Look_at {
            get {
                return ResourceManager.GetString("Look_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Menu_AddExitConfirmationWindow_No {
            get {
                return ResourceManager.GetString("Menu_AddExitConfirmationWindow_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        internal static string Music_Volume {
            get {
                return ResourceManager.GetString("Music_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string New_Game {
            get {
                return ResourceManager.GetString("New_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to see here..
        /// </summary>
        internal static string Nothing_to_see_here {
            get {
                return ResourceManager.GetString("Nothing_to_see_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up.
        /// </summary>
        internal static string Pick_up {
            get {
                return ResourceManager.GetString("Pick_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        internal static string Pull {
            get {
                return ResourceManager.GetString("Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        internal static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really quit?.
        /// </summary>
        internal static string Really_quit {
            get {
                return ResourceManager.GetString("Really_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the game for this setting to take effect..
        /// </summary>
        internal static string Restart_the_game_for_this_setting_to_take_effect {
            get {
                return ResourceManager.GetString("Restart_the_game_for_this_setting_to_take_effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rooms/letter/scene.
        /// </summary>
        internal static string RoomsLetterScene {
            get {
                return ResourceManager.GetString("RoomsLetterScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Volume.
        /// </summary>
        internal static string Sound_Volume {
            get {
                return ResourceManager.GetString("Sound_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to.
        /// </summary>
        internal static string Talk_to {
            get {
                return ResourceManager.GetString("Talk_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That does not need to be closed..
        /// </summary>
        internal static string That_does_not_need_to_be_closed {
            get {
                return ResourceManager.GetString("That_does_not_need_to_be_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That does not need to be opened..
        /// </summary>
        internal static string That_does_not_need_to_be_opened {
            get {
                return ResourceManager.GetString("That_does_not_need_to_be_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That does not work..
        /// </summary>
        internal static string That_does_not_work {
            get {
                return ResourceManager.GetString("That_does_not_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no need to carry that around..
        /// </summary>
        internal static string There_is_no_need_to_carry_that_around {
            get {
                return ResourceManager.GetString("There_is_no_need_to_carry_that_around", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no need to move that..
        /// </summary>
        internal static string There_is_no_need_to_move_that {
            get {
                return ResourceManager.GetString("There_is_no_need_to_move_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can&apos;t be closed..
        /// </summary>
        internal static string This_cant_be_closed {
            get {
                return ResourceManager.GetString("This_cant_be_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can&apos;t be opened..
        /// </summary>
        internal static string This_cant_be_opened {
            get {
                return ResourceManager.GetString("This_cant_be_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui\verbs.
        /// </summary>
        internal static string uiverbs {
            get {
                return ResourceManager.GetString("uiverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui\verbshighlight.
        /// </summary>
        internal static string uiverbshighlight {
            get {
                return ResourceManager.GetString("uiverbshighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSync.
        /// </summary>
        internal static string VSync {
            get {
                return ResourceManager.GetString("VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk to.
        /// </summary>
        internal static string Walk_to {
            get {
                return ResourceManager.GetString("Walk_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Fit.
        /// </summary>
        internal static string Window_Fit {
            get {
                return ResourceManager.GetString("Window_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string with {
            get {
                return ResourceManager.GetString("with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
