//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Session_4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Session_4() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Resources_Session_4", typeof(Resources_Session_4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And do you find that playing helps you when you are... agitated?.
        /// </summary>
        internal static string And_do_you_find_that_playing_helps_you_when_you_are_agitated {
            get {
                return ResourceManager.GetString("And_do_you_find_that_playing_helps_you_when_you_are_agitated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And you like your work?.
        /// </summary>
        internal static string And_you_like_your_work {
            get {
                return ResourceManager.GetString("And_you_like_your_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyways, work isn&apos;t the only thing that makes up a man. What would you say you do for fun?.
        /// </summary>
        internal static string Anyways_work_isnt_the_only_thing_that_makes_up_a_man_What_would_you_say_you_do_for_fun {
            get {
                return ResourceManager.GetString("Anyways_work_isnt_the_only_thing_that_makes_up_a_man_What_would_you_say_you_do_fo" +
                        "r_fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t complain..
        /// </summary>
        internal static string Cant_complain {
            get {
                return ResourceManager.GetString("Cant_complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have to call it that?.
        /// </summary>
        internal static string Do_you_have_to_call_it_that {
            get {
                return ResourceManager.GetString("Do_you_have_to_call_it_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...Don&apos;t you believe me?.
        /// </summary>
        internal static string Dont_you_believe_me {
            get {
                return ResourceManager.GetString("Dont_you_believe_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good to hear. Your family is your support system..
        /// </summary>
        internal static string Good_to_hear_Your_family_is_your_support_system {
            get {
                return ResourceManager.GetString("Good_to_hear_Your_family_is_your_support_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see. Perhaps this time, however, it was for the best?.
        /// </summary>
        internal static string I_see_Perhaps_this_time_however_it_was_for_the_best {
            get {
                return ResourceManager.GetString("I_see_Perhaps_this_time_however_it_was_for_the_best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think we could both benefit from learning a little bit more about yourself..
        /// </summary>
        internal static string I_think_we_could_both_benefit_from_learning_a_little_bit_more_about_yourself {
            get {
                return ResourceManager.GetString("I_think_we_could_both_benefit_from_learning_a_little_bit_more_about_yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a mechanical engineer..
        /// </summary>
        internal static string Im_a_mechanical_engineer {
            get {
                return ResourceManager.GetString("Im_a_mechanical_engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, is there something else you would prefer I call your episodes?.
        /// </summary>
        internal static string Im_sorry_is_there_something_else_you_would_prefer_I_call_your_episodes {
            get {
                return ResourceManager.GetString("Im_sorry_is_there_something_else_you_would_prefer_I_call_your_episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry to hear that..
        /// </summary>
        internal static string Im_sorry_to_hear_that {
            get {
                return ResourceManager.GetString("Im_sorry_to_hear_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is that true? You&apos;re taking your medications regularly?.
        /// </summary>
        internal static string Is_that_true_Youre_taking_your_medications_regularly {
            get {
                return ResourceManager.GetString("Is_that_true_Youre_taking_your_medications_regularly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s awful..
        /// </summary>
        internal static string Its_awful {
            get {
                return ResourceManager.GetString("Its_awful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like what?.
        /// </summary>
        internal static string Like_what {
            get {
                return ResourceManager.GetString("Like_what", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. It doesn&apos;t matter to me if I&apos;m with my family..
        /// </summary>
        internal static string No_It_doesnt_matter_to_me_if_Im_with_my_family {
            get {
                return ResourceManager.GetString("No_It_doesnt_matter_to_me_if_Im_with_my_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, I don&apos;t know... I play the guitar?.
        /// </summary>
        internal static string Oh_I_dont_know_I_play_the_guitar {
            get {
                return ResourceManager.GetString("Oh_I_dont_know_I_play_the_guitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So were you upset about having to change offices to be with your son?.
        /// </summary>
        internal static string So_were_you_upset_about_having_to_change_offices_to_be_with_your_son {
            get {
                return ResourceManager.GetString("So_were_you_upset_about_having_to_change_offices_to_be_with_your_son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s good. Liking what you do is important..
        /// </summary>
        internal static string Thats_good_Liking_what_you_do_is_important {
            get {
                return ResourceManager.GetString("Thats_good_Liking_what_you_do_is_important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s unfortunate. But I wonder if you can&apos;t make something better for yourself where you are now..
        /// </summary>
        internal static string Thats_unfortunate_But_I_wonder_if_you_cant_make_something_better_for_yourself_where_you_are_now {
            get {
                return ResourceManager.GetString("Thats_unfortunate_But_I_wonder_if_you_cant_make_something_better_for_yourself_whe" +
                        "re_you_are_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, I... I don&apos;t know. It doesn&apos;t matter. Besides, I haven&apos;t had a problem like that in a long time..
        /// </summary>
        internal static string Well_I_I_dont_know_It_doesnt_matter_Besides_I_havent_had_a_problem_like_that_in_a_long_time {
            get {
                return ResourceManager.GetString("Well_I_I_dont_know_It_doesnt_matter_Besides_I_havent_had_a_problem_like_that_in_a" +
                        "_long_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, what do you do for work?.
        /// </summary>
        internal static string Well_what_do_you_do_for_work {
            get {
                return ResourceManager.GetString("Well_what_do_you_do_for_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. I don&apos;t handle change well..
        /// </summary>
        internal static string Yes_I_dont_handle_change_well {
            get {
                return ResourceManager.GetString("Yes_I_dont_handle_change_well", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. I had it good where I was..
        /// </summary>
        internal static string Yes_I_had_it_good_where_I_was {
            get {
                return ResourceManager.GetString("Yes_I_had_it_good_where_I_was", resourceCulture);
            }
        }
    }
}
