//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Session_3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Session_3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Resources_Session_3", typeof(Resources_Session_3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And?.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And what are your thoughts on Landon, as of now?.
        /// </summary>
        internal static string And_what_are_your_thoughts_on_Landon_as_of_now {
            get {
                return ResourceManager.GetString("And_what_are_your_thoughts_on_Landon_as_of_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And who knows? Maybe she even knew I was following her after all..
        /// </summary>
        internal static string And_who_knows_Maybe_she_even_knew_I_was_following_her_after_all {
            get {
                return ResourceManager.GetString("And_who_knows_Maybe_she_even_knew_I_was_following_her_after_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And who were you then?.
        /// </summary>
        internal static string And_who_were_you_then {
            get {
                return ResourceManager.GetString("And_who_were_you_then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And you do think that she&apos;s still holding something back from you? Even now?.
        /// </summary>
        internal static string And_you_do_think_that_shes_still_holding_something_back_from_you_Even_now {
            get {
                return ResourceManager.GetString("And_you_do_think_that_shes_still_holding_something_back_from_you_Even_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And you don&apos;t think things will ever be the same now..
        /// </summary>
        internal static string And_you_dont_think_things_will_ever_be_the_same_now {
            get {
                return ResourceManager.GetString("And_you_dont_think_things_will_ever_be_the_same_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And you plan to be there for him?.
        /// </summary>
        internal static string And_you_plan_to_be_there_for_him {
            get {
                return ResourceManager.GetString("And_you_plan_to_be_there_for_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And you think you could get that back one day?.
        /// </summary>
        internal static string And_you_think_you_could_get_that_back_one_day {
            get {
                return ResourceManager.GetString("And_you_think_you_could_get_that_back_one_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any love I had for her is just getting slowly destroyed by what she did..
        /// </summary>
        internal static string Any_love_I_had_for_her_is_just_getting_slowly_destroyed_by_what_she_did {
            get {
                return ResourceManager.GetString("Any_love_I_had_for_her_is_just_getting_slowly_destroyed_by_what_she_did", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before what?.
        /// </summary>
        internal static string Before_what {
            get {
                return ResourceManager.GetString("Before_what", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But do you really think she&apos;s still lying to you? Even now?.
        /// </summary>
        internal static string But_do_you_really_think_shes_still_lying_to_you_Even_now {
            get {
                return ResourceManager.GetString("But_do_you_really_think_shes_still_lying_to_you_Even_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...but we just got so tired of all the family and the friends and it was such a nice, sunny day outside..
        /// </summary>
        internal static string but_we_just_got_so_tired_of_all_the_family_and_the_friends_and_it_was_such_a_nice_sunny_day_outside {
            get {
                return ResourceManager.GetString("but_we_just_got_so_tired_of_all_the_family_and_the_friends_and_it_was_such_a_nice" +
                        "_sunny_day_outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But you do think you will be staying with Cynthia, as of now?.
        /// </summary>
        internal static string But_you_do_think_you_will_be_staying_with_Cynthia_as_of_now {
            get {
                return ResourceManager.GetString("But_you_do_think_you_will_be_staying_with_Cynthia_as_of_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But you still don&apos;t trust her..
        /// </summary>
        internal static string But_you_still_dont_trust_her {
            get {
                return ResourceManager.GetString("But_you_still_dont_trust_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I really love somebody I don&apos;t even fully trust?.
        /// </summary>
        internal static string Can_I_really_love_somebody_I_dont_even_fully_trust {
            get {
                return ResourceManager.GetString("Can_I_really_love_somebody_I_dont_even_fully_trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cynthia and I haven&apos;t been on particularly good ground since this all began..
        /// </summary>
        internal static string Cynthia_and_I_havent_been_on_particularly_good_ground_since_this_all_began {
            get {
                return ResourceManager.GetString("Cynthia_and_I_havent_been_on_particularly_good_ground_since_this_all_began", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I really even have to tell you?.
        /// </summary>
        internal static string Do_I_really_even_have_to_tell_you {
            get {
                return ResourceManager.GetString("Do_I_really_even_have_to_tell_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything she says to me, every time she leaves the house for groceries or whatever, I have to try and figure out if she&apos;s being honest with me or not..
        /// </summary>
        internal static string Everything_she_says_to_me_every_time_she_leaves_the_house_for_groceries_or_whatever_I_have_to_try_and_figure_out_if_shes_being_honest_with_me_or_not {
            get {
                return ResourceManager.GetString("Everything_she_says_to_me_every_time_she_leaves_the_house_for_groceries_or_whatev" +
                        "er_I_have_to_try_and_figure_out_if_shes_being_honest_with_me_or_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good to hear. How have things been with your wife, since all of this?.
        /// </summary>
        internal static string Good_to_hear_How_have_things_been_with_your_wife_since_all_of_this {
            get {
                return ResourceManager.GetString("Good_to_hear_How_have_things_been_with_your_wife_since_all_of_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you told her you feel this way?.
        /// </summary>
        internal static string Have_you_told_her_you_feel_this_way {
            get {
                return ResourceManager.GetString("Have_you_told_her_you_feel_this_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you tried talking to her about this?.
        /// </summary>
        internal static string Have_you_tried_talking_to_her_about_this {
            get {
                return ResourceManager.GetString("Have_you_tried_talking_to_her_about_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honestly, I still haven&apos;t forgiven her for all this..
        /// </summary>
        internal static string Honestly_I_still_havent_forgiven_her_for_all_this {
            get {
                return ResourceManager.GetString("Honestly_I_still_havent_forgiven_her_for_all_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t imagine loving somebody I don&apos;t even trust. Especially not after what she&apos;s done. It&apos;s not possible for me..
        /// </summary>
        internal static string I_cant_imagine_loving_somebody_I_dont_even_trust_Especially_not_after_what_shes_done_Its_not_possible_for_me {
            get {
                return ResourceManager.GetString("I_cant_imagine_loving_somebody_I_dont_even_trust_Especially_not_after_what_shes_d" +
                        "one_Its_not_possible_for_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t just stop loving her. She&apos;s been my best friend since college..
        /// </summary>
        internal static string I_cant_just_stop_loving_her_Shes_been_my_best_friend_since_college {
            get {
                return ResourceManager.GetString("I_cant_just_stop_loving_her_Shes_been_my_best_friend_since_college", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know..
        /// </summary>
        internal static string I_dont_know {
            get {
                return ResourceManager.GetString("I_dont_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know. I really hope so..
        /// </summary>
        internal static string I_dont_know_I_really_hope_so {
            get {
                return ResourceManager.GetString("I_dont_know_I_really_hope_so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know if I ever will be able to trust her again. Not completely..
        /// </summary>
        internal static string I_dont_know_if_I_ever_will_be_able_to_trust_her_again_Not_completely {
            get {
                return ResourceManager.GetString("I_dont_know_if_I_ever_will_be_able_to_trust_her_again_Not_completely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t think I have much of a choice. Besides, I think one day we&apos;ll get back to who we were..
        /// </summary>
        internal static string I_dont_think_I_have_much_of_a_choice_Besides_I_think_one_day_well_get_back_to_who_we_were {
            get {
                return ResourceManager.GetString("I_dont_think_I_have_much_of_a_choice_Besides_I_think_one_day_well_get_back_to_who" +
                        "_we_were", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I... I don&apos;t know. Honestly, I just think this is going to take time..
        /// </summary>
        internal static string I_I_dont_know_Honestly_I_just_think_this_is_going_to_take_time {
            get {
                return ResourceManager.GetString("I_I_dont_know_Honestly_I_just_think_this_is_going_to_take_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just don&apos;t think I can get over this..
        /// </summary>
        internal static string I_just_dont_think_I_can_get_over_this {
            get {
                return ResourceManager.GetString("I_just_dont_think_I_can_get_over_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just don&apos;t think there&apos;s even a chance we&apos;ll go back to the way things were. Not now..
        /// </summary>
        internal static string I_just_dont_think_theres_even_a_chance_well_go_back_to_the_way_things_were_Not_now {
            get {
                return ResourceManager.GetString("I_just_dont_think_theres_even_a_chance_well_go_back_to_the_way_things_were_Not_no" +
                        "w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know there was a point where Cynthia and I were... well, we were really happy..
        /// </summary>
        internal static string I_know_there_was_a_point_where_Cynthia_and_I_were_well_we_were_really_happy {
            get {
                return ResourceManager.GetString("I_know_there_was_a_point_where_Cynthia_and_I_were_well_we_were_really_happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know you keep telling me I should just move on, but it&apos;s just....
        /// </summary>
        internal static string I_know_you_keep_telling_me_I_should_just_move_on_but_its_just {
            get {
                return ResourceManager.GetString("I_know_you_keep_telling_me_I_should_just_move_on_but_its_just", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like to think we&apos;re getting better..
        /// </summary>
        internal static string I_like_to_think_were_getting_better {
            get {
                return ResourceManager.GetString("I_like_to_think_were_getting_better", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I liked those people..
        /// </summary>
        internal static string I_liked_those_people {
            get {
                return ResourceManager.GetString("I_liked_those_people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I mean, it&apos;s hard to know with her, whether or not she&apos;s telling the truth, even now, but we are trying..
        /// </summary>
        internal static string I_mean_its_hard_to_know_with_her_whether_or_not_shes_telling_the_truth_even_now_but_we_are_trying {
            get {
                return ResourceManager.GetString("I_mean_its_hard_to_know_with_her_whether_or_not_shes_telling_the_truth_even_now_b" +
                        "ut_we_are_trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I really do want to trust her again. It&apos;s just... not easy. .
        /// </summary>
        internal static string I_really_do_want_to_trust_her_again_Its_just_not_easy_ {
            get {
                return ResourceManager.GetString("I_really_do_want_to_trust_her_again_Its_just_not_easy_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I stayed clear back so she wouldn&apos;t recognize me, and I followed her all the way to where she was going..
        /// </summary>
        internal static string I_stayed_clear_back_so_she_wouldnt_recognize_me_and_I_followed_her_all_the_way_to_where_she_was_going {
            get {
                return ResourceManager.GetString("I_stayed_clear_back_so_she_wouldnt_recognize_me_and_I_followed_her_all_the_way_to" +
                        "_where_she_was_going", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I&apos;d prefer we save that for another session, Doctor. .
        /// </summary>
        internal static string I_think_Id_prefer_we_save_that_for_another_session_Doctor_ {
            get {
                return ResourceManager.GetString("I_think_Id_prefer_we_save_that_for_another_session_Doctor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought I could let it go, but I couldn&apos;t..
        /// </summary>
        internal static string I_thought_I_could_let_it_go_but_I_couldnt {
            get {
                return ResourceManager.GetString("I_thought_I_could_let_it_go_but_I_couldnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought you said we should talk about something LESS painful..
        /// </summary>
        internal static string I_thought_you_said_we_should_talk_about_something_LESS_painful {
            get {
                return ResourceManager.GetString("I_thought_you_said_we_should_talk_about_something_LESS_painful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to love her, of course I do, but... how can I when I&apos;m too busy analyzing everything she does?.
        /// </summary>
        internal static string I_want_to_love_her_of_course_I_do_but_how_can_I_when_Im_too_busy_analyzing_everything_she_does {
            get {
                return ResourceManager.GetString("I_want_to_love_her_of_course_I_do_but_how_can_I_when_Im_too_busy_analyzing_everyt" +
                        "hing_she_does", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m telling myself she&apos;s not, that we&apos;ve gotten it all out there by now, but... it&apos;s hard to say for sure..
        /// </summary>
        internal static string Im_telling_myself_shes_not_that_weve_gotten_it_all_out_there_by_now_but_its_hard_to_say_for_sure {
            get {
                return ResourceManager.GetString("Im_telling_myself_shes_not_that_weve_gotten_it_all_out_there_by_now_but_its_hard_" +
                        "to_say_for_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was beautiful. I miss that..
        /// </summary>
        internal static string It_was_beautiful_I_miss_that {
            get {
                return ResourceManager.GetString("It_was_beautiful_I_miss_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s been awhile now since everything went down. I&apos;m trying my best..
        /// </summary>
        internal static string Its_been_awhile_now_since_everything_went_down_Im_trying_my_best {
            get {
                return ResourceManager.GetString("Its_been_awhile_now_since_everything_went_down_Im_trying_my_best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s hard to reestablish trust in somebody that constantly seems like they&apos;re holding something back. .
        /// </summary>
        internal static string Its_hard_to_reestablish_trust_in_somebody_that_constantly_seems_like_theyre_holding_something_back_ {
            get {
                return ResourceManager.GetString("Its_hard_to_reestablish_trust_in_somebody_that_constantly_seems_like_theyre_holdi" +
                        "ng_something_back_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s maddening..
        /// </summary>
        internal static string Its_maddening {
            get {
                return ResourceManager.GetString("Its_maddening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just last week she said she was going out to the gym. It&apos;s been years since she last went to the gym..
        /// </summary>
        internal static string Just_last_week_she_said_she_was_going_out_to_the_gym_Its_been_years_since_she_last_went_to_the_gym {
            get {
                return ResourceManager.GetString("Just_last_week_she_said_she_was_going_out_to_the_gym_Its_been_years_since_she_las" +
                        "t_went_to_the_gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s talk about something less painful for a while..
        /// </summary>
        internal static string Lets_talk_about_something_less_painful_for_a_while {
            get {
                return ResourceManager.GetString("Lets_talk_about_something_less_painful_for_a_while", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe not....
        /// </summary>
        internal static string Maybe_not {
            get {
                return ResourceManager.GetString("Maybe_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe some day....
        /// </summary>
        internal static string Maybe_some_day {
            get {
                return ResourceManager.GetString("Maybe_some_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. I think this was just a rare instance of honesty for her..
        /// </summary>
        internal static string No_I_think_this_was_just_a_rare_instance_of_honesty_for_her {
            get {
                return ResourceManager.GetString("No_I_think_this_was_just_a_rare_instance_of_honesty_for_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Never again..
        /// </summary>
        internal static string No_Never_again {
            get {
                return ResourceManager.GetString("No_Never_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Not yet. There&apos;s still too much at stake. I have to think about Landon too, here..
        /// </summary>
        internal static string No_Not_yet_Theres_still_too_much_at_stake_I_have_to_think_about_Landon_too_here {
            get {
                return ResourceManager.GetString("No_Not_yet_Theres_still_too_much_at_stake_I_have_to_think_about_Landon_too_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, of course not. Not yet. But I swear to god it&apos;s driving me insane..
        /// </summary>
        internal static string No_of_course_not_Not_yet_But_I_swear_to_god_its_driving_me_insane {
            get {
                return ResourceManager.GetString("No_of_course_not_Not_yet_But_I_swear_to_god_its_driving_me_insane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not anymore. I can&apos;t..
        /// </summary>
        internal static string Not_anymore_I_cant {
            get {
                return ResourceManager.GetString("Not_anymore_I_cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course..
        /// </summary>
        internal static string Of_course {
            get {
                return ResourceManager.GetString("Of_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course I have good memories. I married the woman, for god&apos;s sakes....
        /// </summary>
        internal static string Of_course_I_have_good_memories_I_married_the_woman_for_gods_sakes {
            get {
                return ResourceManager.GetString("Of_course_I_have_good_memories_I_married_the_woman_for_gods_sakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course, I&apos;m sorry. We&apos;ll save that for another session..
        /// </summary>
        internal static string Of_course_Im_sorry_Well_save_that_for_another_session {
            get {
                return ResourceManager.GetString("Of_course_Im_sorry_Well_save_that_for_another_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no, I let her go. She walked out of the house, got into the car, and drove off down the street before....
        /// </summary>
        internal static string Oh_no_I_let_her_go_She_walked_out_of_the_house_got_into_the_car_and_drove_off_down_the_street_before {
            get {
                return ResourceManager.GetString("Oh_no_I_let_her_go_She_walked_out_of_the_house_got_into_the_car_and_drove_off_dow" +
                        "n_the_street_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who went camping, and rode bikes together, and watched shitty movies together just to make fun of them..
        /// </summary>
        internal static string People_who_went_camping_and_rode_bikes_together_and_watched_shitty_movies_together_just_to_make_fun_of_them {
            get {
                return ResourceManager.GetString("People_who_went_camping_and_rode_bikes_together_and_watched_shitty_movies_togethe" +
                        "r_just_to_make_fun_of_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She has to be. You don&apos;t just uproot somebody&apos;s life like that with such little reason..
        /// </summary>
        internal static string She_has_to_be_You_dont_just_uproot_somebodys_life_like_that_with_such_little_reason {
            get {
                return ResourceManager.GetString("She_has_to_be_You_dont_just_uproot_somebodys_life_like_that_with_such_little_reas" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She was my best friend, and I would have trusted her with my life. We did everything together. Sometimes I think back on that..
        /// </summary>
        internal static string She_was_my_best_friend_and_I_would_have_trusted_her_with_my_life_We_did_everything_together_Sometimes_I_think_back_on_that {
            get {
                return ResourceManager.GetString("She_was_my_best_friend_and_I_would_have_trusted_her_with_my_life_We_did_everythin" +
                        "g_together_Sometimes_I_think_back_on_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She went straight to the gym..
        /// </summary>
        internal static string She_went_straight_to_the_gym {
            get {
                return ResourceManager.GetString("She_went_straight_to_the_gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She&apos;s my wife, of course I do..
        /// </summary>
        internal static string Shes_my_wife_of_course_I_do {
            get {
                return ResourceManager.GetString("Shes_my_wife_of_course_I_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She&apos;s still hiding something from me, even now. I know she is. She didn&apos;t even want me coming in to see you..
        /// </summary>
        internal static string Shes_still_hiding_something_from_me_even_now_I_know_she_is_She_didnt_even_want_me_coming_in_to_see_you {
            get {
                return ResourceManager.GetString("Shes_still_hiding_something_from_me_even_now_I_know_she_is_She_didnt_even_want_me" +
                        "_coming_in_to_see_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you didn&apos;t let her go?.
        /// </summary>
        internal static string So_you_didnt_let_her_go {
            get {
                return ResourceManager.GetString("So_you_didnt_let_her_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds good to me..
        /// </summary>
        internal static string Sounds_good_to_me {
            get {
                return ResourceManager.GetString("Sounds_good_to_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kind of people that would sneak out of our own wedding reception just to make out and get something greasy to eat..
        /// </summary>
        internal static string The_kind_of_people_that_would_sneak_out_of_our_own_wedding_reception_just_to_make_out_and_get_something_greasy_to_eat {
            get {
                return ResourceManager.GetString("The_kind_of_people_that_would_sneak_out_of_our_own_wedding_reception_just_to_make" +
                        "_out_and_get_something_greasy_to_eat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two aren&apos;t exactly mutually exclusive. I don&apos;t know. I don&apos;t really want to talk about him right now..
        /// </summary>
        internal static string The_two_arent_exactly_mutually_exclusive_I_dont_know_I_dont_really_want_to_talk_about_him_right_now {
            get {
                return ResourceManager.GetString("The_two_arent_exactly_mutually_exclusive_I_dont_know_I_dont_really_want_to_talk_a" +
                        "bout_him_right_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We ended up just pulling off the highway at this lake, just me and her, and lying in the grass for hours on our picnic blanket, just soaking up the sun together until it went down..
        /// </summary>
        internal static string We_ended_up_just_pulling_off_the_highway_at_this_lake_just_me_and_her_and_lying_in_the_grass_for_hours_on_our_picnic_blanket_just_soaking_up_the_sun_together_until_it_went_down {
            get {
                return ResourceManager.GetString("We_ended_up_just_pulling_off_the_highway_at_this_lake_just_me_and_her_and_lying_i" +
                        "n_the_grass_for_hours_on_our_picnic_blanket_just_soaking_up_the_sun_together_unt" +
                        "il_it_went_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had one day, not long before Landon was born, when we were supposed to be out getting some decorations for our baby shower....
        /// </summary>
        internal static string We_had_one_day_not_long_before_Landon_was_born_when_we_were_supposed_to_be_out_getting_some_decorations_for_our_baby_shower {
            get {
                return ResourceManager.GetString("We_had_one_day_not_long_before_Landon_was_born_when_we_were_supposed_to_be_out_ge" +
                        "tting_some_decorations_for_our_baby_shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a son together. He... he needs us both..
        /// </summary>
        internal static string We_have_a_son_together_He_he_needs_us_both {
            get {
                return ResourceManager.GetString("We_have_a_son_together_He_he_needs_us_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well alright, that&apos;s fair. But tell me this, Ryan. Do you still love her?.
        /// </summary>
        internal static string Well_alright_thats_fair_But_tell_me_this_Ryan_Do_you_still_love_her {
            get {
                return ResourceManager.GetString("Well_alright_thats_fair_But_tell_me_this_Ryan_Do_you_still_love_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, I&apos;m not proud of it, but... I followed her..
        /// </summary>
        internal static string Well_Im_not_proud_of_it_but_I_followed_her {
            get {
                return ResourceManager.GetString("Well_Im_not_proud_of_it_but_I_followed_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happened to them?.
        /// </summary>
        internal static string What_happened_to_them {
            get {
                return ResourceManager.GetString("What_happened_to_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday I even cooked pasta for her..
        /// </summary>
        internal static string Yesterday_I_even_cooked_pasta_for_her {
            get {
                return ResourceManager.GetString("Yesterday_I_even_cooked_pasta_for_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any good memories with her? Something to convince you otherwise? .
        /// </summary>
        internal static string You_dont_have_any_good_memories_with_her_Something_to_convince_you_otherwise_ {
            get {
                return ResourceManager.GetString("You_dont_have_any_good_memories_with_her_Something_to_convince_you_otherwise_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t just move on from something like that, you know?.
        /// </summary>
        internal static string You_dont_just_move_on_from_something_like_that_you_know {
            get {
                return ResourceManager.GetString("You_dont_just_move_on_from_something_like_that_you_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You think she could still be lying to you?.
        /// </summary>
        internal static string You_think_she_could_still_be_lying_to_you {
            get {
                return ResourceManager.GetString("You_think_she_could_still_be_lying_to_you", resourceCulture);
            }
        }
    }
}
