//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Session_6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Session_6() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Resources_Session_6", typeof(Resources_Session_6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wrench?.
        /// </summary>
        internal static string A_wrench {
            get {
                return ResourceManager.GetString("A_wrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All that time, I thought my family was in danger..
        /// </summary>
        internal static string All_that_time_I_thought_my_family_was_in_danger {
            get {
                return ResourceManager.GetString("All_that_time_I_thought_my_family_was_in_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And all that time I&apos;d just been abandoned..
        /// </summary>
        internal static string And_all_that_time_Id_just_been_abandoned {
            get {
                return ResourceManager.GetString("And_all_that_time_Id_just_been_abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And did he say anything to you after that?.
        /// </summary>
        internal static string And_did_he_say_anything_to_you_after_that {
            get {
                return ResourceManager.GetString("And_did_he_say_anything_to_you_after_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And how did that go?.
        /// </summary>
        internal static string And_how_did_that_go {
            get {
                return ResourceManager.GetString("And_how_did_that_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Landon must have heard..
        /// </summary>
        internal static string And_Landon_must_have_heard {
            get {
                return ResourceManager.GetString("And_Landon_must_have_heard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And she... she did. She shook herself out of my grip and went to him after only about a minute..
        /// </summary>
        internal static string And_she_she_did_She_shook_herself_out_of_my_grip_and_went_to_him_after_only_about_a_minute {
            get {
                return ResourceManager.GetString("And_she_she_did_She_shook_herself_out_of_my_grip_and_went_to_him_after_only_about" +
                        "_a_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And that&apos;s all you remember? It was Landon all along?.
        /// </summary>
        internal static string And_thats_all_you_remember_It_was_Landon_all_along {
            get {
                return ResourceManager.GetString("And_thats_all_you_remember_It_was_Landon_all_along", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And that&apos;s it? It was both of them, working together?.
        /// </summary>
        internal static string And_thats_it_It_was_both_of_them_working_together {
            get {
                return ResourceManager.GetString("And_thats_it_It_was_both_of_them_working_together", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And that&apos;s the last thing I remember..
        /// </summary>
        internal static string And_thats_the_last_thing_I_remember {
            get {
                return ResourceManager.GetString("And_thats_the_last_thing_I_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And then?.
        /// </summary>
        internal static string And_then {
            get {
                return ResourceManager.GetString("And_then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And then he fell..
        /// </summary>
        internal static string And_then_he_fell {
            get {
                return ResourceManager.GetString("And_then_he_fell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And then he fell on top of me, like a rag doll, and I just knew..
        /// </summary>
        internal static string And_then_he_fell_on_top_of_me_like_a_rag_doll_and_I_just_knew {
            get {
                return ResourceManager.GetString("And_then_he_fell_on_top_of_me_like_a_rag_doll_and_I_just_knew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And then... It was like my body acted on its own. I didn&apos;t even think about it..
        /// </summary>
        internal static string And_then_It_was_like_my_body_acted_on_its_own_I_didnt_even_think_about_it {
            get {
                return ResourceManager.GetString("And_then_It_was_like_my_body_acted_on_its_own_I_didnt_even_think_about_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And what did she say to you?.
        /// </summary>
        internal static string And_what_did_she_say_to_you {
            get {
                return ResourceManager.GetString("And_what_did_she_say_to_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And what was he doing?.
        /// </summary>
        internal static string And_what_was_he_doing {
            get {
                return ResourceManager.GetString("And_what_was_he_doing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you alright, Ryan?.
        /// </summary>
        internal static string Are_you_alright_Ryan {
            get {
                return ResourceManager.GetString("Are_you_alright_Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready to tell me what happened that night?.
        /// </summary>
        internal static string Are_you_ready_to_tell_me_what_happened_that_night {
            get {
                return ResourceManager.GetString("Are_you_ready_to_tell_me_what_happened_that_night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At first she wasn&apos;t making any sense. She kept saying things like &quot;I&apos;m alright, I&apos;m alright, it wasn&apos;t his fault&quot;, and I was asking her &quot;who is he?&quot;..
        /// </summary>
        internal static string At_first_she_wasnt_making_any_sense_She_kept_saying_things_like_Im_alright_Im_alright_it_wasnt_his_fault_and_I_was_asking_her_who_is_he {
            get {
                return ResourceManager.GetString("At_first_she_wasnt_making_any_sense_She_kept_saying_things_like_Im_alright_Im_alr" +
                        "ight_it_wasnt_his_fault_and_I_was_asking_her_who_is_he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But I was wrong..
        /// </summary>
        internal static string But_I_was_wrong {
            get {
                return ResourceManager.GetString("But_I_was_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But if you killed him, then how did you...?.
        /// </summary>
        internal static string But_if_you_killed_him_then_how_did_you {
            get {
                return ResourceManager.GetString("But_if_you_killed_him_then_how_did_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But she was absolutely broken. I found her still sitting on the floor, trying to act like nothing was wrong..
        /// </summary>
        internal static string But_she_was_absolutely_brokenI_found_her_still_sitting_on_the_floor_trying_to_act_like_nothing_was_wrong {
            get {
                return ResourceManager.GetString("But_she_was_absolutely_brokenI_found_her_still_sitting_on_the_floor_trying_to_act" +
                        "_like_nothing_was_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But she wouldn&apos;t..
        /// </summary>
        internal static string But_she_wouldnt {
            get {
                return ResourceManager.GetString("But_she_wouldnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But that&apos;s not what happened..
        /// </summary>
        internal static string But_thats_not_what_happened {
            get {
                return ResourceManager.GetString("But_thats_not_what_happened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But who was he?.
        /// </summary>
        internal static string But_who_was_he {
            get {
                return ResourceManager.GetString("But_who_was_he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cynthia, too?.
        /// </summary>
        internal static string Cynthia_too {
            get {
                return ResourceManager.GetString("Cynthia_too", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did he admit to hurting her?.
        /// </summary>
        internal static string Did_he_admit_to_hurting_her {
            get {
                return ResourceManager.GetString("Did_he_admit_to_hurting_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did he hurt you too?.
        /// </summary>
        internal static string Did_he_hurt_you_too {
            get {
                return ResourceManager.GetString("Did_he_hurt_you_too", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you call the police?.
        /// </summary>
        internal static string Did_you_call_the_police {
            get {
                return ResourceManager.GetString("Did_you_call_the_police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t make it sound like I knew what I was doing. I didn&apos;t, I really didn&apos;t..
        /// </summary>
        internal static string Dont_make_it_sound_like_I_knew_what_I_was_doing_I_didnt_I_really_didnt {
            get {
                return ResourceManager.GetString("Dont_make_it_sound_like_I_knew_what_I_was_doing_I_didnt_I_really_didnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty and maybe a little annoyed that I was there..
        /// </summary>
        internal static string Empty_and_maybe_a_little_annoyed_that_I_was_there {
            get {
                return ResourceManager.GetString("Empty_and_maybe_a_little_annoyed_that_I_was_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especially not my family. I thought we could just pack up and escape..
        /// </summary>
        internal static string Especially_not_my_family_I_thought_we_could_just_pack_up_and_escape {
            get {
                return ResourceManager.GetString("Especially_not_my_family_I_thought_we_could_just_pack_up_and_escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the son you raised..
        /// </summary>
        internal static string From_the_son_you_raised {
            get {
                return ResourceManager.GetString("From_the_son_you_raised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He asked me what I was doing. I told him I just wanted to talk..
        /// </summary>
        internal static string He_asked_me_what_I_was_doing_I_told_him_I_just_wanted_to_talk {
            get {
                return ResourceManager.GetString("He_asked_me_what_I_was_doing_I_told_him_I_just_wanted_to_talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He didn&apos;t look like he regretted anything at all. He just looked empty..
        /// </summary>
        internal static string He_didnt_look_like_he_regretted_anything_at_all_He_just_looked_empty {
            get {
                return ResourceManager.GetString("He_didnt_look_like_he_regretted_anything_at_all_He_just_looked_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He didn&apos;t move or say anything, so I just went ahead and sat down next to him on the bed..
        /// </summary>
        internal static string He_didnt_move_or_say_anything_so_I_just_went_ahead_and_sat_down_next_to_him_on_the_bed {
            get {
                return ResourceManager.GetString("He_didnt_move_or_say_anything_so_I_just_went_ahead_and_sat_down_next_to_him_on_th" +
                        "e_bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He got all quiet, and I looked him in the eyes and he just looked surprised..
        /// </summary>
        internal static string He_got_all_quiet_and_I_looked_him_in_the_eyes_and_he_just_looked_surprised {
            get {
                return ResourceManager.GetString("He_got_all_quiet_and_I_looked_him_in_the_eyes_and_he_just_looked_surprised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He got right back up and turned around, and I realized at that moment that whoever I was looking at wasn&apos;t my son..
        /// </summary>
        internal static string He_got_right_back_up_and_turned_around_and_I_realized_in_that_moment_that_whoever_I_was_looking_at_wasnt_my_son {
            get {
                return ResourceManager.GetString("He_got_right_back_up_and_turned_around_and_I_realized_in_that_moment_that_whoever" +
                        "_I_was_looking_at_wasnt_my_son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He just said he was sure she&apos;d be alright. Honestly, it broke my heart..
        /// </summary>
        internal static string He_just_said_he_was_sure_shed_be_alright_Honestly_it_broke_my_heart {
            get {
                return ResourceManager.GetString("He_just_said_he_was_sure_shed_be_alright_Honestly_it_broke_my_heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He knocked the air straight out of me. Put me flat on my back..
        /// </summary>
        internal static string He_knocked_the_air_straight_out_of_me_Put_me_flat_on_my_back {
            get {
                return ResourceManager.GetString("He_knocked_the_air_straight_out_of_me_Put_me_flat_on_my_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He pulled the wrench out from under his leg before I could do anything..
        /// </summary>
        internal static string He_pulled_the_wrench_out_from_under_his_leg_before_I_could_do_anything {
            get {
                return ResourceManager.GetString("He_pulled_the_wrench_out_from_under_his_leg_before_I_could_do_anything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He told me I really ought to mind my own business..
        /// </summary>
        internal static string He_told_me_I_really_ought_to_mind_my_own_business {
            get {
                return ResourceManager.GetString("He_told_me_I_really_ought_to_mind_my_own_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was holding a wrench. He didn&apos;t even look at me. He just told Cynthia to come to him..
        /// </summary>
        internal static string He_was_holding_a_wrench_He_didnt_even_look_at_me_He_just_told_Cynthia_to_come_to_him {
            get {
                return ResourceManager.GetString("He_was_holding_a_wrench_He_didnt_even_look_at_me_He_just_told_Cynthia_to_come_to_" +
                        "him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was our son. He slept in our house. We took care of him when he was sick..
        /// </summary>
        internal static string He_was_our_son_He_slept_in_our_house_We_took_care_of_him_when_he_was_sick {
            get {
                return ResourceManager.GetString("He_was_our_son_He_slept_in_our_house_We_took_care_of_him_when_he_was_sick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her lip was bleeding, and one of her eyes was turning black on the spot..
        /// </summary>
        internal static string Her_lip_was_bleeding_and_one_of_her_eyes_was_turning_black_on_the_spot {
            get {
                return ResourceManager.GetString("Her_lip_was_bleeding_and_one_of_her_eyes_was_turning_black_on_the_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His mother tucked him in at night for years..
        /// </summary>
        internal static string His_mother_tucked_him_in_at_night_for_years {
            get {
                return ResourceManager.GetString("His_mother_tucked_him_in_at_night_for_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How about we take a short break. You can catch your breath..
        /// </summary>
        internal static string How_about_we_take_a_short_break_You_can_catch_your_breath {
            get {
                return ResourceManager.GetString("How_about_we_take_a_short_break_You_can_catch_your_breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I asked him what happened. I asked him if he knew what state his mother was in downstairs..
        /// </summary>
        internal static string I_asked_him_what_happened_I_asked_him_if_he_knew_what_state_his_mother_was_in_downstairs {
            get {
                return ResourceManager.GetString("I_asked_him_what_happened_I_asked_him_if_he_knew_what_state_his_mother_was_in_dow" +
                        "nstairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I could see him in his room, before he could see me..
        /// </summary>
        internal static string I_could_see_him_in_his_room_before_he_could_see_me {
            get {
                return ResourceManager.GetString("I_could_see_him_in_his_room_before_he_could_see_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t help it. I started crying. I couldn&apos;t understand what was happening. I just wanted it to be a nightmare..
        /// </summary>
        internal static string I_couldnt_help_it_I_started_cryingI_couldnt_understand_what_was_happening_I_just_wanted_it_to_be_a_nightmare {
            get {
                return ResourceManager.GetString("I_couldnt_help_it_I_started_cryingI_couldnt_understand_what_was_happening_I_just_" +
                        "wanted_it_to_be_a_nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t just abandon him. He&apos;s my son..
        /// </summary>
        internal static string I_couldnt_just_abandon_him_Hes_my_son {
            get {
                return ResourceManager.GetString("I_couldnt_just_abandon_him_Hes_my_son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t believe it myself. I couldn&apos;t have..
        /// </summary>
        internal static string I_didnt_believe_it_myself_I_couldnt_have {
            get {
                return ResourceManager.GetString("I_didnt_believe_it_myself_I_couldnt_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t know what else I could do!.
        /// </summary>
        internal static string I_didnt_know_what_else_I_could_do {
            get {
                return ResourceManager.GetString("I_didnt_know_what_else_I_could_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t really have a choice. I just knew I needed to stop him..
        /// </summary>
        internal static string I_didnt_really_have_a_choice_I_just_knew_I_needed_to_stop_him {
            get {
                return ResourceManager.GetString("I_didnt_really_have_a_choice_I_just_knew_I_needed_to_stop_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t want to believe it..
        /// </summary>
        internal static string I_didnt_want_to_believe_it {
            get {
                return ResourceManager.GetString("I_didnt_want_to_believe_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...I don&apos;t know. I just don&apos;t know. Somebody soulless..
        /// </summary>
        internal static string I_dont_know_I_just_dont_know_Somebody_soulless {
            get {
                return ResourceManager.GetString("I_dont_know_I_just_dont_know_Somebody_soulless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know if she believed me. Then I went upstairs. His door was slightly open..
        /// </summary>
        internal static string I_dont_know_if_she_believed_me_Then_I_went_upstairs_His_door_was_slightly_open {
            get {
                return ResourceManager.GetString("I_dont_know_if_she_believed_me_Then_I_went_upstairs_His_door_was_slightly_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t think I want to understand. I don&apos;t want to know what was happening in his head..
        /// </summary>
        internal static string I_dont_think_I_want_to_understand_I_dont_want_to_know_what_was_happening_in_his_head {
            get {
                return ResourceManager.GetString("I_dont_think_I_want_to_understand_I_dont_want_to_know_what_was_happening_in_his_h" +
                        "ead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t want to know what he was thinking when he hit her. Or when he attacked me..
        /// </summary>
        internal static string I_dont_want_to_know_what_he_was_thinking_when_he_hit_herOr_when_he_attacked_me {
            get {
                return ResourceManager.GetString("I_dont_want_to_know_what_he_was_thinking_when_he_hit_herOr_when_he_attacked_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I ended up trying to drag her out with me, but she wouldn&apos;t cooperate. She started screaming and yelling, telling me she couldn&apos;t leave her baby..
        /// </summary>
        internal static string I_ended_up_trying_to_drag_her_out_with_me_but_she_wouldnt_cooperate_She_started_screaming_and_yelling_telling_me_she_couldnt_leave_her_baby {
            get {
                return ResourceManager.GetString("I_ended_up_trying_to_drag_her_out_with_me_but_she_wouldnt_cooperate_She_started_s" +
                        "creaming_and_yelling_telling_me_she_couldnt_leave_her_baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I got up to help her, to run over to her, but then... she lifted the vase up above her head..
        /// </summary>
        internal static string I_got_up_to_help_her_to_run_over_to_her_but_then_she_lifted_the_vase_up_above_her_head {
            get {
                return ResourceManager.GetString("I_got_up_to_help_her_to_run_over_to_her_but_then_she_lifted_the_vase_up_above_her" +
                        "_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I grabbed her arm and told her &quot;come on, we&apos;re leaving&quot;, but she just kept shaking her head..
        /// </summary>
        internal static string I_grabbed_her_arm_and_told_her_come_on_were_leaving_but_she_just_kept_shaking_her_head {
            get {
                return ResourceManager.GetString("I_grabbed_her_arm_and_told_her_come_on_were_leaving_but_she_just_kept_shaking_her" +
                        "_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess that&apos;s true..
        /// </summary>
        internal static string I_guess_thats_true {
            get {
                return ResourceManager.GetString("I_guess_thats_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I had to do something, right then and there. He was putting us all in danger..
        /// </summary>
        internal static string I_had_to_do_something_right_then_and_there_He_was_putting_us_all_in_danger {
            get {
                return ResourceManager.GetString("I_had_to_do_something_right_then_and_there_He_was_putting_us_all_in_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I helped Cynthia into a chair and got her some ice, and then I told her I&apos;d be right back. She was scared out of her mind, I think..
        /// </summary>
        internal static string I_helped_Cynthia_into_a_chair_and_got_her_some_ice_and_then_I_told_her_Id_be_right_back_She_was_scared_out_of_her_mind_I_think {
            get {
                return ResourceManager.GetString("I_helped_Cynthia_into_a_chair_and_got_her_some_ice_and_then_I_told_her_Id_be_righ" +
                        "t_back_She_was_scared_out_of_her_mind_I_think", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I... I don&apos;t know..
        /// </summary>
        internal static string I_I_dont_know {
            get {
                return ResourceManager.GetString("I_I_dont_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I jumped him from behind..
        /// </summary>
        internal static string I_jumped_him_from_behind {
            get {
                return ResourceManager.GetString("I_jumped_him_from_behind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just got so... so angry, all of a sudden. I came up behind him and I hit him, hard across the back of the head..
        /// </summary>
        internal static string I_just_got_so_so_angry_all_of_a_sudden_I_came_up_behind_him_and_I_hit_him_hard_across_the_back_of_the_head {
            get {
                return ResourceManager.GetString("I_just_got_so_so_angry_all_of_a_sudden_I_came_up_behind_him_and_I_hit_him_hard_ac" +
                        "ross_the_back_of_the_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just kept thinking about Cynthia too, and the way she&apos;d looked so pathetic and hurt..
        /// </summary>
        internal static string I_just_kept_thinking_about_Cynthia_too_and_the_way_shed_looked_so_pathetic_and_hurt {
            get {
                return ResourceManager.GetString("I_just_kept_thinking_about_Cynthia_too_and_the_way_shed_looked_so_pathetic_and_hu" +
                        "rt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just need a moment..
        /// </summary>
        internal static string I_just_need_a_moment {
            get {
                return ResourceManager.GetString("I_just_need_a_moment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I knew he was gone..
        /// </summary>
        internal static string I_knew_he_was_gone {
            get {
                return ResourceManager.GetString("I_knew_he_was_gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I knew immediately that I wasn&apos;t safe..
        /// </summary>
        internal static string I_knew_immediately_that_I_wasnt_safe {
            get {
                return ResourceManager.GetString("I_knew_immediately_that_I_wasnt_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I knew we hadn&apos;t been talking much lately, but I really thought he would care about what his own father had to say..
        /// </summary>
        internal static string I_knew_we_hadnt_been_talking_much_lately_but_I_really_thought_he_would_care_about_what_his_own_father_had_to_say {
            get {
                return ResourceManager.GetString("I_knew_we_hadnt_been_talking_much_lately_but_I_really_thought_he_would_care_about" +
                        "_what_his_own_father_had_to_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I knocked on the doorframe so that I wouldn&apos;t surprise him, and the way he looked around at me, I almost felt... scared..
        /// </summary>
        internal static string I_knocked_on_the_doorframe_so_that_I_wouldnt_surprise_him_and_the_way_he_looked_around_at_me_I_almost_felt_scared {
            get {
                return ResourceManager.GetString("I_knocked_on_the_doorframe_so_that_I_wouldnt_surprise_him_and_the_way_he_looked_a" +
                        "round_at_me_I_almost_felt_scared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I ran straight to her and asked her what happened. I thought we&apos;d had a break in..
        /// </summary>
        internal static string I_ran_straight_to_her_and_asked_her_what_happened_I_thought_wed_had_a_break_in {
            get {
                return ResourceManager.GetString("I_ran_straight_to_her_and_asked_her_what_happened_I_thought_wed_had_a_break_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I saw her, Cynthia, cowering on the floor of the kitchen..
        /// </summary>
        internal static string I_saw_her_Cynthia_cowering_on_the_floor_of_the_kitchen {
            get {
                return ResourceManager.GetString("I_saw_her_Cynthia_cowering_on_the_floor_of_the_kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I swear I could feel the irritated energy coming off of him when I did. It was... cold..
        /// </summary>
        internal static string I_swear_I_could_feel_the_irritated_energy_coming_off_of_him_when_I_did_It_was_cold {
            get {
                return ResourceManager.GetString("I_swear_I_could_feel_the_irritated_energy_coming_off_of_him_when_I_did_It_was_col" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think it was self defense, and I know I was crying, and I just swung the damn wrench up to where I thought his face might be above mine and... and....
        /// </summary>
        internal static string I_think_it_was_self_defense_and_I_know_I_was_crying_and_I_just_swung_the_damn_wrench_up_to_where_I_thought_his_face_might_be_above_mine_and_and {
            get {
                return ResourceManager.GetString("I_think_it_was_self_defense_and_I_know_I_was_crying_and_I_just_swung_the_damn_wre" +
                        "nch_up_to_where_I_thought_his_face_might_be_above_mine_and_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought maybe if I could just talk to him, father to son, he would listen..
        /// </summary>
        internal static string I_thought_maybe_if_I_could_just_talk_to_him_father_to_son_he_would_listen {
            get {
                return ResourceManager.GetString("I_thought_maybe_if_I_could_just_talk_to_him_father_to_son_he_would_listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought maybe once he saw that he wasn&apos;t going to be able to hurt us, he&apos;d sit down and listen to reason..
        /// </summary>
        internal static string I_thought_maybe_once_he_saw_that_he_wasnt_going_to_be_able_to_hurt_us_hed_sit_down_and_listen_to_reason {
            get {
                return ResourceManager.GetString("I_thought_maybe_once_he_saw_that_he_wasnt_going_to_be_able_to_hurt_us_hed_sit_dow" +
                        "n_and_listen_to_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought maybe they&apos;d been taken away, and that&apos;s why they weren&apos;t helping me..
        /// </summary>
        internal static string I_thought_maybe_theyd_been_taken_away_and_thats_why_they_werent_helping_me {
            get {
                return ResourceManager.GetString("I_thought_maybe_theyd_been_taken_away_and_thats_why_they_werent_helping_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought my family was in danger..
        /// </summary>
        internal static string I_thought_my_family_was_in_danger {
            get {
                return ResourceManager.GetString("I_thought_my_family_was_in_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought once we were safely out of there, we could call the police to confront Landon..
        /// </summary>
        internal static string I_thought_once_we_were_safely_out_of_there_we_could_call_the_police_to_confront_Landon {
            get {
                return ResourceManager.GetString("I_thought_once_we_were_safely_out_of_there_we_could_call_the_police_to_confront_L" +
                        "andon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought she was going to faint..
        /// </summary>
        internal static string I_thought_she_was_going_to_faint {
            get {
                return ResourceManager.GetString("I_thought_she_was_going_to_faint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I thought she would leave with me right away. That she would finally see sense..
        /// </summary>
        internal static string I_thought_she_would_leave_with_me_right_away_That_she_would_finally_see_sense {
            get {
                return ResourceManager.GetString("I_thought_she_would_leave_with_me_right_away_That_she_would_finally_see_sense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I told him &quot;you can&apos;t really mean that&quot;, and the look on his face when he heard my voice breaking....
        /// </summary>
        internal static string I_told_him_you_cant_really_mean_that_and_the_look_on_his_face_when_he_heard_my_voice_breaking {
            get {
                return ResourceManager.GetString("I_told_him_you_cant_really_mean_that_and_the_look_on_his_face_when_he_heard_my_vo" +
                        "ice_breaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I tried to hold his head down to the ground, but he was stronger than I thought..
        /// </summary>
        internal static string I_tried_to_hold_his_head_down_to_the_ground_but_he_was_stronger_than_I_thought {
            get {
                return ResourceManager.GetString("I_tried_to_hold_his_head_down_to_the_ground_but_he_was_stronger_than_I_thought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I tried to talk him down so that we could get him help. .
        /// </summary>
        internal static string I_tried_to_talk_him_down_so_that_we_could_get_him_help_ {
            get {
                return ResourceManager.GetString("I_tried_to_talk_him_down_so_that_we_could_get_him_help_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I tried to tell her that didn&apos;t make any sense, but she just wouldn&apos;t listen. She was sobbing. Inconsolable..
        /// </summary>
        internal static string I_tried_to_tell_her_that_didnt_make_any_sense_but_she_just_wouldnt_listen_She_was_sobbing {
            get {
                return ResourceManager.GetString("I_tried_to_tell_her_that_didnt_make_any_sense_but_she_just_wouldnt_listen_She_was" +
                        "_sobbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wanted to wake up. I wanted Landon to snap out of it..
        /// </summary>
        internal static string I_wanted_to_wake_up_I_wanted_Landon_to_snap_out_of_it {
            get {
                return ResourceManager.GetString("I_wanted_to_wake_up_I_wanted_Landon_to_snap_out_of_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was enraged..
        /// </summary>
        internal static string I_was_enraged {
            get {
                return ResourceManager.GetString("I_was_enraged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was only trying to protect her. I was trying to protect us..
        /// </summary>
        internal static string I_was_only_trying_to_protect_her_I_was_trying_to_protect_us {
            get {
                return ResourceManager.GetString("I_was_only_trying_to_protect_her_I_was_trying_to_protect_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was trying to get up and I turned around, and she was there, holding one of the heavy ceramic vases her mother gave to us..
        /// </summary>
        internal static string I_was_trying_to_get_up_and_I_turned_around_and_she_was_there_holding_one_of_the_heavy_ceramic_vases_her_mother_gave_to_us {
            get {
                return ResourceManager.GetString("I_was_trying_to_get_up_and_I_turned_around_and_she_was_there_holding_one_of_the_h" +
                        "eavy_ceramic_vases_her_mother_gave_to_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I went back to my room and started packing for Cynthia and me to get away. .
        /// </summary>
        internal static string I_went_back_to_my_room_and_started_packing_for_Cynthia_and_me_to_get_away_ {
            get {
                return ResourceManager.GetString("I_went_back_to_my_room_and_started_packing_for_Cynthia_and_me_to_get_away_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would have had to leave the house to do it, and I didn&apos;t want to leave Cynthia alone. I didn&apos;t know what he was going to do next..
        /// </summary>
        internal static string I_would_have_had_to_leave_the_house_to_do_it_and_I_didnt_want_to_leave_Cynthia_alone_I_didnt_know_what_he_was_going_to_do_next {
            get {
                return ResourceManager.GetString("I_would_have_had_to_leave_the_house_to_do_it_and_I_didnt_want_to_leave_Cynthia_al" +
                        "one_I_didnt_know_what_he_was_going_to_do_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I yelled at him to stop, but he didn&apos;t, he just kept hitting me, hitting me so hard I could barely see, and my nose was bleeding, and I called out for Cynthia but I don&apos;t think she could hear us..
        /// </summary>
        internal static string I_yelled_at_him_to_stop_but_he_didnt_he_just_kept_hitting_me_hitting_me_so_hard_I_could_barely_see_and_my_nose_was_bleeding_and_I_called_out_for_Cynthia_but_I_dont_think_she_could_hear_us {
            get {
                return ResourceManager.GetString("I_yelled_at_him_to_stop_but_he_didnt_he_just_kept_hitting_me_hitting_me_so_hard_I" +
                        "_could_barely_see_and_my_nose_was_bleeding_and_I_called_out_for_Cynthia_but_I_do" +
                        "nt_think_she_could_hear_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m only here to help you, Ryan. You know that. That has always been my goal with you..
        /// </summary>
        internal static string Im_only_here_to_help_you_Ryan_You_know_that_That_has_always_been_my_goal_with_you_ {
            get {
                return ResourceManager.GetString("Im_only_here_to_help_you_Ryan_You_know_that_That_has_always_been_my_goal_with_you" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was trying to get her to stop, telling her she needed to leave, that Landon would hear her... but....
        /// </summary>
        internal static string Inconsolable_I_was_trying_to_get_her_to_stop_telling_her_she_needed_to_leave_that_Landon_would_hear_her_but {
            get {
                return ResourceManager.GetString("Inconsolable_I_was_trying_to_get_her_to_stop_telling_her_she_needed_to_leave_that" +
                        "_Landon_would_hear_her_but", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It didn&apos;t feel like I had a choice. I didn&apos;t want anybody to get hurt any more..
        /// </summary>
        internal static string It_didnt_feel_like_I_had_a_choice_I_didnt_want_anybody_to_get_hurt_any_more {
            get {
                return ResourceManager.GetString("It_didnt_feel_like_I_had_a_choice_I_didnt_want_anybody_to_get_hurt_any_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is. So, why don&apos;t you start with what you saw when you came home?.
        /// </summary>
        internal static string It_is_So_why_dont_you_start_with_what_you_saw_when_you_came_home {
            get {
                return ResourceManager.GetString("It_is_So_why_dont_you_start_with_what_you_saw_when_you_came_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It only took him a second to realize what had happened, and who had hit him, and then he was right back up and punching me as hard as he could in the face without a word..
        /// </summary>
        internal static string It_only_took_him_a_second_to_realize_what_had_happened_and_who_had_hit_him_and_then_he_was_right_back_up_and_punching_me_as_hard_as_he_could_in_the_face_without_a_word {
            get {
                return ResourceManager.GetString("It_only_took_him_a_second_to_realize_what_had_happened_and_who_had_hit_him_and_th" +
                        "en_he_was_right_back_up_and_punching_me_as_hard_as_he_could_in_the_face_without_" +
                        "a_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It surprised him. He fell forward, and I used the opportunity to grab what he had in his lap..
        /// </summary>
        internal static string It_surprised_him_He_fell_forward_and_I_used_the_opportunity_to_grab_what_he_had_in_his_lap {
            get {
                return ResourceManager.GetString("It_surprised_him_He_fell_forward_and_I_used_the_opportunity_to_grab_what_he_had_i" +
                        "n_his_lap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It took me ages of searching around in that basement to remember even that far..
        /// </summary>
        internal static string It_took_me_ages_of_searching_around_in_that_basement_to_remember_even_that_far {
            get {
                return ResourceManager.GetString("It_took_me_ages_of_searching_around_in_that_basement_to_remember_even_that_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It took me ages of wandering around in that basement to remember it for myself completely..
        /// </summary>
        internal static string It_took_me_ages_of_wandering_around_in_that_basement_to_remember_it_for_myself_completely {
            get {
                return ResourceManager.GetString("It_took_me_ages_of_wandering_around_in_that_basement_to_remember_it_for_myself_co" +
                        "mpletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was Cynthia..
        /// </summary>
        internal static string It_was_Cynthia {
            get {
                return ResourceManager.GetString("It_was_Cynthia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was just a wrench. It wasn&apos;t even that heavy..
        /// </summary>
        internal static string It_was_just_a_wrench_It_wasnt_even_that_heavy {
            get {
                return ResourceManager.GetString("It_was_just_a_wrench_It_wasnt_even_that_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was like all of a sudden I realized that this person I&apos;d been looking at all his life wasn&apos;t who I thought he was..
        /// </summary>
        internal static string It_was_like_all_of_a_sudden_I_realized_that_this_person_Id_been_looking_at_all_his_life_wasnt_who_I_thought_he_was {
            get {
                return ResourceManager.GetString("It_was_like_all_of_a_sudden_I_realized_that_this_person_Id_been_looking_at_all_hi" +
                        "s_life_wasnt_who_I_thought_he_was", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was them..
        /// </summary>
        internal static string It_was_them {
            get {
                return ResourceManager.GetString("It_was_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s just sickening..
        /// </summary>
        internal static string Its_just_sickening {
            get {
                return ResourceManager.GetString("Its_just_sickening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just... sitting. On the edge of his bed. Perfectly still. Just staring at the wall..
        /// </summary>
        internal static string Just_sitting_On_the_edge_of_his_bed_Perfectly_still_Just_staring_at_the_wall {
            get {
                return ResourceManager.GetString("Just_sitting_On_the_edge_of_his_bed_Perfectly_still_Just_staring_at_the_wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe go stay in a hotel for the night..
        /// </summary>
        internal static string Maybe_go_stay_in_a_hotel_for_the_night {
            get {
                return ResourceManager.GetString("Maybe_go_stay_in_a_hotel_for_the_night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My own family..
        /// </summary>
        internal static string My_own_family {
            get {
                return ResourceManager.GetString("My_own_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My own family... And all this time, I thought maybe they were hurt... But they&apos;d just run away..
        /// </summary>
        internal static string My_own_family_And_all_this_time_I_thought_maybe_they_were_hurt_But_theyd_just_run_away {
            get {
                return ResourceManager.GetString("My_own_family_And_all_this_time_I_thought_maybe_they_were_hurt_But_theyd_just_run" +
                        "_away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My own wife imprisoned me..
        /// </summary>
        internal static string My_own_wife_imprisoned_me {
            get {
                return ResourceManager.GetString("My_own_wife_imprisoned_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My wife... My son....
        /// </summary>
        internal static string My_wife_My_son {
            get {
                return ResourceManager.GetString("My_wife_My_son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next thing I knew, Cynthia was looking up at him, and he was standing behind me, watching us both..
        /// </summary>
        internal static string Next_thing_I_knew_Cynthia_was_looking_up_at_him_and_he_was_standing_behind_me_watching_us_both {
            get {
                return ResourceManager.GetString("Next_thing_I_knew_Cynthia_was_looking_up_at_him_and_he_was_standing_behind_me_wat" +
                        "ching_us_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. No it&apos;s not. I asked her &quot;who? who did this?&quot;, and she kept crying and telling me to keep my voice down, and that&apos;s....
        /// </summary>
        internal static string No_No_its_not_I_asked_her_who_who_did_this__and_she_kept_crying_and_telling_me_to_keep_my_voice_down_and_thats {
            get {
                return ResourceManager.GetString("No_No_its_not_I_asked_her_who_who_did_this__and_she_kept_crying_and_telling_me_to" +
                        "_keep_my_voice_down_and_thats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, not really. But he didn&apos;t deny it either..
        /// </summary>
        internal static string No_not_really_But_he_didnt_deny_it_either {
            get {
                return ResourceManager.GetString("No_not_really_But_he_didnt_deny_it_either", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, we were past that. He was violent. I felt like I hardly even knew him anymore..
        /// </summary>
        internal static string No_we_were_past_that_He_was_violent_I_felt_like_I_hardly_even_knew_him_anymore {
            get {
                return ResourceManager.GetString("No_we_were_past_that_He_was_violent_I_felt_like_I_hardly_even_knew_him_anymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not even sad, or upset. Just surprised..
        /// </summary>
        internal static string Not_even_sad_or_upset_Just_surprised {
            get {
                return ResourceManager.GetString("Not_even_sad_or_upset_Just_surprised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not how it should have..
        /// </summary>
        internal static string Not_how_it_should_have {
            get {
                return ResourceManager.GetString("Not_how_it_should_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not really. It was like a monster had taken over..
        /// </summary>
        internal static string Not_really_It_was_like_a_monster_had_taken_over {
            get {
                return ResourceManager.GetString("Not_really_It_was_like_a_monster_had_taken_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh god, the sound was awful..
        /// </summary>
        internal static string Oh_god_the_sound_was_awful {
            get {
                return ResourceManager.GetString("Oh_god_the_sound_was_awful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or when I... when we looked at each other....
        /// </summary>
        internal static string Or_when_I_when_we_looked_at_each_other {
            get {
                return ResourceManager.GetString("Or_when_I_when_we_looked_at_each_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps we should end here? We can always pick up later..
        /// </summary>
        internal static string Perhaps_we_should_end_here_We_can_always_pick_up_later {
            get {
                return ResourceManager.GetString("Perhaps_we_should_end_here_We_can_always_pick_up_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychopathy is... very difficult to understand..
        /// </summary>
        internal static string Psychopathy_is_very_difficult_to_understand {
            get {
                return ResourceManager.GetString("Psychopathy_is_very_difficult_to_understand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She didn&apos;t want me to go up there. She said he had some kind of a weapon..
        /// </summary>
        internal static string She_didnt_want_me_to_go_up_there_She_said_he_had_some_kind_of_a_weapon {
            get {
                return ResourceManager.GetString("She_didnt_want_me_to_go_up_there_She_said_he_had_some_kind_of_a_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She kept muttering about how he was her baby, and she was sorry....
        /// </summary>
        internal static string She_kept_muttering_about_how_he_was_her_baby_and_she_was_sorry {
            get {
                return ResourceManager.GetString("She_kept_muttering_about_how_he_was_her_baby_and_she_was_sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She left me to die..
        /// </summary>
        internal static string She_left_me_to_die {
            get {
                return ResourceManager.GetString("She_left_me_to_die", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She must have left with him after he threw me in the basement..
        /// </summary>
        internal static string She_must_have_left_with_him_after_he_threw_me_in_the_basement {
            get {
                return ResourceManager.GetString("She_must_have_left_with_him_after_he_threw_me_in_the_basement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She never would have agreed. I knew she wouldn&apos;t have agreed..
        /// </summary>
        internal static string She_never_would_have_agreed_I_knew_she_wouldnt_have_agreed {
            get {
                return ResourceManager.GetString("She_never_would_have_agreed_I_knew_she_wouldnt_have_agreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She probably wanted to protect him..
        /// </summary>
        internal static string She_probably_wanted_to_protect_him {
            get {
                return ResourceManager.GetString("She_probably_wanted_to_protect_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She was willing to move for him. She didn&apos;t care how it made me feel. .
        /// </summary>
        internal static string She_was_willing_to_move_for_him_She_didnt_care_how_it_made_me_feel_ {
            get {
                return ResourceManager.GetString("She_was_willing_to_move_for_him_She_didnt_care_how_it_made_me_feel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She wasn&apos;t listening to common sense..
        /// </summary>
        internal static string She_wasnt_listening_to_common_sense {
            get {
                return ResourceManager.GetString("She_wasnt_listening_to_common_sense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She&apos;s always been so attached to him. He&apos;s her little boy. She obsesses over him..
        /// </summary>
        internal static string Shes_always_been_so_attached_to_him_Hes_her_little_boy_She_obsesses_over_him {
            get {
                return ResourceManager.GetString("Shes_always_been_so_attached_to_him_Hes_her_little_boy_She_obsesses_over_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So I just brought the bag to her downstairs and told her we were leaving. She was so beaten..
        /// </summary>
        internal static string So_I_just_brought_the_bag_to_her_downstairs_and_told_her_we_were_leaving_She_was_so_beaten {
            get {
                return ResourceManager.GetString("So_I_just_brought_the_bag_to_her_downstairs_and_told_her_we_were_leaving_She_was_" +
                        "so_beaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So I went back to our room and started packing for both of us..
        /// </summary>
        internal static string So_I_went_back_to_our_room_and_started_packing_for_both_of_us {
            get {
                return ResourceManager.GetString("So_I_went_back_to_our_room_and_started_packing_for_both_of_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So what did you do?.
        /// </summary>
        internal static string So_what_did_you_do {
            get {
                return ResourceManager.GetString("So_what_did_you_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So what did you do next?.
        /// </summary>
        internal static string So_what_did_you_do_next {
            get {
                return ResourceManager.GetString("So_what_did_you_do_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you attacked him?.
        /// </summary>
        internal static string So_you_attacked_him {
            get {
                return ResourceManager.GetString("So_you_attacked_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you tried to force her?.
        /// </summary>
        internal static string So_you_tried_to_force_her {
            get {
                return ResourceManager.GetString("So_you_tried_to_force_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son or not, he&apos;d become a stranger. I didn&apos;t know what I could have said or done..
        /// </summary>
        internal static string Son_or_not_hed_become_a_stranger_I_didnt_know_what_I_could_have_said_or_done {
            get {
                return ResourceManager.GetString("Son_or_not_hed_become_a_stranger_I_didnt_know_what_I_could_have_said_or_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me how you did it..
        /// </summary>
        internal static string Tell_me_how_you_did_it {
            get {
                return ResourceManager.GetString("Tell_me_how_you_did_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That he&apos;d threatened to kill us both with it if we bothered him. I told her I was just going to get some painkillers from our bedroom..
        /// </summary>
        internal static string That_hed_threatened_to_kill_us_both_with_it_if_we_bothered_him_I_told_her_I_was_just_going_to_get_some_painkillers_from_our_bedroom {
            get {
                return ResourceManager.GetString("That_hed_threatened_to_kill_us_both_with_it_if_we_bothered_him_I_told_her_I_was_j" +
                        "ust_going_to_get_some_painkillers_from_our_bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s all you remember? It was Cynthia?.
        /// </summary>
        internal static string Thats_all_you_remember_It_was_Cynthia {
            get {
                return ResourceManager.GetString("Thats_all_you_remember_It_was_Cynthia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s when you realized he was in the house with you..
        /// </summary>
        internal static string Thats_when_you_realized_he_was_in_the_house_with_you {
            get {
                return ResourceManager.GetString("Thats_when_you_realized_he_was_in_the_house_with_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last thing I remember is her screaming while he swung the wrench at my head..
        /// </summary>
        internal static string The_last_thing_I_remember_is_her_screaming_while_he_swung_the_wrench_at_my_head {
            get {
                return ResourceManager.GetString("The_last_thing_I_remember_is_her_screaming_while_he_swung_the_wrench_at_my_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last thing I remember was him raising it over his head, and it swinging towards me..
        /// </summary>
        internal static string The_last_thing_I_remember_was_him_raising_it_over_his_head_and_it_swinging_towards_me {
            get {
                return ResourceManager.GetString("The_last_thing_I_remember_was_him_raising_it_over_his_head_and_it_swinging_toward" +
                        "s_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next thing I knew I woke up in the basement..
        /// </summary>
        internal static string The_next_thing_I_knew_I_woke_up_in_the_basement {
            get {
                return ResourceManager.GetString("The_next_thing_I_knew_I_woke_up_in_the_basement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The way she kept making excuses for him... I knew the only way to save her would be to get her far away from him..
        /// </summary>
        internal static string The_way_she_kept_making_excuses_for_him_I_knew_the_only_way_to_save_her_would_be_to_get_her_far_away_from_him {
            get {
                return ResourceManager.GetString("The_way_she_kept_making_excuses_for_him_I_knew_the_only_way_to_save_her_would_be_" +
                        "to_get_her_far_away_from_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weapon Cynthia had mentioned..
        /// </summary>
        internal static string The_weapon_Cynthia_had_mentioned {
            get {
                return ResourceManager.GetString("The_weapon_Cynthia_had_mentioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then I thought maybe she was cheating on me again. That she&apos;d brought somebody home and they&apos;d attacked her..
        /// </summary>
        internal static string Then_I_thought_maybe_she_was_cheating_on_me_again_That_shed_brought_somebody_home_and_theyd_attacked_her {
            get {
                return ResourceManager.GetString("Then_I_thought_maybe_she_was_cheating_on_me_again_That_shed_brought_somebody_home" +
                        "_and_theyd_attacked_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then we could get him the help he needed..
        /// </summary>
        internal static string Then_we_could_get_him_the_help_he_needed {
            get {
                return ResourceManager.GetString("Then_we_could_get_him_the_help_he_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then we could put him in a hospital or something for a while. I didn&apos;t think, I never thought that....
        /// </summary>
        internal static string Then_we_could_put_him_in_a_hospital_or_something_for_a_while_I_didnt_think_I_never_thought_that {
            get {
                return ResourceManager.GetString("Then_we_could_put_him_in_a_hospital_or_something_for_a_while_I_didnt_think_I_neve" +
                        "r_thought_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no telling how much time we had before Landon realized something was happening..
        /// </summary>
        internal static string There_was_no_telling_how_much_time_we_had_before_Landon_realized_something_was_happening {
            get {
                return ResourceManager.GetString("There_was_no_telling_how_much_time_we_had_before_Landon_realized_something_was_ha" +
                        "ppening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was something in his lap, but I couldn&apos;t quite see it. I figured that was his weapon..
        /// </summary>
        internal static string There_was_something_in_his_lap_but_I_couldnt_quite_see_it_I_figured_that_was_his_weapon {
            get {
                return ResourceManager.GetString("There_was_something_in_his_lap_but_I_couldnt_quite_see_it_I_figured_that_was_his_" +
                        "weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There wasn&apos;t a trace of humanity left in him..
        /// </summary>
        internal static string There_wasnt_a_trace_of_humanity_left_in_him {
            get {
                return ResourceManager.GetString("There_wasnt_a_trace_of_humanity_left_in_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They hurt me..
        /// </summary>
        internal static string They_hurt_me {
            get {
                return ResourceManager.GetString("They_hurt_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see my son do that to his own mother, and feel nothing... It was painful..
        /// </summary>
        internal static string To_see_my_son_do_that_to_his_own_mother_and_feel_nothing_It_was_painful {
            get {
                return ResourceManager.GetString("To_see_my_son_do_that_to_his_own_mother_and_feel_nothing_It_was_painful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugh... I....
        /// </summary>
        internal static string Ugh_I {
            get {
                return ResourceManager.GetString("Ugh_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We gave up our lives for him. I switched jobs..
        /// </summary>
        internal static string We_gave_up_our_lives_for_him_I_switched_jobs {
            get {
                return ResourceManager.GetString("We_gave_up_our_lives_for_him_I_switched_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d been growing apart, and then to have her baby do something like that... Running off with him only made sense to her..
        /// </summary>
        internal static string Wed_been_growing_apart_and_then_to_have_her_baby_do_something_like_that_Running_off_with_him_only_made_sense_to_her {
            get {
                return ResourceManager.GetString("Wed_been_growing_apart_and_then_to_have_her_baby_do_something_like_that_Running_o" +
                        "ff_with_him_only_made_sense_to_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happened after he fell?.
        /// </summary>
        internal static string What_happened_after_he_fell {
            get {
                return ResourceManager.GetString("What_happened_after_he_fell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I woke up in that basement, I thought.... I thought maybe somebody had come in, or I had fallen down..
        /// </summary>
        internal static string When_I_woke_up_in_that_basement_I_thought_I_thought_maybe_somebody_had_come_in_or_I_had_fallen_down {
            get {
                return ResourceManager.GetString("When_I_woke_up_in_that_basement_I_thought_I_thought_maybe_somebody_had_come_in_or" +
                        "_I_had_fallen_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, I mean, I guess that&apos;s the truly scary part about all this, isn&apos;t it?.
        /// </summary>
        internal static string Yeah_I_mean_I_guess_thats_the_truly_scary_part_about_all_this_isnt_it {
            get {
                return ResourceManager.GetString("Yeah_I_mean_I_guess_thats_the_truly_scary_part_about_all_this_isnt_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, well, we&apos;ll see what the jury thinks about that..
        /// </summary>
        internal static string Yeah_well_well_see_what_the_jury_thinks_about_that {
            get {
                return ResourceManager.GetString("Yeah_well_well_see_what_the_jury_thinks_about_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes..
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, but not right away. It took him a second. Like he was thinking about it..
        /// </summary>
        internal static string Yes_but_not_right_away_It_took_him_a_second_Like_he_was_thinking_about_it {
            get {
                return ResourceManager.GetString("Yes_but_not_right_away_It_took_him_a_second_Like_he_was_thinking_about_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. I heard him blasting music from his room. He&apos;d just left her to bleed on the floor..
        /// </summary>
        internal static string Yes_I_heard_him_blasting_music_from_his_room_Hed_just_left_her_to_bleed_on_the_floor {
            get {
                return ResourceManager.GetString("Yes_I_heard_him_blasting_music_from_his_room_Hed_just_left_her_to_bleed_on_the_fl" +
                        "oor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t consult her first?.
        /// </summary>
        internal static string You_didnt_consult_her_first {
            get {
                return ResourceManager.GetString("You_didnt_consult_her_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t think you should confront him yourself?.
        /// </summary>
        internal static string You_didnt_think_you_should_confront_him_yourself {
            get {
                return ResourceManager.GetString("You_didnt_think_you_should_confront_him_yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to understand me, I didn&apos;t want to hurt him! I just needed him to drop whatever he had..
        /// </summary>
        internal static string You_have_to_understand_me_I_didnt_want_to_hurt_him_I_just_needed_him_to_drop_whatever_he_had {
            get {
                return ResourceManager.GetString("You_have_to_understand_me_I_didnt_want_to_hurt_him_I_just_needed_him_to_drop_what" +
                        "ever_he_had", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You killed her only son, Ryan. She was terrified..
        /// </summary>
        internal static string You_killed_her_only_son_Ryan_She_was_terrified {
            get {
                return ResourceManager.GetString("You_killed_her_only_son_Ryan_She_was_terrified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;d never have known what he&apos;d just done. To his own mother..
        /// </summary>
        internal static string Youd_never_have_known_what_hed_just_done_To_his_own_mother {
            get {
                return ResourceManager.GetString("Youd_never_have_known_what_hed_just_done_To_his_own_mother", resourceCulture);
            }
        }
    }
}
