//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Session_7 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Session_7() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Resources_Session_7", typeof(Resources_Session_7).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lot more, huh? Does that mean... do you think I&apos;ll ever get out of here, Doctor?.
        /// </summary>
        internal static string A_lot_more_huh_Does_that_mean_do_you_think_Ill_ever_get_out_of_here_Doctor {
            get {
                return ResourceManager.GetString("A_lot_more_huh_Does_that_mean_do_you_think_Ill_ever_get_out_of_here_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, Ryan, I think we got a lot of important work done today..
        /// </summary>
        internal static string Alright_Ryan_I_think_we_got_a_lot_of_important_work_done_today {
            get {
                return ResourceManager.GetString("Alright_Ryan_I_think_we_got_a_lot_of_important_work_done_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And... and Cynthia?.
        /// </summary>
        internal static string And_and_Cynthia {
            get {
                return ResourceManager.GetString("And_and_Cynthia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And of course, Ryan, I&apos;m here for you..
        /// </summary>
        internal static string And_of_course_Ryan_Im_here_for_you {
            get {
                return ResourceManager.GetString("And_of_course_Ryan_Im_here_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And perhaps that&apos;s true..
        /// </summary>
        internal static string And_perhaps_thats_true {
            get {
                return ResourceManager.GetString("And_perhaps_thats_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And she was very scared, this time around. Who knows?.
        /// </summary>
        internal static string And_she_was_very_scared_this_time_around_Who_knows {
            get {
                return ResourceManager.GetString("And_she_was_very_scared_this_time_around_Who_knows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And what do you think will happen to Cynthia?.
        /// </summary>
        internal static string And_what_do_you_think_will_happen_to_Cynthia {
            get {
                return ResourceManager.GetString("And_what_do_you_think_will_happen_to_Cynthia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And you will. But I think that&apos;s time for today, Ryan. Same time next week?.
        /// </summary>
        internal static string And_you_will_But_I_think_thats_time_for_today_Ryan_Same_time_next_week {
            get {
                return ResourceManager.GetString("And_you_will_But_I_think_thats_time_for_today_Ryan_Same_time_next_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besides, it&apos;ll be a while before you can reach out to Landon at all, considering he&apos;s in a separate hospital..
        /// </summary>
        internal static string Besides_itll_be_a_while_before_you_can_reach_out_to_Landon_at_all_considering_hes_in_a_separate_hospital {
            get {
                return ResourceManager.GetString("Besides_itll_be_a_while_before_you_can_reach_out_to_Landon_at_all_considering_hes" +
                        "_in_a_separate_hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Testing.
        /// </summary>
        internal static string BetaTesting {
            get {
                return ResourceManager.GetString("BetaTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But seeing how traumatized you were after all of this, and for me personally, knowing your very unhealthy relationships with Landon and Cynthia....
        /// </summary>
        internal static string But_seeing_how_traumatized_you_were_after_all_of_this_and_for_me_personally_knowing_your_very_unhealthy_relationships_with_Landon_and_Cynthia {
            get {
                return ResourceManager.GetString("But_seeing_how_traumatized_you_were_after_all_of_this_and_for_me_personally_knowi" +
                        "ng_your_very_unhealthy_relationships_with_Landon_and_Cynthia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But you do think I&apos;ll come out okay?.
        /// </summary>
        internal static string But_you_do_think_Ill_come_out_okay {
            get {
                return ResourceManager.GetString("But_you_do_think_Ill_come_out_okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management, Coding.
        /// </summary>
        internal static string Coding {
            get {
                return ResourceManager.GetString("Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damian Potenzoni.
        /// </summary>
        internal static string Damian_Potenzoni {
            get {
                return ResourceManager.GetString("Damian_Potenzoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damian: I would like to thank my family and friends for the continuous support. Thanks to everyone involved in Session Seven for making me a part of the experience, you guys rock. Big thanks to my wife, without her, I couldn&apos;t make this possible. Love, D..
        /// </summary>
        internal static string DamianWouldLikeThankFamilyFriendsContinuousSupportThanksEveryoneInvolvedSessionSevenMakingPartExperienceGuysRockThanksWifeWithoutHerCouldnTMakeThisPossibleLove {
            get {
                return ResourceManager.GetString("DamianWouldLikeThankFamilyFriendsContinuousSupportThanksEveryoneInvolvedSessionSe" +
                        "venMakingPartExperienceGuysRockThanksWifeWithoutHerCouldnTMakeThisPossibleLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devoted to all point &amp; click adventure fans..
        /// </summary>
        internal static string Devoted_to_all_point__click_adventure_fans {
            get {
                return ResourceManager.GetString("Devoted_to_all_point__click_adventure_fans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think they&apos;ll make me speak to her in court?.
        /// </summary>
        internal static string Do_you_think_theyll_make_me_speak_to_her_in_court {
            get {
                return ResourceManager.GetString("Do_you_think_theyll_make_me_speak_to_her_in_court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you think they&apos;ll make me talk to her?.
        /// </summary>
        internal static string Do_you_think_theyll_make_me_talk_to_her {
            get {
                return ResourceManager.GetString("Do_you_think_theyll_make_me_talk_to_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy your freedom..
        /// </summary>
        internal static string Enjoy_your_freedom {
            get {
                return ResourceManager.GetString("Enjoy_your_freedom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especially seeing the traumatized, admittedly manic state you were in when you first arrived..
        /// </summary>
        internal static string Especially_seeing_the_traumatized_admittedly_manic_state_you_were_in_when_you_first_arrived {
            get {
                return ResourceManager.GetString("Especially_seeing_the_traumatized_admittedly_manic_state_you_were_in_when_you_fir" +
                        "st_arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He doesn&apos;t know me like you do, either. It&apos;s hard enough to tell this story once, nevermind a second time..
        /// </summary>
        internal static string He_doesnt_know_me_like_you_do_either_Its_hard_enough_to_tell_this_story_once_nevermind_a_second_time {
            get {
                return ResourceManager.GetString("He_doesnt_know_me_like_you_do_either_Its_hard_enough_to_tell_this_story_once_neve" +
                        "rmind_a_second_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He won&apos;t be allowed visitors for quite some time..
        /// </summary>
        internal static string He_wont_be_allowed_visitors_for_quite_some_time {
            get {
                return ResourceManager.GetString("He_wont_be_allowed_visitors_for_quite_some_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I appreciate you opening up to me as much as you have. I understand this hasn&apos;t been easy for you..
        /// </summary>
        internal static string I_appreciate_you_opening_up_to_me_as_much_as_you_have_I_understand_this_hasnt_been_easy_for_you {
            get {
                return ResourceManager.GetString("I_appreciate_you_opening_up_to_me_as_much_as_you_have_I_understand_this_hasnt_bee" +
                        "n_easy_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I assume that&apos;s why you&apos;re here, right?.
        /// </summary>
        internal static string I_assume_thats_why_youre_here_right {
            get {
                return ResourceManager.GetString("I_assume_thats_why_youre_here_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I believe this will be alright in the end..
        /// </summary>
        internal static string I_believe_this_will_be_alright_in_the_end {
            get {
                return ResourceManager.GetString("I_believe_this_will_be_alright_in_the_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess so. I&apos;ll just be glad when I can put this all behind me..
        /// </summary>
        internal static string I_guess_so_Ill_just_be_glad_when_I_can_put_this_all_behind_me {
            get {
                return ResourceManager.GetString("I_guess_so_Ill_just_be_glad_when_I_can_put_this_all_behind_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have hope for you still, Ryan, I really do..
        /// </summary>
        internal static string I_have_hope_for_you_still_Ryan_I_really_do {
            get {
                return ResourceManager.GetString("I_have_hope_for_you_still_Ryan_I_really_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just... I hope it will be enough..
        /// </summary>
        internal static string I_just_I_hope_it_will_be_enough {
            get {
                return ResourceManager.GetString("I_just_I_hope_it_will_be_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I mean, even after she cheated you felt like you could never trust her again, right?.
        /// </summary>
        internal static string I_mean_even_after_she_cheated_you_felt_like_you_could_never_trust_her_again_right {
            get {
                return ResourceManager.GetString("I_mean_even_after_she_cheated_you_felt_like_you_could_never_trust_her_again_right" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see. Do you think... do you think I&apos;ll have to talk to her?.
        /// </summary>
        internal static string I_see_Do_you_think_do_you_think_Ill_have_to_talk_to_her {
            get {
                return ResourceManager.GetString("I_see_Do_you_think_do_you_think_Ill_have_to_talk_to_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think all we can do is hope for the best..
        /// </summary>
        internal static string I_think_all_we_can_do_is_hope_for_the_best {
            get {
                return ResourceManager.GetString("I_think_all_we_can_do_is_hope_for_the_best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think it&apos;s likely she&apos;ll claim she was forced by her abusive son..
        /// </summary>
        internal static string I_think_its_likely_shell_claim_she_was_forced_by_her_abusive_son {
            get {
                return ResourceManager.GetString("I_think_its_likely_shell_claim_she_was_forced_by_her_abusive_son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to thank you again for opening up to me..
        /// </summary>
        internal static string I_want_to_thank_you_again_for_opening_up_to_me {
            get {
                return ResourceManager.GetString("I_want_to_thank_you_again_for_opening_up_to_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d suggest just keeping him off your mind as much as possible until then..
        /// </summary>
        internal static string Id_suggest_just_keeping_him_off_your_mind_as_much_as_possible_until_then {
            get {
                return ResourceManager.GetString("Id_suggest_just_keeping_him_off_your_mind_as_much_as_possible_until_then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If anything, this is the end of a very difficult chapter of your life. Things can only get better for you now..
        /// </summary>
        internal static string If_anything_this_is_the_end_of_a_very_difficult_chapter_of_your_life_Things_can_only_get_better_for_you_now {
            get {
                return ResourceManager.GetString("If_anything_this_is_the_end_of_a_very_difficult_chapter_of_your_life_Things_can_o" +
                        "nly_get_better_for_you_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll see you tomorrow..
        /// </summary>
        internal static string Ill_see_you_tomorrow {
            get {
                return ResourceManager.GetString("Ill_see_you_tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m glad you&apos;ve opened up to me so much about what happened..
        /// </summary>
        internal static string Im_glad_youve_opened_up_to_me_so_much_about_what_happened {
            get {
                return ResourceManager.GetString("Im_glad_youve_opened_up_to_me_so_much_about_what_happened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry it&apos;s come to this..
        /// </summary>
        internal static string Im_sorry_its_come_to_this {
            get {
                return ResourceManager.GetString("Im_sorry_its_come_to_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is important that you came clean. I think with this testimony we can prove that this was a big misunderstanding..
        /// </summary>
        internal static string It_is_important_that_you_came_clean_I_think_with_this_testimony_we_can_prove_that_this_was_a_big_misunderstanding {
            get {
                return ResourceManager.GetString("It_is_important_that_you_came_clean_I_think_with_this_testimony_we_can_prove_that" +
                        "_this_was_a_big_misunderstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was good to see a familiar face. The person they normally send me to....
        /// </summary>
        internal static string It_was_good_to_see_a_familiar_face_The_person_they_normally_send_me_to {
            get {
                return ResourceManager.GetString("It_was_good_to_see_a_familiar_face_The_person_they_normally_send_me_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s going to be a long journey for you. I can help you make the best of it, but as for your freedom....
        /// </summary>
        internal static string Its_going_to_be_a_long_journey_for_you_I_can_help_you_make_the_best_of_it_but_as_for_your_freedom {
            get {
                return ResourceManager.GetString("Its_going_to_be_a_long_journey_for_you_I_can_help_you_make_the_best_of_it_but_as_" +
                        "for_your_freedom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Landon who has to face the real consequences from this. They&apos;ll be putting him away any day now..
        /// </summary>
        internal static string Its_Landon_who_has_to_face_the_real_consequences_from_this_Theyll_be_putting_him_away_any_day_now {
            get {
                return ResourceManager.GetString("Its_Landon_who_has_to_face_the_real_consequences_from_this_Theyll_be_putting_him_" +
                        "away_any_day_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not as if you&apos;ve really hurt anyone..
        /// </summary>
        internal static string Its_not_as_if_youve_really_hurt_anyone {
            get {
                return ResourceManager.GetString("Its_not_as_if_youve_really_hurt_anyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...it&apos;s probably for the best that you get this time to really heal and reflect on yourself..
        /// </summary>
        internal static string its_probably_for_the_best_that_you_get_this_time_to_really_heal_and_reflect_on_yourself {
            get {
                return ResourceManager.GetString("its_probably_for_the_best_that_you_get_this_time_to_really_heal_and_reflect_on_yo" +
                        "urself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve been seeing you for nearly a year at this point. It wouldn&apos;t make sense to stop now..
        /// </summary>
        internal static string Ive_been_seeing_you_for_nearly_a_year_at_this_point_It_wouldnt_make_sense_to_stop_now {
            get {
                return ResourceManager.GetString("Ive_been_seeing_you_for_nearly_a_year_at_this_point_It_wouldnt_make_sense_to_stop" +
                        "_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jennifer Jussel.
        /// </summary>
        internal static string Jennifer_Jussel {
            get {
                return ResourceManager.GetString("Jennifer_Jussel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jennifer: Thanks to my family and friends for their unending support, and to the Session Seven team for making this dream a reality. And thanks to the player, too! None of this is possible without you..
        /// </summary>
        internal static string JenniferThanksFamilyFriendsTheirUnendingSupportSessionSevenTeamMakingThisDreamRealityThanksPlayerTooNoneThisPossibleWithoutYou {
            get {
                return ResourceManager.GetString("JenniferThanksFamilyFriendsTheirUnendingSupportSessionSevenTeamMakingThisDreamRea" +
                        "lityThanksPlayerTooNoneThisPossibleWithoutYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeremy Carver &amp; Jonas Jelli.
        /// </summary>
        internal static string Jeremy_Carver__Jonas_Jelli {
            get {
                return ResourceManager.GetString("Jeremy_Carver__Jonas_Jelli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeremy: Amanda &amp; Christian Carver, Maria Smith, Pierre Bezuidenhout, Dawid Frederik Strauss.
        /// </summary>
        internal static string JeremyAmandaChristianCarverMariaSmithPierreBezuidenhoutDawidFrederikStrauss {
            get {
                return ResourceManager.GetString("JeremyAmandaChristianCarverMariaSmithPierreBezuidenhoutDawidFrederikStrauss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jonas Jelli.
        /// </summary>
        internal static string Jonas_Jelli {
            get {
                return ResourceManager.GetString("Jonas_Jelli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jonas: My wife, family and friends and everybody contributing to making this game. You are outstanding!.
        /// </summary>
        internal static string JonasWifeFamilyFriendsEverybodyContributingMakingThisGame {
            get {
                return ResourceManager.GetString("JonasWifeFamilyFriendsEverybodyContributingMakingThisGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just be as honest with the jury as you were with me just now, and everything should be fine..
        /// </summary>
        internal static string Just_be_as_honest_with_the_jury_as_you_were_with_me_just_now_and_everything_should_be_fine {
            get {
                return ResourceManager.GetString("Just_be_as_honest_with_the_jury_as_you_were_with_me_just_now_and_everything_shoul" +
                        "d_be_fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laura Hubbes, Simon Tschirner, Stefan Dienst, Tanja Dienst, Thorsten Kraemer, Elanarae.
        /// </summary>
        internal static string LauraHubbesSimonTschirnerStefanDienstTanjaDienstThorstenKraemer {
            get {
                return ResourceManager.GetString("LauraHubbesSimonTschirnerStefanDienstTanjaDienstThorstenKraemer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaciejKubiszewski_ {
            get {
                return ResourceManager.GetString("MaciejKubiszewski ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe talking to her again, with all of the truth laid out now, wouldn&apos;t be such a bad thing..
        /// </summary>
        internal static string Maybe_talking_to_her_again_with_all_of_the_truth_laid_out_now_wouldnt_be_such_a_bad_thing {
            get {
                return ResourceManager.GetString("Maybe_talking_to_her_again_with_all_of_the_truth_laid_out_now_wouldnt_be_such_a_b" +
                        "ad_thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, especially not now. It&apos;s very important that you&apos;re talking to someone as you go through this process..
        /// </summary>
        internal static string No_especially_not_now_Its_very_important_that_youre_talking_to_someone_as_you_go_through_this_process {
            get {
                return ResourceManager.GetString("No_especially_not_now_Its_very_important_that_youre_talking_to_someone_as_you_go_" +
                        "through_this_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course I do. I&apos;ve seen you go through quite a lot, but I&apos;ve also seen you pull through it with grace..
        /// </summary>
        internal static string Of_course_I_do_Ive_seen_you_go_through_quite_a_lot_but_Ive_also_seen_you_pull_through_it_with_grace {
            get {
                return ResourceManager.GetString("Of_course_I_do_Ive_seen_you_go_through_quite_a_lot_but_Ive_also_seen_you_pull_thr" +
                        "ough_it_with_grace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course. I think you&apos;ll be glad to hear I&apos;m taking over for him now..
        /// </summary>
        internal static string Of_course_I_think_youll_be_glad_to_hear_Im_taking_over_for_him_now {
            get {
                return ResourceManager.GetString("Of_course_I_think_youll_be_glad_to_hear_Im_taking_over_for_him_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course. Still, I have to admit, I was surprised to get this call..
        /// </summary>
        internal static string Of_course_Still_I_have_to_admit_I_was_surprised_to_get_this_call {
            get {
                return ResourceManager.GetString("Of_course_Still_I_have_to_admit_I_was_surprised_to_get_this_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, I think so. These places aren&apos;t meant for permanent residents, except for some extreme cases..
        /// </summary>
        internal static string Oh_I_think_so_These_places_arent_meant_for_permanent_residents_except_for_some_extreme_cases {
            get {
                return ResourceManager.GetString("Oh_I_think_so_These_places_arent_meant_for_permanent_residents_except_for_some_ex" +
                        "treme_cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Polish_Translation {
            get {
                return ResourceManager.GetString("Polish_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right, I&apos;ll see you next Tuesday..
        /// </summary>
        internal static string Right_Ill_see_you_next_Tuesday {
            get {
                return ResourceManager.GetString("Right_Ill_see_you_next_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryan, I must admit to you, things aren&apos;t looking good for you..
        /// </summary>
        internal static string Ryan_I_must_admit_to_you_things_arent_looking_good_for_you {
            get {
                return ResourceManager.GetString("Ryan_I_must_admit_to_you_things_arent_looking_good_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-defense or not, it&apos;s possible you&apos;ll always be seen as a threat to society..
        /// </summary>
        internal static string Selfdefense_or_not_its_possible_youll_always_be_seen_as_a_threat_to_society {
            get {
                return ResourceManager.GetString("Selfdefense_or_not_its_possible_youll_always_be_seen_as_a_threat_to_society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She&apos;s in just about the same boat as you..
        /// </summary>
        internal static string Shes_in_just_about_the_same_boat_as_you {
            get {
                return ResourceManager.GetString("Shes_in_just_about_the_same_boat_as_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So... for your sake, I hope they don&apos;t..
        /// </summary>
        internal static string So_for_your_sake_I_hope_they_dont {
            get {
                return ResourceManager.GetString("So_for_your_sake_I_hope_they_dont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks.
        /// </summary>
        internal static string SpecialThanks {
            get {
                return ResourceManager.GetString("SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still... it&apos;s important that you came clean. I&apos;ll do everything I can to help you with my testimony..
        /// </summary>
        internal static string Still_its_important_that_you_came_clean_Ill_do_everything_I_can_to_help_you_with_my_testimony {
            get {
                return ResourceManager.GetString("Still_its_important_that_you_came_clean_Ill_do_everything_I_can_to_help_you_with_" +
                        "my_testimony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure. And, uh, Ryan?.
        /// </summary>
        internal static string Sure_And_uh_Ryan {
            get {
                return ResourceManager.GetString("Sure_And_uh_Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for playing!.
        /// </summary>
        internal static string Thank_you_for_playing {
            get {
                return ResourceManager.GetString("Thank_you_for_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string thanks {
            get {
                return ResourceManager.GetString("thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, Doc..
        /// </summary>
        internal static string Thanks_Doc {
            get {
                return ResourceManager.GetString("Thanks_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s all for today, Ryan. Your handler will take you back to your room..
        /// </summary>
        internal static string Thats_all_for_today_Ryan_Your_handler_will_take_you_back_to_your_room {
            get {
                return ResourceManager.GetString("Thats_all_for_today_Ryan_Your_handler_will_take_you_back_to_your_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial hasn&apos;t happened yet. I still have a chance..
        /// </summary>
        internal static string The_trial_hasnt_happened_yet_I_still_have_a_chance {
            get {
                return ResourceManager.GetString("The_trial_hasnt_happened_yet_I_still_have_a_chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, it&apos;s likely she&apos;ll plead that she was forced. You know, that she was fearing for her life, and that&apos;s why she helped Landon over you..
        /// </summary>
        internal static string Then_its_likely_shell_plead_that_she_was_forced_You_know_that_she_was_fearing_for_her_life_and_thats_why_she_helped_Landon_over_you {
            get {
                return ResourceManager.GetString("Then_its_likely_shell_plead_that_she_was_forced_You_know_that_she_was_fearing_for" +
                        "_her_life_and_thats_why_she_helped_Landon_over_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, maybe later, you can tackle that problem as it comes..
        /// </summary>
        internal static string Then_maybe_later_you_can_tackle_that_problem_as_it_comes {
            get {
                return ResourceManager.GetString("Then_maybe_later_you_can_tackle_that_problem_as_it_comes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a chance she&apos;ll be released because she was technically a victim of domestic abuse but, yes, she&apos;ll also have to stand trial..
        /// </summary>
        internal static string Theres_a_chance_shell_be_released_because_she_was_technically_a_victim_of_domestic_abuse_but_yes_shell_also_have_to_stand_trial {
            get {
                return ResourceManager.GetString("Theres_a_chance_shell_be_released_because_she_was_technically_a_victim_of_domesti" +
                        "c_abuse_but_yes_shell_also_have_to_stand_trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, after her adultery issue you still wanted to make things work, right?.
        /// </summary>
        internal static string Well_after_her_adultery_issue_you_still_wanted_to_make_things_work_right {
            get {
                return ResourceManager.GetString("Well_after_her_adultery_issue_you_still_wanted_to_make_things_work_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll be seeing a lot more of each other, Ryan..
        /// </summary>
        internal static string Well_be_seeing_a_lot_more_of_each_other_Ryan {
            get {
                return ResourceManager.GetString("Well_be_seeing_a_lot_more_of_each_other_Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, for now, she&apos;s awaiting trial..
        /// </summary>
        internal static string Well_for_now_shes_awaiting_trial {
            get {
                return ResourceManager.GetString("Well_for_now_shes_awaiting_trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, I&apos;d like to say I&apos;m here simply to support you, but yes....
        /// </summary>
        internal static string Well_Id_like_to_say_Im_here_simply_to_support_you_but_yes {
            get {
                return ResourceManager.GetString("Well_Id_like_to_say_Im_here_simply_to_support_you_but_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, I&apos;d say we got a lot done today, Ryan..
        /// </summary>
        internal static string Well_Id_say_we_got_a_lot_done_today_Ryan {
            get {
                return ResourceManager.GetString("Well_Id_say_we_got_a_lot_done_today_Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, it&apos;ll be some time before he&apos;s allowed visitors in the mental ward..
        /// </summary>
        internal static string Well_itll_be_some_time_before_hes_allowed_visitors_in_the_mental_ward {
            get {
                return ResourceManager.GetString("Well_itll_be_some_time_before_hes_allowed_visitors_in_the_mental_ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, it&apos;s almost the end... What about Cynthia?.
        /// </summary>
        internal static string Well_its_almost_the_end_What_about_Cynthia {
            get {
                return ResourceManager.GetString("Well_its_almost_the_end_What_about_Cynthia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, Ryan, I have to be honest with you... it doesn&apos;t look good..
        /// </summary>
        internal static string Well_Ryan_I_have_to_be_honest_with_you_it_doesnt_look_good {
            get {
                return ResourceManager.GetString("Well_Ryan_I_have_to_be_honest_with_you_it_doesnt_look_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve gotten a lot of good work done today, Ryan..
        /// </summary>
        internal static string Weve_gotten_a_lot_of_good_work_done_today_Ryan {
            get {
                return ResourceManager.GetString("Weve_gotten_a_lot_of_good_work_done_today_Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether that will be enough to convince the judges of her innocence, I can&apos;t say..
        /// </summary>
        internal static string Whether_that_will_be_enough_to_convince_the_judges_of_her_innocence_I_cant_say {
            get {
                return ResourceManager.GetString("Whether_that_will_be_enough_to_convince_the_judges_of_her_innocence_I_cant_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        internal static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.sessionseven.com.
        /// </summary>
        internal static string wwwsessionsevencom {
            get {
                return ResourceManager.GetString("wwwsessionsevencom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah... and Landon? I&apos;m still trying to figure out what to do with him..
        /// </summary>
        internal static string Yeah_and_Landon_Im_still_trying_to_figure_out_what_to_do_with_him {
            get {
                return ResourceManager.GetString("Yeah_and_Landon_Im_still_trying_to_figure_out_what_to_do_with_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, well, it was good just to see a familiar face. It&apos;s easier to talk to somebody who already knows my history..
        /// </summary>
        internal static string Yeah_well_it_was_good_just_to_see_a_familiar_face_Its_easier_to_talk_to_somebody_who_already_knows_my_history {
            get {
                return ResourceManager.GetString("Yeah_well_it_was_good_just_to_see_a_familiar_face_Its_easier_to_talk_to_somebody_" +
                        "who_already_knows_my_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Doctor?.
        /// </summary>
        internal static string Yes_Doctor {
            get {
                return ResourceManager.GetString("Yes_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;ve heard Dr. Raj can be a bit... harsh..
        /// </summary>
        internal static string Yes_Ive_heard_Dr_Raj_can_be_a_bit_harsh {
            get {
                return ResourceManager.GetString("Yes_Ive_heard_Dr_Raj_can_be_a_bit_harsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have quite a few good memories with her..
        /// </summary>
        internal static string You_have_quite_a_few_good_memories_with_her {
            get {
                return ResourceManager.GetString("You_have_quite_a_few_good_memories_with_her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only have been trying to help your family, but this is going to be difficult to explain away..
        /// </summary>
        internal static string You_may_only_have_been_trying_to_help_your_family_but_this_is_going_to_be_difficult_to_explain_away {
            get {
                return ResourceManager.GetString("You_may_only_have_been_trying_to_help_your_family_but_this_is_going_to_be_difficu" +
                        "lt_to_explain_away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You mean her trial? Yes, there&apos;s no telling how that will go..
        /// </summary>
        internal static string You_mean_her_trial_Yes_theres_no_telling_how_that_will_go {
            get {
                return ResourceManager.GetString("You_mean_her_trial_Yes_theres_no_telling_how_that_will_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your son is dead by your hands..
        /// </summary>
        internal static string Your_son_is_dead_by_your_hands {
            get {
                return ResourceManager.GetString("Your_son_is_dead_by_your_hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re a good man. You can come back from this..
        /// </summary>
        internal static string Youre_a_good_man_You_can_come_back_from_this {
            get {
                return ResourceManager.GetString("Youre_a_good_man_You_can_come_back_from_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been through a lot. I just hope we can work through it all and get you feeling better soon..
        /// </summary>
        internal static string Youve_been_through_a_lot_I_just_hope_we_can_work_through_it_all_and_get_you_feeling_better_soon {
            get {
                return ResourceManager.GetString("Youve_been_through_a_lot_I_just_hope_we_can_work_through_it_all_and_get_you_feeli" +
                        "ng_better_soon", resourceCulture);
            }
        }
    }
}
