//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionSeven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_Session_5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Session_5() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionSeven.Properties.Resources_Session_5", typeof(Resources_Session_5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a while, he seemed to get bored. He got up and left. After I was sure he wasn&apos;t going to come back, I got up so I could get a closer look at his project..
        /// </summary>
        internal static string After_a_while_he_seemed_to_get_bored_He_got_up_and_left_After_I_was_sure_he_wasnt_going_to_come_back_I_got_up_so_I_could_get_a_closer_look_at_his_project {
            get {
                return ResourceManager.GetString("After_a_while_he_seemed_to_get_bored_He_got_up_and_left_After_I_was_sure_he_wasnt" +
                        "_going_to_come_back_I_got_up_so_I_could_get_a_closer_look_at_his_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All he did was stare. Stare or cry when he was hungry. It was unnerving..
        /// </summary>
        internal static string All_he_did_was_stare_Stare_or_cry_when_he_was_hungry_It_was_unnerving {
            get {
                return ResourceManager.GetString("All_he_did_was_stare_Stare_or_cry_when_he_was_hungry_It_was_unnerving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and I realized....
        /// </summary>
        internal static string and_I_realized {
            get {
                return ResourceManager.GetString("and_I_realized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And it&apos;s not that I don&apos;t trust... well, your people, but if his own father doesn&apos;t know him, how can a psychiatrist?.
        /// </summary>
        internal static string And_its_not_that_I_dont_trust_well_your_people_but_if_his_own_father_doesnt_know_him_how_can_a_psychiatrist {
            get {
                return ResourceManager.GetString("And_its_not_that_I_dont_trust_well_your_people_but_if_his_own_father_doesnt_know_" +
                        "him_how_can_a_psychiatrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Landon cried?.
        /// </summary>
        internal static string And_Landon_cried {
            get {
                return ResourceManager.GetString("And_Landon_cried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Landon still hasn&apos;t said a thing. Just that he had it coming. He didn&apos;t even seem sorry about it..
        /// </summary>
        internal static string And_Landon_still_hasnt_said_a_thing_Just_that_he_had_it_coming_He_didnt_even_seem_sorry_about_it {
            get {
                return ResourceManager.GetString("And_Landon_still_hasnt_said_a_thing_Just_that_he_had_it_coming_He_didnt_even_seem" +
                        "_sorry_about_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And then?.
        /// </summary>
        internal static string And_then {
            get {
                return ResourceManager.GetString("And_then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And, to be honest with you....
        /// </summary>
        internal static string And_to_be_honest_with_you {
            get {
                return ResourceManager.GetString("And_to_be_honest_with_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyways, I opened up one of the cabinets higher up, trying to find a good frying pan..
        /// </summary>
        internal static string Anyways_I_opened_up_one_of_the_cabinets_higher_up_trying_to_find_a_good_frying_pan {
            get {
                return ResourceManager.GetString("Anyways_I_opened_up_one_of_the_cabinets_higher_up_trying_to_find_a_good_frying_pa" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asperger&apos;s can present itself in many different ways, Ryan..
        /// </summary>
        internal static string Aspergers_can_present_itself_in_many_different_ways_Ryan {
            get {
                return ResourceManager.GetString("Aspergers_can_present_itself_in_many_different_ways_Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But he never said anything to you about it?.
        /// </summary>
        internal static string But_he_never_said_anything_to_you_about_it {
            get {
                return ResourceManager.GetString("But_he_never_said_anything_to_you_about_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But it&apos;s the kind of thing I think a father should know about..
        /// </summary>
        internal static string But_its_the_kind_of_thing_I_think_a_father_should_know_about {
            get {
                return ResourceManager.GetString("But_its_the_kind_of_thing_I_think_a_father_should_know_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But then....
        /// </summary>
        internal static string But_then {
            get {
                return ResourceManager.GetString("But_then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But what was he doing with them?.
        /// </summary>
        internal static string But_what_was_he_doing_with_them {
            get {
                return ResourceManager.GetString("But_what_was_he_doing_with_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cynthia was just out getting the mail when it happened. I was in the kitchen, getting breakfast ready. I was going to make pancakes..
        /// </summary>
        internal static string Cynthia_was_just_out_getting_the_mail_when_it_happened_I_was_in_the_kitchen_getting_breakfast_ready_I_was_going_to_make_pancakes {
            get {
                return ResourceManager.GetString("Cynthia_was_just_out_getting_the_mail_when_it_happened_I_was_in_the_kitchen_getti" +
                        "ng_breakfast_ready_I_was_going_to_make_pancakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found what, Ryan?.
        /// </summary>
        internal static string Found_what_Ryan {
            get {
                return ResourceManager.GetString("Found_what_Ryan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From far away, it looked like... like maybe dolls or something? Like he was playing with dolls or stuffed animals?.
        /// </summary>
        internal static string From_far_away_it_looked_like_like_maybe_dolls_or_something__Like_he_was_playing_with_dolls_or_stuffed_animals {
            get {
                return ResourceManager.GetString("From_far_away_it_looked_like_like_maybe_dolls_or_something__Like_he_was_playing_w" +
                        "ith_dolls_or_stuffed_animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He isn&apos;t interested in bonding..
        /// </summary>
        internal static string He_isnt_interested_in_bonding {
            get {
                return ResourceManager.GetString("He_isnt_interested_in_bonding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He stopped. That same day that I went after him, he quit going out on the weekends..
        /// </summary>
        internal static string He_stopped_That_same_day_that_I_went_after_him_he_quit_going_out_on_the_weekends {
            get {
                return ResourceManager.GetString("He_stopped_That_same_day_that_I_went_after_him_he_quit_going_out_on_the_weekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He walked for about twenty minutes back into the forest, and then he stopped at this little clearing in the trees..
        /// </summary>
        internal static string He_walked_for_about_twenty_minutes_back_into_the_forest_and_then_he_stopped_at_this_little_clearing_in_the_trees {
            get {
                return ResourceManager.GetString("He_walked_for_about_twenty_minutes_back_into_the_forest_and_then_he_stopped_at_th" +
                        "is_little_clearing_in_the_trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was giggling. It was the first time I&apos;d ever seen him smile, or laugh. And he just kept going..
        /// </summary>
        internal static string He_was_giggling_It_was_the_first_time_Id_ever_seen_him_smile_or_laugh_And_he_just_kept_going {
            get {
                return ResourceManager.GetString("He_was_giggling_It_was_the_first_time_Id_ever_seen_him_smile_or_laugh_And_he_just" +
                        "_kept_going", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was making a funny sound and fidgeting a little bit, and for a second I thought maybe he&apos;d somehow been hurt or was getting ready to cry, but no..
        /// </summary>
        internal static string He_was_making_a_funny_sound_and_fidgeting_a_little_bit_and_for_a_second_I_thought_maybe_hed_somehow_been_hurt_or_was_getting_ready_to_cry_but_no {
            get {
                return ResourceManager.GetString("He_was_making_a_funny_sound_and_fidgeting_a_little_bit_and_for_a_second_I_thought" +
                        "_maybe_hed_somehow_been_hurt_or_was_getting_ready_to_cry_but_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He wasn&apos;t meeting anybody after all. He just seemed to be working away at something, like he was really focused..
        /// </summary>
        internal static string He_wasnt_meeting_anybody_after_all_He_just_seemed_to_be_working_away_at_something_like_he_was_really_focused {
            get {
                return ResourceManager.GetString("He_wasnt_meeting_anybody_after_all_He_just_seemed_to_be_working_away_at_something" +
                        "_like_he_was_really_focused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He wouldn&apos;t even tell me what those bullies were doing to him at school. Or who they were. He just said he needed to get away from them..
        /// </summary>
        internal static string He_wouldnt_even_tell_me_what_those_bullies_were_doing_to_him_at_school_Or_who_they_were_He_just_said_he_needed_to_get_away_from_them {
            get {
                return ResourceManager.GetString("He_wouldnt_even_tell_me_what_those_bullies_were_doing_to_him_at_school_Or_who_the" +
                        "y_were_He_just_said_he_needed_to_get_away_from_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He&apos;s just getting out of the hospital today. They thought he might have needed plastic surgery for his face..
        /// </summary>
        internal static string Hes_just_getting_out_of_the_hospital_today_They_thought_he_might_have_needed_plastic_surgery_for_his_face {
            get {
                return ResourceManager.GetString("Hes_just_getting_out_of_the_hospital_today_They_thought_he_might_have_needed_plas" +
                        "tic_surgery_for_his_face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How bad were his injuries, exactly?.
        /// </summary>
        internal static string How_bad_were_his_injuries_exactly {
            get {
                return ResourceManager.GetString("How_bad_were_his_injuries_exactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t quite reach the pan I wanted, so I set Landon down on the counter for just a minute and reached up..
        /// </summary>
        internal static string I_couldnt_quite_reach_the_pan_I_wanted_so_I_set_Landon_down_on_the_counter_for_just_a_minute_and_reached_up {
            get {
                return ResourceManager.GetString("I_couldnt_quite_reach_the_pan_I_wanted_so_I_set_Landon_down_on_the_counter_for_ju" +
                        "st_a_minute_and_reached_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t tell you. He had a bunch of sticks and sharpened rocks around, and he&apos;d pulled the guts out of some of the poor little creatures..
        /// </summary>
        internal static string I_couldnt_tell_you_He_had_a_bunch_of_sticks_and_sharpened_rocks_around_and_hed_pulled_the_guts_out_of_some_of_the_poor_little_creatures {
            get {
                return ResourceManager.GetString("I_couldnt_tell_you_He_had_a_bunch_of_sticks_and_sharpened_rocks_around_and_hed_pu" +
                        "lled_the_guts_out_of_some_of_the_poor_little_creatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that I really would have minded if that was what he was doing back there, because at least that would mean he&apos;s spending time with someone..
        /// </summary>
        internal static string I_dont_know_that_I_really_would_have_minded_if_that_was_what_he_was_doing_back_there_because_at_least_that_would_mean_hes_spending_time_with_someone {
            get {
                return ResourceManager.GetString("I_dont_know_that_I_really_would_have_minded_if_that_was_what_he_was_doing_back_th" +
                        "ere_because_at_least_that_would_mean_hes_spending_time_with_someone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt bad watching him, but I also didn&apos;t want to interrupt. So I just watched..
        /// </summary>
        internal static string I_felt_bad_watching_him_but_I_also_didnt_want_to_interrupt_So_I_just_watched {
            get {
                return ResourceManager.GetString("I_felt_bad_watching_him_but_I_also_didnt_want_to_interrupt_So_I_just_watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I had no idea what he was doing back there. I thought maybe he was meeting a girl, or maybe doing drugs with some friends I didn&apos;t know about..
        /// </summary>
        internal static string I_had_no_idea_what_he_was_doing_back_there_I_thought_maybe_he_was_meeting_a_girl_or_maybe_doing_drugs_with_some_friends_I_didnt_know_about {
            get {
                return ResourceManager.GetString("I_had_no_idea_what_he_was_doing_back_there_I_thought_maybe_he_was_meeting_a_girl_" +
                        "or_maybe_doing_drugs_with_some_friends_I_didnt_know_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I haven&apos;t been able to sleep quite the same since..
        /// </summary>
        internal static string I_havent_been_able_to_sleep_quite_the_same_since {
            get {
                return ResourceManager.GetString("I_havent_been_able_to_sleep_quite_the_same_since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hid behind one of the big oaks while he bent down over something..
        /// </summary>
        internal static string I_hid_behind_one_of_the_big_oaks_while_he_bent_down_over_something {
            get {
                return ResourceManager.GetString("I_hid_behind_one_of_the_big_oaks_while_he_bent_down_over_something", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hit the pan out of the way in time, but not before it broke two of my fingers..
        /// </summary>
        internal static string I_hit_the_pan_out_of_the_way_in_time_but_not_before_it_broke_two_of_my_fingers {
            get {
                return ResourceManager.GetString("I_hit_the_pan_out_of_the_way_in_time_but_not_before_it_broke_two_of_my_fingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just wanted to understand..
        /// </summary>
        internal static string I_just_wanted_to_understand {
            get {
                return ResourceManager.GetString("I_just_wanted_to_understand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know, I know. We should talk about him. We should..
        /// </summary>
        internal static string I_know_I_know_We_should_talk_about_him_We_should {
            get {
                return ResourceManager.GetString("I_know_I_know_We_should_talk_about_him_We_should", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know that, as a parent with mental illness, it can be difficult to handle when your child is also diagnosed..
        /// </summary>
        internal static string I_know_that_as_a_parent_with_mental_illness_it_can_be_difficult_to_handle_when_your_child_is_also_diagnosed {
            get {
                return ResourceManager.GetString("I_know_that_as_a_parent_with_mental_illness_it_can_be_difficult_to_handle_when_yo" +
                        "ur_child_is_also_diagnosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I mean... he&apos;s always been difficult to reach. Even when he was a baby..
        /// </summary>
        internal static string I_mean_hes_always_been_difficult_to_reach_Even_when_he_was_a_baby {
            get {
                return ResourceManager.GetString("I_mean_hes_always_been_difficult_to_reach_Even_when_he_was_a_baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I really don&apos;t think he&apos;s sick. Not like that..
        /// </summary>
        internal static string I_really_dont_think_hes_sick_Not_like_that {
            get {
                return ResourceManager.GetString("I_really_dont_think_hes_sick_Not_like_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I still don&apos;t know why... why he did what he did..
        /// </summary>
        internal static string I_still_dont_know_why_why_he_did_what_he_did {
            get {
                return ResourceManager.GetString("I_still_dont_know_why_why_he_did_what_he_did", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I&apos;m afraid of him..
        /// </summary>
        internal static string I_think_Im_afraid_of_him {
            get {
                return ResourceManager.GetString("I_think_Im_afraid_of_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think that&apos;s the most disturbing part about all of this for me, strangely enough..
        /// </summary>
        internal static string I_think_thats_the_most_disturbing_part_about_all_of_this_for_me_strangely_enough {
            get {
                return ResourceManager.GetString("I_think_thats_the_most_disturbing_part_about_all_of_this_for_me_strangely_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was the first one to ever see him smile..
        /// </summary>
        internal static string I_was_the_first_one_to_ever_see_him_smile {
            get {
                return ResourceManager.GetString("I_was_the_first_one_to_ever_see_him_smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I... You have to understand that he never talks to me. And after everything that&apos;s happened, with the bullying and the switching schools and the secrets....
        /// </summary>
        internal static string I_You_have_to_understand_that_he_never_talks_to_me_And_after_everything_thats_happened_with_the_bullying_and_the_switching_schools_and_the_secrets {
            get {
                return ResourceManager.GetString("I_You_have_to_understand_that_he_never_talks_to_me_And_after_everything_thats_hap" +
                        "pened_with_the_bullying_and_the_switching_schools_and_the_secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you really want to connect, you&apos;ll just need to try harder to reach out. Maybe he&apos;d like a trip to the movies? Or the park?.
        /// </summary>
        internal static string If_you_really_want_to_connect_youll_just_need_to_try_harder_to_reach_out_Maybe_hed_like_a_trip_to_the_movies_Or_the_park {
            get {
                return ResourceManager.GetString("If_you_really_want_to_connect_youll_just_need_to_try_harder_to_reach_out_Maybe_he" +
                        "d_like_a_trip_to_the_movies_Or_the_park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m always off at work, and his mother isn&apos;t the most accessible of people..
        /// </summary>
        internal static string Im_always_off_at_work_and_his_mother_isnt_the_most_accessible_of_people {
            get {
                return ResourceManager.GetString("Im_always_off_at_work_and_his_mother_isnt_the_most_accessible_of_people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m glad you think so too. We can start simple. How have things been since the diagnosis?.
        /// </summary>
        internal static string Im_glad_you_think_so_too_We_can_start_simple_How_have_things_been_since_the_diagnosis {
            get {
                return ResourceManager.GetString("Im_glad_you_think_so_too_We_can_start_simple_How_have_things_been_since_the_diagn" +
                        "osis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not 100% convinced that&apos;s changing schools, pumping him with pills, and starting all over, but if that&apos;s what his mother and his psychiatrist are saying, I guess that&apos;s for the best..
        /// </summary>
        internal static string Im_not_100_convinced_thats_changing_schools_pumping_him_with_pills_and_starting_all_over_but_if_thats_what_his_mother_and_his_psychiatrist_are_saying_I_guess_thats_for_the_best {
            get {
                return ResourceManager.GetString("Im_not_100_convinced_thats_changing_schools_pumping_him_with_pills_and_starting_a" +
                        "ll_over_but_if_thats_what_his_mother_and_his_psychiatrist_are_saying_I_guess_tha" +
                        "ts_for_the_best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m standing there, screaming in pain, and he&apos;s laughing. He thought it was hilarious..
        /// </summary>
        internal static string Im_standing_there_screaming_in_pain_and_hes_laughing_He_thought_it_was_hilarious {
            get {
                return ResourceManager.GetString("Im_standing_there_screaming_in_pain_and_hes_laughing_He_thought_it_was_hilarious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It made the most awful sound..
        /// </summary>
        internal static string It_made_the_most_awful_sound {
            get {
                return ResourceManager.GetString("It_made_the_most_awful_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was like he was examining them. Playing surgeon..
        /// </summary>
        internal static string It_was_like_he_was_examining_them_Playing_surgeon {
            get {
                return ResourceManager.GetString("It_was_like_he_was_examining_them_Playing_surgeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s good that you have his best interests at heart..
        /// </summary>
        internal static string Its_good_that_you_have_his_best_interests_at_heart {
            get {
                return ResourceManager.GetString("Its_good_that_you_have_his_best_interests_at_heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s hard not to feel guilty, you know? Like, maybe if I&apos;d done something differently....
        /// </summary>
        internal static string Its_hard_not_to_feel_guilty_you_know_Like_maybe_if_Id_done_something_differently {
            get {
                return ResourceManager.GetString("Its_hard_not_to_feel_guilty_you_know_Like_maybe_if_Id_done_something_differently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s... hard to explain. And I&apos;m not really proud of how I found it..
        /// </summary>
        internal static string Its_hard_to_explain_And_Im_not_really_proud_of_how_I_found_it {
            get {
                return ResourceManager.GetString("Its_hard_to_explain_And_Im_not_really_proud_of_how_I_found_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s like he knew he&apos;d been followed..
        /// </summary>
        internal static string Its_like_he_knew_hed_been_followed {
            get {
                return ResourceManager.GetString("Its_like_he_knew_hed_been_followed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s possible. Perhaps the antidepressants will help with that as well..
        /// </summary>
        internal static string Its_possible_Perhaps_the_antidepressants_will_help_with_that_as_well {
            get {
                return ResourceManager.GetString("Its_possible_Perhaps_the_antidepressants_will_help_with_that_as_well", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your first step to getting Landon help. Don&apos;t you think so?.
        /// </summary>
        internal static string Its_your_first_step_to_getting_Landon_help_Dont_you_think_so {
            get {
                return ResourceManager.GetString("Its_your_first_step_to_getting_Landon_help_Dont_you_think_so", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve always wanted what&apos;s best for Landon..
        /// </summary>
        internal static string Ive_always_wanted_whats_best_for_Landon {
            get {
                return ResourceManager.GetString("Ive_always_wanted_whats_best_for_Landon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve tried reaching out to him a few times, but he always goes off and hides in his room to play on his computer or whatever it is he does up there..
        /// </summary>
        internal static string Ive_tried_reaching_out_to_him_a_few_times_but_he_always_goes_off_and_hides_in_his_room_to_play_on_his_computer_or_whatever_it_is_he_does_up_there {
            get {
                return ResourceManager.GetString("Ive_tried_reaching_out_to_him_a_few_times_but_he_always_goes_off_and_hides_in_his" +
                        "_room_to_play_on_his_computer_or_whatever_it_is_he_does_up_there", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landon has always been troubled, as long as I can remember..
        /// </summary>
        internal static string Landon_has_always_been_troubled_as_long_as_I_can_remember {
            get {
                return ResourceManager.GetString("Landon_has_always_been_troubled_as_long_as_I_can_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many depressed people feel that socializing just isn&apos;t worth it, whether they&apos;re on the spectrum or not..
        /// </summary>
        internal static string Many_depressed_people_feel_that_socializing_just_isnt_worth_it_whether_theyre_on_the_spectrum_or_not {
            get {
                return ResourceManager.GetString("Many_depressed_people_feel_that_socializing_just_isnt_worth_it_whether_theyre_on_" +
                        "the_spectrum_or_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe, but I don&apos;t think so. I don&apos;t think she knew I&apos;d gone out..
        /// </summary>
        internal static string Maybe_but_I_dont_think_so_I_dont_think_she_knew_Id_gone_out {
            get {
                return ResourceManager.GetString("Maybe_but_I_dont_think_so_I_dont_think_she_knew_Id_gone_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe, but that doesn&apos;t mean you&apos;ve lost everything, Ryan. You can still make time for him now..
        /// </summary>
        internal static string Maybe_but_that_doesnt_mean_youve_lost_everything_Ryan_You_can_still_make_time_for_him_now {
            get {
                return ResourceManager.GetString("Maybe_but_that_doesnt_mean_youve_lost_everything_Ryan_You_can_still_make_time_for" +
                        "_him_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe if I&apos;d been there, he wouldn&apos;t be having such a rough time..
        /// </summary>
        internal static string Maybe_if_Id_been_there_he_wouldnt_be_having_such_a_rough_time {
            get {
                return ResourceManager.GetString("Maybe_if_Id_been_there_he_wouldnt_be_having_such_a_rough_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe... Who knows what he likes anymore..
        /// </summary>
        internal static string Maybe_Who_knows_what_he_likes_anymore {
            get {
                return ResourceManager.GetString("Maybe_Who_knows_what_he_likes_anymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe you were making a funny face?.
        /// </summary>
        internal static string Maybe_you_were_making_a_funny_face {
            get {
                return ResourceManager.GetString("Maybe_you_were_making_a_funny_face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental illness is like any other chronic disease. You can&apos;t have done anything to prevent it..
        /// </summary>
        internal static string Mental_illness_is_like_any_other_chronic_disease_You_cant_have_done_anything_to_prevent_it {
            get {
                return ResourceManager.GetString("Mental_illness_is_like_any_other_chronic_disease_You_cant_have_done_anything_to_p" +
                        "revent_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most babies, their first smile happens because they hear their mother&apos;s voice, or somebody makes a silly face at them..
        /// </summary>
        internal static string Most_babies_their_first_smile_happens_because_they_hear_their_mothers_voice_or_somebody_makes_a_silly_face_at_them {
            get {
                return ResourceManager.GetString("Most_babies_their_first_smile_happens_because_they_hear_their_mothers_voice_or_so" +
                        "mebody_makes_a_silly_face_at_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, never..
        /// </summary>
        internal static string No_never {
            get {
                return ResourceManager.GetString("No_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, no, it wasn&apos;t wonderful. It was... unsettling..
        /// </summary>
        internal static string No_no_it_wasnt_wonderful_It_was_unsettling {
            get {
                return ResourceManager.GetString("No_no_it_wasnt_wonderful_It_was_unsettling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, no, that&apos;s just it. Most babies would have started screaming the second the loud sounds started. But not Landon..
        /// </summary>
        internal static string No_no_thats_just_it_Most_babies_would_have_started_screaming_the_second_the_loud_sounds_started_But_not_Landon {
            get {
                return ResourceManager.GetString("No_no_thats_just_it_Most_babies_would_have_started_screaming_the_second_the_loud_" +
                        "sounds_started_But_not_Landon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Not dolls. Animals. Corpses. Bloody, open bodies of squirrels and rabbits, baking in the sun... I almost threw up..
        /// </summary>
        internal static string No_Not_dolls_Animals_Corpses_Bloody_open_bodies_of_squirrels_and_rabbits_baking_in_the_sun_I_almost_threw_up {
            get {
                return ResourceManager.GetString("No_Not_dolls_Animals_Corpses_Bloody_open_bodies_of_squirrels_and_rabbits_baking_i" +
                        "n_the_sun_I_almost_threw_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Landon..
        /// </summary>
        internal static string Not_Landon {
            get {
                return ResourceManager.GetString("Not_Landon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, Ryan, I know we&apos;ve been avoiding this subject for a while, but....
        /// </summary>
        internal static string Now_Ryan_I_know_weve_been_avoiding_this_subject_for_a_while_but {
            get {
                return ResourceManager.GetString("Now_Ryan_I_know_weve_been_avoiding_this_subject_for_a_while_but", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course. I just want what&apos;s best for my son..
        /// </summary>
        internal static string Of_course_I_just_want_whats_best_for_my_son {
            get {
                return ResourceManager.GetString("Of_course_I_just_want_whats_best_for_my_son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, I don&apos;t know... Odd, I guess. I just don&apos;t know if I believe it..
        /// </summary>
        internal static string Oh_I_dont_know_Odd_I_guess_I_just_dont_know_if_I_believe_it {
            get {
                return ResourceManager.GetString("Oh_I_dont_know_Odd_I_guess_I_just_dont_know_if_I_believe_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, but maybe if I&apos;d been around more often, or spent more time with him..
        /// </summary>
        internal static string Okay_but_maybe_if_Id_been_around_more_often_or_spent_more_time_with_him {
            get {
                return ResourceManager.GetString("Okay_but_maybe_if_Id_been_around_more_often_or_spent_more_time_with_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps Cynthia told him?.
        /// </summary>
        internal static string Perhaps_Cynthia_told_him {
            get {
                return ResourceManager.GetString("Perhaps_Cynthia_told_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryan, I can&apos;t lie to you. That&apos;s... that&apos;s concerning behavior. Is he still doing that?.
        /// </summary>
        internal static string Ryan_I_cant_lie_to_you_Thats_thats_concerning_behavior_Is_he_still_doing_that {
            get {
                return ResourceManager.GetString("Ryan_I_cant_lie_to_you_Thats_thats_concerning_behavior_Is_he_still_doing_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See, pretty much every weekend, when he thinks nobody is looking, Landon goes off into the belt of forest behind our home, and doesn&apos;t come back for a couple of hours..
        /// </summary>
        internal static string See_pretty_much_every_weekend_when_he_thinks_nobody_is_looking_Landon_goes_off_into_the_belt_of_forest_behind_our_home_and_doesnt_come_back_for_a_couple_of_hours {
            get {
                return ResourceManager.GetString("See_pretty_much_every_weekend_when_he_thinks_nobody_is_looking_Landon_goes_off_in" +
                        "to_the_belt_of_forest_behind_our_home_and_doesnt_come_back_for_a_couple_of_hours" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, one Saturday afternoon, I decided to follow after him. I waited until he left the house and scaled over the back fence, and then I went..
        /// </summary>
        internal static string So_one_Saturday_afternoon_I_decided_to_follow_after_him_I_waited_until_he_left_the_house_and_scaled_over_the_back_fence_and_then_I_went {
            get {
                return ResourceManager.GetString("So_one_Saturday_afternoon_I_decided_to_follow_after_him_I_waited_until_he_left_th" +
                        "e_house_and_scaled_over_the_back_fence_and_then_I_went", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started staying at home in his room, like he does most school nights..
        /// </summary>
        internal static string Started_staying_at_home_in_his_room_like_he_does_mosts_school_nights {
            get {
                return ResourceManager.GetString("Started_staying_at_home_in_his_room_like_he_does_mosts_school_nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure..
        /// </summary>
        internal static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure, I know it can, it&apos;s just... you&apos;ve heard the way I describe him. Does it sound like Asperger&apos;s to you?.
        /// </summary>
        internal static string Sure_I_know_it_can_its_just_youve_heard_the_way_I_describe_him_Does_it_sound_like_Aspergers_to_you {
            get {
                return ResourceManager.GetString("Sure_I_know_it_can_its_just_youve_heard_the_way_I_describe_him_Does_it_sound_like" +
                        "_Aspergers_to_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teenagers are difficult, mentally ill or not. You&apos;ve got to try, Ryan. For your family. You know how important it is..
        /// </summary>
        internal static string Teenagers_are_difficult_mentally_ill_or_not_Youve_got_to_try_Ryan_For_your_family_You_know_how_important_it_is {
            get {
                return ResourceManager.GetString("Teenagers_are_difficult_mentally_ill_or_not_Youve_got_to_try_Ryan_For_your_family" +
                        "_You_know_how_important_it_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That psychiatrist he&apos;s seeing doesn&apos;t know Landon like I do. He hasn&apos;t seen what I&apos;ve seen him doing..
        /// </summary>
        internal static string That_psychiatrist_hes_seeing_doesnt_know_Landon_like_I_do_He_hasnt_seen_what_Ive_seen_him_doing {
            get {
                return ResourceManager.GetString("That_psychiatrist_hes_seeing_doesnt_know_Landon_like_I_do_He_hasnt_seen_what_Ive_" +
                        "seen_him_doing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s true. I don&apos;t know, I just can&apos;t shake the feeling that I&apos;m... I&apos;m missing something? Something big about his behavior..
        /// </summary>
        internal static string Thats_true_I_dont_know_I_just_cant_shake_the_feeling_that_Im_Im_missing_something_Something_big_about_his_behavior {
            get {
                return ResourceManager.GetString("Thats_true_I_dont_know_I_just_cant_shake_the_feeling_that_Im_Im_missing_something" +
                        "_Something_big_about_his_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s what Cynthia thought when I told her, but I don&apos;t think that&apos;s it. I think he genuinely liked it..
        /// </summary>
        internal static string Thats_what_Cynthia_thought_when_I_told_her_but_I_dont_think_thats_it_I_think_he_genuinely_liked_it {
            get {
                return ResourceManager.GetString("Thats_what_Cynthia_thought_when_I_told_her_but_I_dont_think_thats_it_I_think_he_g" +
                        "enuinely_liked_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loud noises?.
        /// </summary>
        internal static string The_loud_noises {
            get {
                return ResourceManager.GetString("The_loud_noises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pan came crashing down, right next to Landon. I panicked and threw my hand out..
        /// </summary>
        internal static string The_pan_came_crashing_down_right_next_to_Landon_I_panicked_and_threw_my_hand_out {
            get {
                return ResourceManager.GetString("The_pan_came_crashing_down_right_next_to_Landon_I_panicked_and_threw_my_hand_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screaming. The pain. Sometimes I wonder if he still does..
        /// </summary>
        internal static string The_screaming_The_pain_Sometimes_I_wonder_if_he_still_does {
            get {
                return ResourceManager.GetString("The_screaming_The_pain_Sometimes_I_wonder_if_he_still_does", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...then I got closer, and....
        /// </summary>
        internal static string then_I_got_closer_and {
            get {
                return ResourceManager.GetString("then_I_got_closer_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They weren&apos;t dolls?.
        /// </summary>
        internal static string They_werent_dolls {
            get {
                return ResourceManager.GetString("They_werent_dolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the bullies?.
        /// </summary>
        internal static string To_the_bullies {
            get {
                return ResourceManager.GetString("To_the_bullies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, his anti-social behavior certainly could be a sign. You&apos;ve told me he has lots of trouble making friends..
        /// </summary>
        internal static string Well_his_antisocial_behavior_certainly_could_be_a_sign_Youve_told_me_he_has_lots_of_trouble_making_friends {
            get {
                return ResourceManager.GetString("Well_his_antisocial_behavior_certainly_could_be_a_sign_Youve_told_me_he_has_lots_" +
                        "of_trouble_making_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well... it&apos;s difficult to talk about the people that have hurt us, especially for a teenager..
        /// </summary>
        internal static string Well_its_difficult_to_talk_about_the_people_that_have_hurt_us_especially_for_a_teenager {
            get {
                return ResourceManager.GetString("Well_its_difficult_to_talk_about_the_people_that_have_hurt_us_especially_for_a_te" +
                        "enager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, that&apos;s wonderful..
        /// </summary>
        internal static string Well_thats_wonderful {
            get {
                return ResourceManager.GetString("Well_thats_wonderful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, yes, but it was more than that I mean, there&apos;s something, from when he was younger, and at the time I thought maybe I was imagining it, but now....
        /// </summary>
        internal static string Well_yes_but_it_was_more_than_that_I_mean_theres_something_from_when_he_was_younger_and_at_the_time_I_thought_maybe_I_was_imagining_it_but_now {
            get {
                return ResourceManager.GetString("Well_yes_but_it_was_more_than_that_I_mean_theres_something_from_when_he_was_young" +
                        "er_and_at_the_time_I_thought_maybe_I_was_imagining_it_but_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you talking about?.
        /// </summary>
        internal static string What_are_you_talking_about {
            get {
                return ResourceManager.GetString("What_are_you_talking_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you see?.
        /// </summary>
        internal static string What_did_you_see {
            get {
                return ResourceManager.GetString("What_did_you_see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you mean by &quot;troubled&quot;?.
        /// </summary>
        internal static string What_do_you_mean_by_troubled {
            get {
                return ResourceManager.GetString("What_do_you_mean_by_troubled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What if it&apos;s too late? He&apos;s so attached to his mother now. He barely speaks to me..
        /// </summary>
        internal static string What_if_its_too_late_Hes_so_attached_to_his_mother_now_He_barely_speaks_to_me {
            get {
                return ResourceManager.GetString("What_if_its_too_late_Hes_so_attached_to_his_mother_now_He_barely_speaks_to_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was it for Landon?.
        /// </summary>
        internal static string What_was_it_for_Landon {
            get {
                return ResourceManager.GetString("What_was_it_for_Landon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, he does. At least, I think he does. He never brings anybody home, anyways. Do you think he&apos;ll ever get any better about that?.
        /// </summary>
        internal static string Yeah_he_does_At_least_I_think_he_does_He_never_brings_anybody_home_anyways_Do_you_think_hell_ever_get_any_better_about_that {
            get {
                return ResourceManager.GetString("Yeah_he_does_At_least_I_think_he_does_He_never_brings_anybody_home_anyways_Do_you" +
                        "_think_hell_ever_get_any_better_about_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. Like, to purposefully hurt somebody the way he did that one kid... the kid had to have done something pretty awful to him..
        /// </summary>
        internal static string Yes_Like_to_purposefully_hurt_somebody_the_way_he_did_that_one_kid_the_kid_had_to_have_done_something_pretty_awful_to_him {
            get {
                return ResourceManager.GetString("Yes_Like_to_purposefully_hurt_somebody_the_way_he_did_that_one_kid_the_kid_had_to" +
                        "_have_done_something_pretty_awful_to_him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may be right, Ryan. But for the time being, the diagnosis should be a good thing..
        /// </summary>
        internal static string You_may_be_right_Ryan_But_for_the_time_being_the_diagnosis_should_be_a_good_thing {
            get {
                return ResourceManager.GetString("You_may_be_right_Ryan_But_for_the_time_being_the_diagnosis_should_be_a_good_thing" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You mean to say he was slow to show emotion?.
        /// </summary>
        internal static string You_mean_to_say_he_was_slow_to_show_emotion {
            get {
                return ResourceManager.GetString("You_mean_to_say_he_was_slow_to_show_emotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ought to know that..
        /// </summary>
        internal static string You_ought_to_know_that {
            get {
                return ResourceManager.GetString("You_ought_to_know_that", resourceCulture);
            }
        }
    }
}
